### ISSUE TITLE
Required skills

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/taas-app#1]
In the UI, currently we are showing required skills and other skills. Remove that separation and just consider like all skills of jobs are required. Change the title to `Job Skills`

![image](https://user-images.githubusercontent.com/2202045/98572412-b2558d00-22dd-11eb-8d2e-3ef76dba86c0.png)

**Comment by maxceem** [comment]
This is done via the challenge https://www.topcoder.com/challenges/30154890/?type=develop, so I'm closing this.
