### ISSUE TITLE
Not able to view the job details if job is created using api

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#103]
Description:
Not able to view the job details if job is created using api.

Steps to reproduce:
1. Create a job using api POST request.
2. Click the job created ,in the UI.

sample: https://platform.topcoder-dev.com/taas/myteams/17091/positions/516830b2-ac5a-4388-a2c4-d331ce253be9

![image](https://user-images.githubusercontent.com/55895538/108317549-cb85a800-7201-11eb-8d84-0a384445a53d.png)

https://user-images.githubusercontent.com/55895538/108317678-fd970a00-7201-11eb-9e4f-171239be4da0.mp4

**Comment by maxceem** [comment]
Done by https://github.com/topcoder-platform/taas-app/commit/c375bb545c6a93933d91dcbbc3e4fc1490c0f031 and ready for QA on DEV.

**Comment by sandhiyakavi** [comment]
Verified. Able to view the job details now.


https://user-images.githubusercontent.com/55895538/108340329-cdf4fb80-721b-11eb-8086-de35aedb6a3f.mp4

**Comment by sandhiyakavi** [comment]
Fixed: 🆗 in Production via milestone v1.5

![image](https://user-images.githubusercontent.com/55895538/109266218-17ac9a00-784b-11eb-82f3-34122d0ef92f.png)
![image](https://user-images.githubusercontent.com/55895538/109266276-2bf09700-784b-11eb-9b78-5b69da5cd163.png)
