### ISSUE TITLE
Create Job page: up/down arrow of Number of opening textbox increases/decreases value by decimal point.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#105]
Description:

Up/down arrow of "Number of opening" textbox in Create Job page, increases/decreases value by decimal point but decimal point values are not allowed for Number of Openings field.

https://user-images.githubusercontent.com/55895538/108460827-ccc7db00-72bc-11eb-9528-e927dc30f070.mp4

**Comment by sandhiyakavi** [comment]
Similar issue for Duration field also.

![image](https://user-images.githubusercontent.com/55895538/108463637-1a931200-72c2-11eb-9c0b-8bb8657d8307.png)

**Comment by maxceem** [comment]
Fixed by https://github.com/topcoder-platform/taas-app/commit/850ce75c89a20a2dcad332cfcb01e79cd92f6068.

Ready for QA on DEV.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Working as expected.


https://user-images.githubusercontent.com/55895538/108474899-584c6680-72d3-11eb-8288-192a1f455977.mp4

**Comment by codejamtc** [comment]
Fixed: 🆗 via milestone https://github.com/topcoder-platform/taas-app/milestone/3

https://user-images.githubusercontent.com/42398485/109163413-5258f880-779f-11eb-8d49-9725754f3fc2.mp4
