### ISSUE TITLE
RecruitCRM Integration - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#11]
**Use Case 1:  Candidate tied to an open Job in Recruit CRM**

IF member DOES NOT exist in v5/users (matched using handle):
- Create the user in v5/users and associate to Topcoder organization.
- Continue steps below

- Create a record in jobCandidates on platform associating the member back to the job to which they have been assigned.

**Use Case 2: Candidate Rejected in RCRM**

IF member is rejected in RCRM (hiring status set to: 'Rejected - Topcoder Rejected`, `Client Rejected - Interview No Show`, `Client Rejected - Interview`, `Client Rejected - Screening`, `Offered - Did Not Join`, `Client Closed Opportunity`)

- Set jobCandidate status = `Rejected`
- Candidate should display in the "Not Interested" tab in the UI

**Use Case 3: Candidate Placed in RCRM**

When RCRM status is set to `Placed`:

- set jobCandidate status = Selected
- Create a resourceBooking related to the job/project
- Assign the member to the resourceBooking
- Set resourceBooking Dates to job StartDate and EndDate

**Use Case 4: Job created in v5/jobs**

When a new job record is created in v5/jobs:

- Create the Job in RecrutiCRM
- Associate the job to the RCRM Company "TaaS Intake Holding Company" (RCRM slug: 41373157)
- Ensure the job application form is DISABLED when created autoamtically.

**Comment by SathyaJayabal** [comment]
@wdprice, we should also include creation of jobs in RCRM once the a Taas project is created in connect
Step 5 in the below description
https://github.com/topcoder-platform/taas-app/issues/5#issue-750894805

**Comment by wdprice** [comment]
I think that can logically live in either ticket.

Let me know your preference on tracking this requirement @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@wdprice , I think it will be better to track it here as everything else is complete on the other ticket.

**Comment by wdprice** [comment]
@SathyaJayabal updated the ticket

**Comment by SathyaJayabal** [comment]
1. Job Description field  provided in connect is used as Job  title in RCRM
2. The below status updates through Zap are not happening:
Candidate status update to shortlist in RCRM - not updated to Taas
Candidate status update to rejected in RCRM - not updated to Taas
Candidate status update to reject in Taas - not updated to RCRM

Reference :https://github.com/topcoder-platform/taas-apis/wiki

**Comment by maxceem** [comment]
@nkumar-topcoder would you be able to have a look at the QA feedback here, as I cannot verify this part.

**Comment by SathyaJayabal** [comment]
> @nkumar-topcoder would you be able to have a look at the QA feedback here, as I cannot verify this part.

@maxceem , @nkumar-topcoder is aware of the issues, we tested them together. I am documenting here to keep track.

**Comment by SathyaJayabal** [comment]
This is verified in dev and works as expected.

**Comment by SathyaJayabal** [comment]
Verified on prod
