### ISSUE TITLE
Fix permissions for BookingManagers users when they are not project members

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#111]
Follow up form https://github.com/topcoder-platform/taas-app/issues/14#issuecomment-784239658

> 1. Booking Manager was not able to access the "Manage Access" page .Getting error " You do not have permissions to perform this action" but able to access the project and all its features. Booking Manager is able to access "Manage access" page only when added as member.
credential used: bookingmanager/Appirio123
> <img width="960" alt="booking manager_not able to access" src="https://user-images.githubusercontent.com/55895538/108847663-4f38fd80-7623-11eb-9fed-6a2896c77490.png">

At the moment we have permission issues with BookingManagers users when they are not members of the project.

**Comment by maxceem** [comment]
@sandhiyakavi this is ready for testing on DEV. Now pure `bookingmanager` users should have any permission issues.

**Comment by sandhiyakavi** [comment]
Verified on dev. Booking Manager is now having all the privileges even if not a member of the project.

![image](https://user-images.githubusercontent.com/55895538/109111755-d2ba3200-777c-11eb-93d4-487c6accd7f2.png)
![image](https://user-images.githubusercontent.com/55895538/109111784-e1084e00-777c-11eb-80d8-1d8933159661.png)

**Comment by lakshmiathreya** [comment]
lakshmia3006 is a bookingmanager in Prod:
<img width="1680" alt="Screenshot 2021-02-25 at 8 28 36 PM" src="https://user-images.githubusercontent.com/51733042/109172722-1aef4980-77a9-11eb-9a19-4fe9b59a295d.png">
<img width="1680" alt="Screenshot 2021-02-25 at 8 28 39 PM" src="https://user-images.githubusercontent.com/51733042/109172743-1f1b6700-77a9-11eb-8eff-8292485f7456.png">
<img width="1680" alt="Screenshot 2021-02-25 at 8 32 43 PM" src="https://user-images.githubusercontent.com/51733042/109172748-204c9400-77a9-11eb-831b-64d0b75d0da2.png">
