### ISSUE TITLE
Allow user who created Job to edit it

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#112]
As a part of this issue https://github.com/topcoder-platform/taas-app/issues/12 we have to allow editing jobs for users who have permissions for that.

![image](https://user-images.githubusercontent.com/146016/108857819-25b4ad80-75f4-11eb-9362-3df5e01685a0.png)

At the moment we are only allowing editing jobs to the BookingManagers and Administrators, but we don't allow edit jobs to customer users who create such jobs.

The reason for this, because TaaS API uses V5 user ids to for `createdBy` and `updatedBy` fields:

```js
{ // example job object
  title: "Job title",
  createdBy: "57646ff9-1cd3-4d3c-88ba-eb09a395366c", // <----- V5 User ID
  updatedBy: "077fd578-7463-457f-b6ef-22c02178d7f5"
  // other fields
}
```

But we don't know the V5 user id of the logged in user, we only know V3 `userId` and `handle`:
```js
{
   userId: 40159127 // <----- V5 User ID
   handle: "pshah_manager"
}   
```

So we have to know somehow V5 User id of the logged-in user client-side. I'm not sure if we have such an endpoint that could be called by any user to obtain it.

FYI @nkumar-topcoder

**Comment by sandhiyakavi** [comment]
According to my observation, eventhough the creator of the job don't have Edit Job details button, he still be able to edit the job by accessing the Edit job page url.

**Comment by nkumar-topcoder** [comment]
@maxceem 
Pls let me know if below approach helps. 

1. get `createdby` userid from jobs api.
2. pass the `UUID` to v5/users. This will fetch userhandle.
`http://api.topcoder-dev.com/v5/users/f8eca99a-xxxxxxxxxxxxxxx`
3. via userhandle we can call v3/users or v5/users and get related user info

And go-ahead for enhancement if it's fine.

**Comment by maxceem** [comment]
@nkumar-topcoder we've created endpoint `/taas-teams/me` which returns the V5 user profile for the current user which we can use to implement this feature.

Sum up:
- We have `withAuthentication` HOC which takes care of user authentication and loads all the data related to user details and permissions. It wraps all the pages with authentication.
- `withAuthentication` HOC should additionally load V5 user profile. V5 user profile is returned by endpoint `GET ${config.API.V5}/taas-teams/me`.
    
   ![image](https://user-images.githubusercontent.com/146016/118241859-4ed33480-b4a5-11eb-851b-f48d0866d5fc.png)

   - make sure to correctly use Redux actions similar to how we load `teamMembers`
   - if an error happens then it should go to `<LoadingIndicator error=` then this error would appear like this https://monosnap.com/file/jTxdvBwknttmFTLIN7zI89eFdZeFg3

- Here is demo project which was created by `pshah_customer` https://platform.topcoder-dev.com/taas/myteams/17334. And in particular here is a job which was created by `pshah_customer` https://platform.topcoder-dev.com/taas/myteams/17334/positions/5b84a3bc-b759-4648-aa16-ff8232779501

- At the moment `pshah_customer` cannot see edit button even though he created this job, see screenshot https://monosnap.com/file/dLkddj5wkZgylc09r6QRaaY0nDbZ45

- So we should allow users to edit the job they created, so basically we have to add one more check here https://github.com/topcoder-platform/taas-app/blob/dev/src/routes/JobDetails/index.jsx#L109. If Job was created by the current user. Note, that job `createdBy` holds v5 user id, which we can get from Redux store now from `authUser.v5UserProfile.id`.

**Comment by maxceem** [comment]
@yoution would you like to handle it as a private task as per the comment above https://github.com/topcoder-platform/taas-app/issues/112#issuecomment-841097505?

Payment $50.

**Comment by yoution** [comment]
@maxceem please assign to me

**Comment by maxceem** [comment]
@yoution assigned

Branch to work: `master`. Create PR.

**Comment by maxceem** [comment]
@sandhiyakavi @SathyaJayabal this is fixed and ready for testing in DEV.

**Comment by sandhiyakavi** [comment]
Verified below cases in Dev. Working as expected.

1. Edit Job details button available and able to edit if member created Job from Taas app /Connect.
2. The permission level for the Booking Manager and Topcoder manager is correct.


https://user-images.githubusercontent.com/55895538/118754148-66455f80-b8a1-11eb-80c7-1460c94fd418.mp4

**Comment by sandhiyakavi** [comment]
Verified in Prod. 

Edit Job details button available and able to edit if member created Job from Taas app /Connect.

https://user-images.githubusercontent.com/55895538/119447234-9641a680-bd6a-11eb-84ac-c526608f11cb.mp4
