### ISSUE TITLE
RCRM Job Candidate Shortlist Status Integration Loop

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#114]
A loop exists in RCRM Job Candidate Status updates. This bug loops as follows:
1. Candidate Status in RCRM set to Interview Scheduled, Schedule Interview, Resume Handoff to Client, Phone Screening Organized, Shortlist
2.  Zapier Job `5 PROD - JOBCANDIDATE Update All Status RCRM to TaaS` executes and sets TaaS App JobCandidate Status = `shortlist`
3. Zapier Job `4-PROD-JOBCANDIDATE-Status-to-Rcrm` picks up webhook with the JobCandidate status update from previous step, updates the corresponding job back to `Shortlist` status in RCRM.

**Solution agreed upon by team**
1. Update TaaS App API to allow a new status on the JobCandidate object: `interview`
2. Update TaaS App Front end JobCandidate review page to display JobCandidate records with status = `interview` on the "Interested" tab, and to not display them on the "To Review" tab
3. Update Zap `5 PROD - JOBCANDIDATE Update All Status RCRM to TaaS`  to set status = `interview` instead of the current value of `shortlist`

**Comment by maxceem** [comment]
This was fixed on PROD and DEV.

@nkumar-topcoder do you know if Zapier was updated on DEV accordingly? I know @wdprice did update it on PROD, though for testing on DEV, we have to update Zapier on DEV too.

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with help from @nkumar-topcoder .Working as expected.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Candidate status is not changed to shortlist in RCRM.

![image (22)](https://user-images.githubusercontent.com/55895538/109141295-ed060700-77a0-11eb-97d1-a333b4f067d0.png)

**Comment by SathyaJayabal** [comment]
labelling as p0 as it required a hotfix
cc @lakshmiathreya
