### ISSUE TITLE
Manage Access - email additions

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#119]
The Manage Access page says you can add an email:
![image](https://user-images.githubusercontent.com/6014049/109161454-11cc9100-7745-11eb-9fcc-8d8e7f6dda35.png)

However if you try to input anything, you get an `Internal Server Error`:
![image](https://user-images.githubusercontent.com/6014049/109161511-26108e00-7745-11eb-966e-1ae85eca2a24.png)

Need to either remove the option to input email, or provide useful error messaging to inform the user why they cannot add this particular email.

**Comment by maxceem** [comment]
This shouldn't happen. I will investigate.

**Comment by maxceem** [comment]
@wdprice this is fixed on PROD now. You should be able to invite users by email.

**Comment by SathyaJayabal** [comment]
verified, was able to add users using their email
<img width="1440" alt="Screenshot 2021-03-03 at 10 51 14 AM" src="https://user-images.githubusercontent.com/58783823/109756833-a6843280-7c0e-11eb-88cf-86c11beb87f1.png">

**Comment by lakshmiathreya** [comment]
This prompted a hotfix - should have been marked P0.
