### ISSUE TITLE
Jobs Edit UI

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#12]
Implement a UI for viewing & editing the details on a job from the Team Details page.

Must be able to view:
All fields except memberRate and system fields (createdBy, createdTime, externalID, etc.)

Must be able to edit:

Job Name
Job Description
Number of Openings
Job Skills

Only someone with access to the project can edit a a related job record, or TC admins.

**Comment by maxceem** [comment]
Should we also be able to **create** new jobs from UI?

**Comment by wdprice** [comment]
Undecided at this time, but it won't be in until a later release if so, and we will add an additional ticket for it.

This feature is slated for a followup release and not for v1.0, so don't dedicate cycles here just yet.

**Comment by maxceem** [comment]
@wdprice 

### Sum up:
1. Implement Job View page as per new design https://marvelapp.com/prototype/921gg0f/screen/75360459/handoff

   - But also show "Start Date", "End Date", "Resource Type", "Rate Type", "Workload" and "Status"

    ![image](https://user-images.githubusercontent.com/146016/105059229-b7724d80-5a7f-11eb-8060-7291e587b7d2.png)
    
2. Clicking "Eidt Job Details" should open edit job page https://marvelapp.com/prototype/921gg0f/screen/75360460/handoff

    ![image](https://user-images.githubusercontent.com/146016/105060042-9b22e080-5a80-11eb-83ea-1be64b3fe6f9.png)

### Questions:

1. What do these icons mean in the new design?:

   ![image](https://user-images.githubusercontent.com/146016/105058908-64989600-5a7f-11eb-91ab-40654d02bd1e.png)
   
2. To open Job View page, we should click Job Title, right?

    ![image](https://user-images.githubusercontent.com/146016/105059068-93167100-5a7f-11eb-80be-f03c1689d788.png)
    
3. > All fields except memberRate

    Just to confirm, Job model at the moment doesn't have "memberRate" so we cannot show it and shouldn't hide it yet.

4. As per design "Number of Openings" is Select, but I guess it should be text input which should only allow numbers 0 and more.

   ![image](https://user-images.githubusercontent.com/146016/105059912-775f9a80-5a80-11eb-9bc0-ee2a10ec4efa.png)

5. Should we also allow editing other fields "Start Date", "End Date", "Resource Type", "Rate Type", "Workload" and "Status"?

**Comment by SathyaJayabal** [comment]
@maxceem @wdprice , these job updates must also be synced back to RCRM right?

**Comment by maxceem** [comment]
> @maxceem @wdprice , these job updates must also be synced back to RCRM right?

Nice catch @SathyaJayabal. @nkumar-topcoder what do you think about it?

**Comment by wdprice** [comment]
1. Also add duration. Calculate end date based on start date + duration (weeks)
2. We will need to handle zapier flow for updates to existing jobs.
3. Correct

Questions:
1. Icons removed in latest designs
2. Correct
3. Correct, that only exists on resourceBooking
4. TExt input is OK
5. Edit Requested Start Date + Duration (add requested to the label). See 1. above.
6. Yes, customer (or manager) role on Connect project can add a new job or edit.

**Comment by nkumar-topcoder** [comment]
> @maxceem @wdprice , these job updates must also be synced back to RCRM right?

@maxceem @wdprice @SathyaJayabal job updates to RCRM is already taken care in the initial sync. So, adding/updating new job should take. However, once the UI implemented need to take care of any edge case

**Comment by maxceem** [comment]
This is ready for QA on DEV, except for a few things:

### Not yet done:
- `duration` is not added yet, as business required are not yet confirmed, so for now we have start/end date
- Edit button, for now, is visible for all the users, we would hide it after we implement member access management https://github.com/topcoder-platform/taas-app/issues/14

**Comment by SathyaJayabal** [comment]
@maxceem , I do not see the edits made from the job edits page getting saved. There is no error on the PUT api call.


https://user-images.githubusercontent.com/58783823/107218856-367ef400-6a36-11eb-8b9e-010d3a8c4b30.mov

**Comment by maxceem** [comment]
Right, there should **not** be any error.

**Comment by sandhiyakavi** [comment]
Adding to the above,

1. Topcoder Member is not able to edit the job created along with the taas project in Connect (Taas project is created by the same Topcoder member) but has permission to edit the one created in the UI by the member.
![image](https://user-images.githubusercontent.com/55895538/107344462-d5265600-6b05-11eb-8ca7-78eb7d711ce9.png)
![image](https://user-images.githubusercontent.com/55895538/107344556-eec79d80-6b05-11eb-8197-ca10c650dbb1.png)


2. Able to add End date less than the Start date

![image](https://user-images.githubusercontent.com/55895538/107343767-06525680-6b05-11eb-9cb8-4de102a805bb.png)

3. Able to set Status for Job as Closed/Cancelled while Creating the Job.

![image](https://user-images.githubusercontent.com/55895538/107344050-5cbf9500-6b05-11eb-9e49-db35ab63a1da.png)

**Comment by maxceem** [comment]
@SathyaJayabal editing jobs works now. Changes should be reflected after you save the Job. Please, let me know if you have such issues again.

**Comment by sandhiyakavi** [comment]
@maxceem Able to Edit jobs now but
1.Able to set status as 'Assigned' for a job even if no candidate is assigned to the job. User should not be allowed to change status 'Assigned' in this scenario right?

![image](https://user-images.githubusercontent.com/55895538/107351107-92687c00-6b0d-11eb-9c74-fde2d50fefff.png)

2. The issues mentioned in comment https://github.com/topcoder-platform/taas-app/issues/12#issuecomment-775802158 is existing

**Comment by maxceem** [comment]
> Topcoder Member is not able to edit the job created along with the taas project in Connect (Taas project is created by the same Topcoder member) but has permission to edit the one created in the UI by the member.

Great catch, and valid issue. We would fix it in Projects API.

> Able to add End date less than the Start date

Will add validation.

### Questions to Bussiness

Should we add any restrictions for these or we can keep these as it is.

1. Able to set Status for Job as Closed/Cancelled while Creating the Job.

2.Able to set status as 'Assigned' for a job even if no candidate is assigned to the job. User should not be allowed to change status 'Assigned' in this scenario right?

**Comment by wdprice** [comment]
Let's place the status field in read only only. Only BookingManager / Topcoder Admin can edit those fields.

**Comment by maxceem** [comment]
@sandhiyakavi some of the issues are fixed now. And for some of them I've created separate issue for easier control. So after testing the fixed part, could we mark this issue as QA passed, and we would handle not yet fixed issues separately.

> 1. Topcoder Member is not able to edit the job created along with the taas project in Connect (Taas project is created by the same Topcoder member) but has permission to edit the one created in the UI by the member.

Already fixed. You may test it by creating a new Project. For the Project which is already created, it cannot be fixed.

> 2. Able to add End date less than the Start date

This would be fixed by https://github.com/topcoder-platform/taas-app/issues/84

> 3. Able to set Status for Job as Closed/Cancelled while Creating the Job.
> 4.Able to set status as 'Assigned' for a job even if no candidate is assigned to the job. User should not be allowed to change status 'Assigned' in this scenario right?

As per Will clarification, we would not fix these. But we would add restriction on who can change status. This would be done by https://github.com/topcoder-platform/taas-app/issues/83

**Comment by sandhiyakavi** [comment]
Verified in Dev env .Comment #1 is working now

![image](https://user-images.githubusercontent.com/55895538/107908599-c3c3ca80-6f99-11eb-80f1-0f3c275b56a4.png)

**Comment by sandhiyakavi** [comment]
Fixed: 🆗 in Production via milestone v1.5

1. Able to create job
![image](https://user-images.githubusercontent.com/55895538/109269602-103bbf80-7850-11eb-9dab-cec68ad92ef2.png)
2. View Job details page.
![image](https://user-images.githubusercontent.com/55895538/109269681-2e092480-7850-11eb-8b66-e3ed80e21408.png)

@lakshmiathreya Edit Job details button is visible only to BookingManager/Admin. Need to try Job editing using Booking Manager role.

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-02-26 at 2 04 16 PM" src="https://user-images.githubusercontent.com/51733042/109276088-9ac5f400-783b-11eb-997e-2a5b863740a5.png">
<img width="1680" alt="Screenshot 2021-02-26 at 2 06 26 PM" src="https://user-images.githubusercontent.com/51733042/109276374-f1333280-783b-11eb-9bb4-21c5a2478ed7.png">

**Comment by lakshmiathreya** [comment]
lakshmia3006 is a bookingmanager in Prod ...
