### ISSUE TITLE
Incorrect Link in Issue Report Emails

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#121]
Issue report emails contain a link to topcoder-dev, not to prod environment. See test email below:

![image](https://user-images.githubusercontent.com/6014049/109169828-337e4600-774e-11eb-870a-951ec494b451.png)

**Comment by maxceem** [comment]
@wdprice this should work good now on PROD. I've sent a test report "Test report issue from "maxceem". The link to the project should work good now.". Please, let me know if it works good now, as I cannot read the email.

**Comment by SathyaJayabal** [comment]
@wdprice , sent test reports from PROD with issue link. Will need help from you to verify if the reports were sent to the correct email addresses.

cc @maxceem

**Comment by sandhiyakavi** [comment]
Closing this issue as it's confirmed with @wdprice
