### ISSUE TITLE
When we click on the URL posted on the description; it is redirected to an invalid url

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/taas-app#122]
**Testing URL:** https://platform.topcoder-dev.com/taas/myteams/16873/positions/edda7f39-5297-461a-89be-2074faa8bdc8

- When we click on the URL posted on the description; it is redirected to `https://platform.topcoder-dev.com/taas/myteams/16873/positions/www.google.com` and displayed an error '"id" must be a valid GUID'

https://user-images.githubusercontent.com/42398485/108969022-881ab600-76a7-11eb-939e-cbb0222b18f0.mp4

**Comment by SathyaJayabal** [comment]
Verified on dev

https://user-images.githubusercontent.com/58783823/109753358-1e9b2a00-7c08-11eb-85f9-787d1a42f458.mov

@maxceem, Suggestion: should the link open in a new tab ?

**Comment by maxceem** [comment]
> Suggestion: should the link open in a new tab ?

As for me, this is a good idea. We can create a separate issue for this enhancement and confirm with WIll if he likes it.

**Comment by SathyaJayabal** [comment]
@wdprice , should we open the links in the description in a new tab? If its fine, I will create a separate issue as enhancement.

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.


https://user-images.githubusercontent.com/55895538/110459206-0a779100-8110-11eb-96bc-8fed440bdca6.mp4
