### ISSUE TITLE
Markdown Editor quick improvements

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#126]
Follow up from https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097 and https://github.com/topcoder-platform/taas-app/issues/74.

Related to this issue https://github.com/topcoder-platform/taas-app/issues/122

I suggest removing features:

- Table - because cannot be converted properly to RCRM (in theory can, but somehow doesn't work)
- Tasks - because don't need and cannot be displayed in RCRM
- Indent - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097
- Outdnet - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097

Editor before:

![image](https://user-images.githubusercontent.com/146016/109140252-12751f80-7765-11eb-9f5e-1a74ded19d13.png)

After:

![image](https://user-images.githubusercontent.com/146016/109140530-58ca7e80-7765-11eb-8fde-660a0316bff7.png)

**Comment by maxceem** [comment]
@wdprice could you please have a look on this issue. Is it ok to remove from the editor the features mentioned above, so they don't create problems to us, or do we need them?

We should do this the same for the editor in Connect and we already did that for demo https://connect-test01.topcoder-dev.com/new-project/taas-jobs (not in DEV and not in PROD yet). You may check it out.

**Comment by wdprice** [comment]
All good - removal of those features in both places is approved.

**Comment by SathyaJayabal** [comment]
verified on dev, Table, tasks, indent and outdent are removed
<img width="1440" alt="Screenshot 2021-03-03 at 10 16 53 AM" src="https://user-images.githubusercontent.com/58783823/109754224-a9305900-7c09-11eb-9375-33f99f30a0ef.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Tables, Task, Indent and Outdent are removed from both Create/Edit Job page.

![image](https://user-images.githubusercontent.com/55895538/110461323-a1454d00-8112-11eb-955b-f97fc285a06b.png)
![image](https://user-images.githubusercontent.com/55895538/110461465-cfc32800-8112-11eb-8238-2295461dddfd.png)
