### ISSUE TITLE
RB Status 'sourcing', 'in-review' still displayed in UI

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#147]
Description:

Status 'sourcing', 'in-review' still displayed in UI

![image](https://user-images.githubusercontent.com/55895538/115329969-17d37100-a1ce-11eb-9099-7a1633b1914f.png)

**Comment by maxceem** [comment]
@sandhiyakavi fixed in DEV:

![image](https://user-images.githubusercontent.com/146016/115355197-1cdef300-a1c3-11eb-818d-145c7afb1cec.png)

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. The status 'sourcing', 'in-review' removed.

![image](https://user-images.githubusercontent.com/55895538/115358649-d5735980-a1f8-11eb-8549-488d50c80416.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected

![image](https://user-images.githubusercontent.com/55895538/116072841-977ba700-a6ca-11eb-95a3-db8aa8ad5671.png)
