### ISSUE TITLE
Show/Edit Resource Bookings strat/end dates without time and timezone

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#150]
In API we've updated the Resource Bookings model to only store dates inside `startDate` and `endDate` https://github.com/topcoder-platform/taas-apis/issues/204

Now we have to update the UI for this:

- display the Resource Bookings dates as it is without timezone conversion, but in current date format
- edit Resource Booking page should load/updated dates correctly in a new format without any timezone conversion and save dates without time and timezones

**Comment by maxceem** [comment]
Here are the screenshots of the Resource Booking pages with dates BEFORE the migration of dates, we could compare after the migration.

https://platform.topcoder-dev.com/taas/myteams/16873

![image](https://user-images.githubusercontent.com/146016/115675960-c820b100-a357-11eb-9889-6b847fba5bdd.png)

https://platform.topcoder-dev.com/taas/myteams/16873/rb/7c057525-6ddd-4b62-abdf-1371ff678015

![image](https://user-images.githubusercontent.com/146016/115676023-dbcc1780-a357-11eb-9462-6a407a918953.png)

https://platform.topcoder-dev.com/taas/myteams/16873/rb/7c057525-6ddd-4b62-abdf-1371ff678015/edit

![image](https://user-images.githubusercontent.com/146016/115676076-e686ac80-a357-11eb-9052-a68096b3e8f5.png)

**Comment by SathyaJayabal** [comment]
verified on dev

Existing RB
https://platform.topcoder-dev.com/taas/myteams/16873
<img width="1440" alt="Screenshot 2021-04-22 at 5 51 39 PM" src="https://user-images.githubusercontent.com/58783823/115713359-89a8e780-a393-11eb-8311-6e4efe6b1e85.png">

https://platform.topcoder-dev.com/taas/myteams/16873/rb/7c057525-6ddd-4b62-abdf-1371ff678015
<img width="1440" alt="Screenshot 2021-04-22 at 5 51 36 PM" src="https://user-images.githubusercontent.com/58783823/115713375-8f9ec880-a393-11eb-9318-e5328b55abf8.png">

https://platform.topcoder-dev.com/taas/myteams/16873/rb/7c057525-6ddd-4b62-abdf-1371ff678015/edit
<img width="1440" alt="Screenshot 2021-04-22 at 5 51 35 PM" src="https://user-images.githubusercontent.com/58783823/115713397-962d4000-a393-11eb-8a51-ebead1b15f5e.png">


New RB
https://platform.topcoder-dev.com/taas/myteams/17283
<img width="1440" alt="Screenshot 2021-04-22 at 5 59 42 PM" src="https://user-images.githubusercontent.com/58783823/115714252-8a8e4900-a394-11eb-88f7-348299528b4e.png">

https://platform.topcoder-dev.com/taas/myteams/17283/rb/5a57eadb-a390-4777-8eba-8dc8984e9bbd
<img width="1440" alt="Screenshot 2021-04-22 at 6 00 09 PM" src="https://user-images.githubusercontent.com/58783823/115714305-9974fb80-a394-11eb-9ac9-0ccacd6632a4.png">

https://platform.topcoder-dev.com/taas/myteams/17283/rb/5a57eadb-a390-4777-8eba-8dc8984e9bbd/edit
<img width="1440" alt="Screenshot 2021-04-22 at 6 00 25 PM" src="https://user-images.githubusercontent.com/58783823/115714349-a5f95400-a394-11eb-856f-fb37e73c10c9.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/116072662-5edbcd80-a6ca-11eb-9f63-b0913b8c876e.png)
