### ISSUE TITLE
[$30] When BM declines candidate, the JC status must be updated to "client rejected - screening"

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#158]
When BM declines candidate, the JC status must be updated to "client rejected - screening". At present the FE tries to update to "rejected" and gets an error.

<img width="1440" alt="Screenshot 2021-04-28 at 9 58 29 PM" src="https://user-images.githubusercontent.com/58783823/116439184-e4977e80-a86c-11eb-9997-445e4fcb069d.png">

**Comment by cagdas001** [comment]
If it's rejected from the TO REVIEW list, the status will be `client rejected - screening`. If it's rejected from the INTERVIEW list, then  the status will be `client rejected - interview` Please confirm if this is correct

@urwithat @nikolay83

**Comment by SathyaJayabal** [comment]
@cagdas001 , if there is atleast one interview associated with the candidate, it will be client rejected - interview. So yes to your question.

**Comment by cagdas001** [comment]
If rejected without any interview record, it will be `client rejected - screening`. If rejected with at least one interview record, it will be `client rejected - interview`

**Comment by SathyaJayabal** [comment]
Verified. JC status is updated to `client rejected - screening` when there is no interview associated. JC status is updated to `client rejected - interview` when there is at least one interview associated.

**Comment by SathyaJayabal** [comment]
Verified on prod
