### ISSUE TITLE
[$30] While selecting a candidate JC status must be updated to "selected"

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#159]
While selecting a candidate JC status must be updated to `selected`. But the FE tries to update it to `shortlist`.
<img width="1440" alt="Screenshot 2021-04-28 at 9 59 57 PM" src="https://user-images.githubusercontent.com/58783823/116439513-43f58e80-a86d-11eb-9ea1-b82a43d5fd1a.png">

**Comment by cagdas001** [comment]
If selected from the TO REVIEW list, the status will be `selected` If selected from the INTERVIEWS list, the status will be `placed`. Please confirm if this is correct

@urwithat @nikolay83

**Comment by SathyaJayabal** [comment]
@cagdas001 ,  If selected from the INTERVIEWS list, the status will be still `selected`

**Comment by SathyaJayabal** [comment]
verified. Candidate status updated to `selected` when they are selected form the `To Review` and the `Interviews` tab.

**Comment by SathyaJayabal** [comment]
verified on prod
