### ISSUE TITLE
[$15] To Review Tab: Schedule Interview button doesn't close the popup and user is able to create more interviews  by clicking on the button repeatedly

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#161]
1.. Go to "To Review" tab of candidates review screen
2. Click on Schedule interview from actions drop down
3. Schedule an Interview popup opens
4. Click on Add More under Attendees section
5. Click on Begin Scheduling button.

Expected: An error message should be displayed asking the user to enter the email address if the field is mandatory. Else the flow should move on to the next step. 

Actual: The popup continues to be displayed and the user is able to click on `Begin Scheduling` again and again, creating multiple interview requests.

https://user-images.githubusercontent.com/58783823/116442033-aa7bac00-a86f-11eb-8a74-acf1bf2db638.mov

**Comment by nikolay83** [comment]
once we have candidate's and customer's e-mails fetched from member API, this will be expected behaviour. Should fix it now? @wdprice @urwithat

**Comment by SathyaJayabal** [comment]
@nikolay83 , on further testing, this doesn't seem to be the issue with empty email input. Sometimes when we click on the Schedule Interview button on the popup, the popup doesn't close and the interviews keep getting created when user clicks on schedule interview button.

This issue doesn't happen always.

https://user-images.githubusercontent.com/58783823/116509832-91abde80-a8e1-11eb-9691-c713d3220d7e.mov

**Comment by cagdas001** [comment]
This was happening in case of errors, but, since it wasn't reporting the errors this was causing confusion. It will now show a toast notification in case of any error. Also, I have fixed a few common issues, it should now work more robust

**Comment by SathyaJayabal** [comment]
verified. user is able to schedule interview form the "To Review" tab

https://user-images.githubusercontent.com/58783823/116652322-92587980-a9a2-11eb-9932-a8d97a5e9871.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/116899156-d7a3d200-ac54-11eb-8d44-a24c7296d453.mov
