### ISSUE TITLE
Unable to schedule an interview

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#162]
While scheduling an interview we get the error

interview.xaiTemplate" must be one of [interview-30, interview-60]
<img width="1440" alt="Screenshot 2021-04-28 at 10 42 56 PM" src="https://user-images.githubusercontent.com/58783823/116445111-20354700-a873-11eb-83bd-cfb35808e048.png">

Note: This was working fine sometime back

**Comment by SathyaJayabal** [comment]
This is working now @nikolay83

**Comment by nikolay83** [comment]
Ok, will close it.
