### ISSUE TITLE
[$15] Update "Select Candidate" Confirmation Page Text

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#164]
Update the text highlighted in the screenshot below:
![image](https://user-images.githubusercontent.com/6014049/116467278-80a99180-a83d-11eb-9baa-6a4005aead70.png)

New Text:

> You have selected this applicant - you want this member on your team!  What happens next:
> 1. Upon confirmation, Topcoder will confirm the arrangement with the selected member
> 2. A Topcoder Rep will contact you with details on the work arrangement
> 3. When both sides accept, we will finalize the agreement and begin onboarding

**Comment by wdprice** [comment]
CC: @urwithat

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/116651812-f721cd00-a9be-11eb-8635-3483b61fbbd1.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 18 24 PM" src="https://user-images.githubusercontent.com/58783823/116899417-2487a880-ac55-11eb-9e8b-33e99cf7f46f.png">
