### ISSUE TITLE
[$50] Default Email Addresses

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#165]
Schedule Interview screen should default to show the logged in user's email address:
![image](https://user-images.githubusercontent.com/6014049/116487195-62ec2480-a85d-11eb-9c47-457b36f5006c.png)

Additionally, the member identified in jobCandidate.id should be in the CC: field on the email, and their full name should be added to the payload passed to Kafka so the Sendgrid API call can include the `interviewee_name` dynamic field.

**Comment by wdprice** [comment]
CC: @urwithat

**Comment by SathyaJayabal** [comment]
@wdprice , should the Job candidate's email also be displayed by default in the above screen?

**Comment by nikolay83** [comment]
They should.
However, for now we couldn't retrieve any default e-mails due to member API issues. @urwithat could you advise if member API is fixed now?

**Comment by nikolay83** [comment]
IIRC, we agreed not to display candidate's e-mail

**Comment by wdprice** [comment]
Do not display the candidates email in the UI, it only needs to be passed in the payload.

**Comment by cagdas001** [comment]
To clarify, the UI will pass the candidate email to the backend right? So backend won't find any email based on candidate/customer etc., it'll send to whatever it gets from UI, as recipients.

**Comment by nikolay83** [comment]
Yes, as long as it's only GUI fetching the e-mail.

**Comment by cagdas001** [comment]
As the `/users?enrich=true` doesn't return `attributes` anymore, we'll have to find user email by its handle. For this, we have to call `/members/:userHandle` with an M2M token. So, we'll need to configure & generate M2M tokens at the frontend, which is not a good idea I think. In case of a bug like a memory leak, a user can easily access the M2M token. What about doing this at the backend, without exposing it to the end-users?

**Comment by nikolay83** [comment]
Yes, I've got the same concern, however, I think it's safe enough to fix it later.

**Comment by wdprice** [comment]
@urwithat - your call on the appraoch.

If we decide to fix later, let's ensure we have a tech debt ticket logged so we don't forget.

**Comment by nikolay83** [comment]
@wdprice 
I've logged it in my future Fix&Cleanup Code challenge not to forget.

**Comment by cagdas001** [comment]
Already done at the backend. We have missed the fact that `tc-core-library-js` (we use to generate token) is mainly a NodeJS library, caused too many issues when used in the ReactJS project. So, with the opened PR, the frontend doesn't have the mentioned issue, all the flow is in the backend. And candidate email is also not exposed to the frontend. (incl. req. payload) The backend automatically finds the email and adds it to the attendee list. See the backend PR for more details

**Comment by SathyaJayabal** [comment]
Verified, that the customer's email address is displayed  by default.
<img width="639" alt="Screenshot 2021-04-30 at 11 30 01 AM" src="https://user-images.githubusercontent.com/58783823/116654760-760b0b80-a9a7-11eb-844f-bd690da4d58e.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 19 19 PM" src="https://user-images.githubusercontent.com/58783823/116899514-408b4a00-ac55-11eb-862e-84563244ac8b.png">
