### ISSUE TITLE
Select Candidate Flow

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#166]
For the duration between when customer selects a candidate and the candidate is placed(and shows up as an RB/Team member) , where will the candidate be displayed ? Should we have a selected tab? 

For example, this is the current flow: 
1. Customer sees 4 candidates in the to review tab.
2. Customer schedules interview for 1, they show up in the interview tab
3. Customer declines one, They show up in the Declined tab
4. Customer selects a candidate, The candidate is removed from all tabs and will show up as a team member only when they are placed.
5. The customer does not know the status of the candidate that they selected. 

cc @wdprice

**Comment by wdprice** [comment]
Good point @SathyaJayabal. A selected tab would be great (but only if it is easy to implement quickly).

@nikolay83 - what do you think?

**Comment by SathyaJayabal** [comment]
@wdprice @urwithat , current implementation is when a candidate is selected from the `To Review` tab, they show up in the `Interviews` tab. When they are selected from the `Interviews` tab, they stay there. What should be the flow when the JC is selected, should we show the records on the UI and if so , under which tab?

**Comment by nikolay83** [comment]
@wdprice 
I believe not a big effort, can be included in the Cleanup challenge.

**Comment by SathyaJayabal** [comment]
@nikolay83 @urwithat @wdprice , so if we are not adding the new tab for this release, we have two options:

. display selected candidates under interview tab (current implementation)
- dont display selected candidates

**Comment by SathyaJayabal** [comment]
Verified, that selected tab is added and selected candidates are displayed under it
<img width="1440" alt="Screenshot 2021-05-01 at 1 01 43 PM" src="https://user-images.githubusercontent.com/58783823/116774916-6827ba00-aa7d-11eb-83c7-2d7f52aceab4.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 20 22 PM" src="https://user-images.githubusercontent.com/58783823/116899630-6add0780-ac55-11eb-8268-ab30aed9a08a.png">
