### ISSUE TITLE
Customer is able to schedule interviews even though the previous round is still scheduled/being scheduled

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#167]
Customer is able to schedule interviews even though the previous round is scheduled/being scheduled. Should this be allowed?
<img width="1440" alt="Screenshot 2021-04-29 at 8 37 27 AM" src="https://user-images.githubusercontent.com/58783823/116497936-2e608300-a8c6-11eb-8c4e-21cf5c8a3deb.png">

**Comment by nikolay83** [comment]
I assume a customer may want to plan >1 interviews with a candidate in parallel.

**Comment by wdprice** [comment]
@nikolay83 your interpretation is accurate. This is working as intended.
