### ISSUE TITLE
"Decline candidate" confirmation popup text

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#168]
Description:

The current text in "Decline candidate" confirmation popup from To Review tab is shown as "Are you sure you want to decline the selected candidate?" . The candidate is mentioned as "selected" though they are not selected.

<img width="959" alt="declinecand_selected" src="https://user-images.githubusercontent.com/55895538/116504151-ab095680-a8f2-11eb-910d-d911dc02fb27.png">

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , i think they mean the currently selected candidate (selected from the list of candidates)
