### ISSUE TITLE
Update code to trigger Zaps on new status changes

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#169]
When the following status JC changes are made from the taas app, the zaps to sync to RCRM must be triggered

Open->Interview (from review tab)
Open->Client - Rejected Screening (from review tab)
Open-> Selected (from review tab)
Interview->Client - Rejected Interview (from interview tab)
Interview -> Selected (from interview tab)

cc @nkumar-topcoder @urwithat @nikolay83

**Comment by nikolay83** [comment]
@urwithat from architecture PoV what should it at taas-app side? Not sure what to update so far?

**Comment by SathyaJayabal** [comment]
@nikolay83 , @nkumar-topcoder is working on this. Fixes to be made to the taas-es-processor.

**Comment by SathyaJayabal** [comment]
This is fixed thro
https://github.com/topcoder-platform/taas-es-processor/commit/90c4b4f52e6a40b358fa539a407dfbfb61db8e72

All JC Status updates between RCRM and Taas are working as expected
<img width="800" alt="Screenshot 2021-04-29 at 3 48 58 PM" src="https://user-images.githubusercontent.com/58783823/116536356-6eddf200-a902-11eb-9360-a95d5d5c3d0d.png">
