### ISSUE TITLE
Time Remaining on My Teams page language update required

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#17]
In the scenario that there are no resourceBookings on a team yet, the Time Remaining should read "TBD"

![image](https://user-images.githubusercontent.com/6014049/101373066-898fcb80-387a-11eb-87db-8253dc4ad1ed.png)

**Comment by maxceem** [comment]
Done via 4615fc9c9310e7641a932913d1cf7e8c85352c81

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-12-21 at 4 35 48 PM" src="https://user-images.githubusercontent.com/58783823/102770715-9a782b00-43aa-11eb-8ca2-2fe29ec07210.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 14 48 PM" src="https://user-images.githubusercontent.com/58783823/106146811-27c65080-619d-11eb-9989-5dbdf5cc3d0c.png">
