### ISSUE TITLE
[$25] The RB status 'Assigned' is still displayed in UI and 'Placed' displayed as unsupported value

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#170]
Description:

The RB status 'Assigned' is still displayed in UI and the new replaced status 'Placed' is displayed as 'Unsupported value: placed' 

<img width="956" alt="RB_status" src="https://user-images.githubusercontent.com/55895538/116510696-481ebc00-a900-11eb-8fba-d48428974a69.png">

**Comment by nkumar-topcoder** [comment]
@nikolay83 @urwithat 
 please update values from "assigned" to "placed"

https://github.com/topcoder-platform/taas-app/blob/cfeec2e85bf72fc115e8880d6fea8b378c803b5d/src/constants/index.js#L300

**Comment by SathyaJayabal** [comment]
@cagdas001 , test comment

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Displaying correctly.

![image](https://user-images.githubusercontent.com/55895538/116651575-76fb6780-a9be-11eb-91f8-16f3ee9d9665.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 23 09 PM" src="https://user-images.githubusercontent.com/58783823/116900063-f48cd500-ac55-11eb-82d6-2b7fe11aeda5.png">
