### ISSUE TITLE
[$25] Candidate with status 'rejected - other' are not getting displayed under Declined tab

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#171]
Description:

In existing records, the Job candidates with new status 'rejected - other' (changed from 'rejected' to 'rejected-other' are not getting displayed under declined tab.

![image](https://user-images.githubusercontent.com/55895538/116512951-d0529080-a903-11eb-85cc-ff2a3918aa6c.png)
![image](https://user-images.githubusercontent.com/55895538/116513048-f5df9a00-a903-11eb-8b5e-b7dd474fd887.png)

**Comment by SathyaJayabal** [comment]
@nikolay83 @sandhiyakavi Candidates with all three rejected statuses must be displayed here
`rejected-other` , `Client - Rejected Screening` and `Client - Rejected Interview`

**Comment by nikolay83** [comment]
@cagdas001

**Comment by cagdas001** [comment]
`rejected - other`, `client rejected - screening`, `client rejected - interview`, `topcoder-rejected`, all these statuses will be listed in the Declined list.

**Comment by SathyaJayabal** [comment]
verified that candidates with the following statuses are displayed under the rejected tab
rejected - other, client rejected - screening, client rejected - interview

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 26 25 PM" src="https://user-images.githubusercontent.com/58783823/116900333-42a1d880-ac56-11eb-8a50-45040d7f8567.png">
