### ISSUE TITLE
[$15] Error message/Constraint should be added in UI when the project members tries to schedule an interview

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#173]
Description:

At present, No Error message/Constraint is added in UI when a member of the project tries to schedule an interview. 

If the project member clicks Begin scheduling button, no action occurs.

<img width="959" alt="member_schedulean interview" src="https://user-images.githubusercontent.com/55895538/116517798-6984a580-a90a-11eb-8216-9eab90eb1c62.png">

**Comment by SathyaJayabal** [comment]
@nikolay83, @sandhiyakavi ,@urwithat Only Booking Manager/Admin should be bale to see the schedule interview button.

**Comment by wdprice** [comment]
@SathyaJayabal This is not true - customers would be the ones hitting this button. Basically anyone with access to the project should be able to.

**Comment by SathyaJayabal** [comment]
@wdprice , yes you are right. We should check the permissions on the backend.

**Comment by nikolay83** [comment]
Final requirement: regular member (a customer) must be able to schedule an interview.

**Comment by cagdas001** [comment]
> Final requirement: regular member (a customer) must be able to schedule an interview.

Only book (i.e. requestInterview)? I guess the update endpoint will remain with the same permissions?

And, by regular member, you mean any member with a valid token right? or do customers have a specific role?

**Comment by nikolay83** [comment]
Actually everything developed within the Interview Scheduler must be allowed.
Yes, Any member with the token.

**Comment by wdprice** [comment]
Any member who is associated with the parent project, plus bookingAdmin and Topcoder Admin can click "Schedule Interview", "Schedule Another Interview", and "Begin Scheduling"

**Comment by cagdas001** [comment]
> Any member who is associated with the parent project, plus bookingAdmin and Topcoder Admin can click "Schedule Interview", "Schedule Another Interview", and "Begin Scheduling"

What I understand from this, customers have nothing to do with the updateInterview endpoint. They'll only schedule/create interviews. And, AFAIK, the updateInterview will already be called by Zapier, it's a part of the automated flow.

So, we'll require project-level permission to schedule interviews.  Does this also apply when viewing the interview details? Technically endpoints will return all the interview details. So, a member, even though he is not one of the attendees, can still see the interview details?

**Comment by nikolay83** [comment]
Customer must definitely be able to view the interview details.
As for Zapier - not necessary.

>So, a member, even though he is not one of the attendees, can still see the interview details?
Yes, that'll be possible via API.
@urwithat @wdprice do we want to fix it in future authorizing member by a project they belong to?

**Comment by wdprice** [comment]
Doesn't the jobCandidates API already do that? Or perhaps that feature is
at the /taas-team level? Might be worth checking with Maxceem.

**Comment by cagdas001** [comment]
To add more context,

The `interviews` are being returned as an included (i.e. nested) field in both `jobCandidates` (`GET /jobCandidates`, `GET /jobCandidates/:id`) and `teamJob` (`GET /taas-teams/:id/jobs/:jobId` - the UI currently gets position data from this) endpoints. These two endpoints have already their own project based access level, like you said.

So, for "viewing" interview details, if we'll apply the same project-based access level,  we need to update only `requestInterview` and `updateInterview` endpoints. The other 2 mentioned endpoints already have this logic in place.

For now, I'm updating the `requestInterview` and `updateInterview` for the project-based access level - so can I can finalize fixes & push them. We can change it later if it would be necessary.

**Comment by wdprice** [comment]
This sounds correct to me.

**Comment by cagdas001** [comment]
Permissions fixed. Also, it will show a toast notification in case of any error.

**Comment by sandhiyakavi** [comment]
@cagdas001 Still member of the project are not able to schedule interview. Getting error "Not found"

<img width="957" alt="error_1" src="https://user-images.githubusercontent.com/55895538/116653052-626c9e80-a9c1-11eb-8052-cac135335c27.png">

<img width="686" alt="projectaccess" src="https://user-images.githubusercontent.com/55895538/116653040-5da7ea80-a9c1-11eb-920b-833fd8c259b5.png">

**Comment by nikolay83** [comment]
@cagdas001 please have a look. It failed in Dev.

**Comment by cagdas001** [comment]
https://github.com/topcoder-platform/taas-apis/pull/230 should resolve this issue

**Comment by SathyaJayabal** [comment]
verified. normal user is able to schedule interview.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 27 32 PM" src="https://user-images.githubusercontent.com/58783823/116900501-6ebd5980-ac56-11eb-92b4-21c6d46f7871.png">
<img width="1440" alt="Screenshot 2021-05-03 at 9 27 38 PM" src="https://user-images.githubusercontent.com/58783823/116900527-741aa400-ac56-11eb-8e14-03c367221e28.png">
