### ISSUE TITLE
Able to schedule more than three interviews for a Job candidate

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#174]
Description:

User is able to schedule more than three interviews for a Job candidate. Warning pop up "You've reached the cap of 3 interviews with this candidate. Now please make your decision to Select and Decline them"  not displayed. Popup for interview scheduling still appear.

![image](https://user-images.githubusercontent.com/55895538/116523917-bae46300-a911-11eb-8a9a-eeb8b118eb21.png)
![image](https://user-images.githubusercontent.com/55895538/116523954-c59ef800-a911-11eb-91c1-ad395a9cbde1.png)

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , thats out fo scope for now. But lets keep this open to track.

**Comment by SathyaJayabal** [comment]
Verified. An error message is displayed when a user tries to schedule more than 3 rounds.

<img width="1440" alt="Screenshot 2021-05-01 at 12 59 24 PM" src="https://user-images.githubusercontent.com/58783823/116774983-db313080-aa7d-11eb-9761-8e8453174d5c.png"> 

<img width="1440" alt="Screenshot 2021-05-01 at 12 58 42 PM" src="https://user-images.githubusercontent.com/58783823/116774977-d3718c00-aa7d-11eb-9def-1fd979fd2f06.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 32 17 PM" src="https://user-images.githubusercontent.com/58783823/116901040-133f9b80-ac57-11eb-8dc8-c1030fd55e93.png">
