### ISSUE TITLE
Email not sent for following interviews scheduled if same attendees mentioned.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#175]
Description:
Email not sent for following interviews scheduled if same attendees mentioned.

Steps to Reproduce:
1. Add an email address as attendee for first interview scheduled.
2.  Add the same email address as attendee for second interview scheduled.

Actual result:
Email received for the interview round 1 and the Email for interview round 2 not received.

Expected result:
Email should be received for each round even if the attendees are same.

![image](https://user-images.githubusercontent.com/55895538/116535028-3ea44c80-a91e-11eb-9a8c-59bac980a36c.png)

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , can you reverify this one please?

**Comment by sandhiyakavi** [comment]
Email is now sent for following interviews scheduled if same attendees mentioned. Closing this issue since not able to reproduce now.

![image](https://user-images.githubusercontent.com/55895538/116663088-98b21a00-a9d1-11eb-9415-f2aac326d0c4.png)
