### ISSUE TITLE
Email is not sent to the customer and candidate email ids

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#176]
When an interview is scheduled, the emails are not sent to the customer and candidate email addresses. The email is sent only to the manually entered attendees email id.

**Comment by nikolay83** [comment]
because they are mocked. Must be fixed by today's update we are waiting for.

**Comment by SathyaJayabal** [comment]
verified. email sent to customer and candidate email addresses

**Comment by SathyaJayabal** [comment]
verified on prod. email sent to customer and candidate emails.
