### ISSUE TITLE
[$70] Editing a JOB is not syncing to RCRM

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#179]
1. Create a job in taas
2. Check that the job appears in RCRM
3. edit the job name/description in taas
4. Check job details on RCRM

Actual: The updates made on the Taas app are not reflected in RCRM. Further more, any updates to the job candidates statues in either RCRM or Taas are not synced.

Expected:The updates made on the Taas app must be reflected in RCRM. Further more, there should not be any effect on the Job Candidate status syncs

Note: This issue is present only on DEV. 

@nkumar-topcoder confirmed that this is good on PROD

**Comment by nkumar-topcoder** [comment]
@nikolay83 
there's is a mixup of external id here.
https://github.com/topcoder-platform/taas-app/blob/dev/src/routes/JobForm/index.jsx#L67.

Please note - that **externalID** are there only for 2 tables - **job.externalid and jobcandidate.externalid** and Only used for syncing to recruit crm. 

also inform the submitter to check for all the places where **externalid** is set to userid. externalid’s are only for RCRM.

**Comment by nikolay83** [comment]
@cagdas001 instead id external ID please use her UUID from v5/users

**Comment by nkumar-topcoder** [comment]
@cagdas001 also check if you made any other `externalid` assigned to `userid` compare with prod and remove if it.

**Comment by SathyaJayabal** [comment]
Verified.

**Comment by SathyaJayabal** [comment]
verified on prod.
