### ISSUE TITLE
Hide Overall Team Rating on My Teams page

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#18]
Overall rating UI element should not be displayed on the My Teams page during the version 1.0 release

![image](https://user-images.githubusercontent.com/6014049/101373163-a62c0380-387a-11eb-995c-a411f0dd831f.png)

**Comment by maxceem** [comment]
Done via 143c312e88367a7a85c04369b9703602b1c599ef

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-12-21 at 4 25 13 PM" src="https://user-images.githubusercontent.com/58783823/102769789-27ba8000-43a9-11eb-8dfc-a71b01afaf1c.png">
<img width="1440" alt="Screenshot 2020-12-21 at 4 25 23 PM" src="https://user-images.githubusercontent.com/58783823/102769809-2c7f3400-43a9-11eb-8b48-906aa36ca4cc.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 10 18 PM" src="https://user-images.githubusercontent.com/58783823/106147838-58f35080-619e-11eb-995f-034ed289f5e6.png">
