### ISSUE TITLE
Update Video on the Schedule Interview confirmation popup

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#180]
Update Video on the Schedule Interview confirmation popup
<img width="1440" alt="Screenshot 2021-04-30 at 4 32 23 PM" src="https://user-images.githubusercontent.com/58783823/116686618-b0899e00-a9d1-11eb-8955-09b1d92f771d.png">

**Comment by SathyaJayabal** [comment]
@nikolay83 , we need to remove this video before the release
https://topcoder.slack.com/archives/C01RTKEQR63/p1619792551244800

cc @urwithat

**Comment by nikolay83** [comment]
Fixed with https://github.com/topcoder-platform/taas-app/pull/187

**Comment by SathyaJayabal** [comment]
Verified , video is removed for now. Will need to hotfix when video is available.
<img width="1440" alt="Screenshot 2021-05-01 at 12 58 18 PM" src="https://user-images.githubusercontent.com/58783823/116774876-344c9480-aa7d-11eb-98d3-366ef44956b9.png">

**Comment by SathyaJayabal** [comment]
verified on prod. video removed for now
<img width="1440" alt="Screenshot 2021-05-03 at 9 27 38 PM" src="https://user-images.githubusercontent.com/58783823/116901417-847f4e80-ac57-11eb-9862-651b81a1397b.png">
