### ISSUE TITLE
Nice to have: Display Interview time along with interview date 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#181]
Display Interview time along with interview date in the Last scheduled interview status and in  the previous interviews popup. At present only the date is displayed.

<img width="658" alt="Screenshot 2021-04-30 at 4 37 53 PM" src="https://user-images.githubusercontent.com/58783823/116687234-779df900-a9d2-11eb-92b5-1e877061d5b0.png">. 

<img width="1113" alt="Screenshot 2021-04-30 at 4 37 14 PM" src="https://user-images.githubusercontent.com/58783823/116687224-740a7200-a9d2-11eb-86a8-53d10f89b973.png">

cc @wdprice

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Time displaying correctly
![image](https://user-images.githubusercontent.com/55895538/118467482-c7a0ed80-b73e-11eb-83e1-95cd176615ca.png)

![image](https://user-images.githubusercontent.com/55895538/118467244-9b856c80-b73e-11eb-9d66-00960ef01972.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="640" alt="Screenshot 2021-05-17 at 4 30 39 PM" src="https://user-images.githubusercontent.com/58783823/118478423-7d634080-b72d-11eb-94b3-e001e2b5896f.png">
<img width="1100" alt="Screenshot 2021-05-17 at 4 31 08 PM" src="https://user-images.githubusercontent.com/58783823/118478430-7f2d0400-b72d-11eb-96f2-4e32dd48cfab.png">
