### ISSUE TITLE
 Interviewstatus  not updated to "completed" eventhough the interview date scheduled is over.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#182]
Description:

 Interviewstatus  not updated to "completed" for earlier round even though the interview date scheduled is over. But status changed to "completed" for latter round.
In the below example, Status is still 'scheduled' for round 1 but "completed" for round 7

![image](https://user-images.githubusercontent.com/55895538/116648822-f5550b00-a9b8-11eb-99a1-b4a82d58f828.png)
![image](https://user-images.githubusercontent.com/55895538/116654562-5c2bf180-a9c4-11eb-924f-cbd92b313dc1.png)

![image](https://user-images.githubusercontent.com/55895538/116654626-7f56a100-a9c4-11eb-8a1e-fe9bad3753aa.png)

**Comment by SathyaJayabal** [comment]
@nikolay83 , I think this works, let me confirm with one more example and close this issue later today.

**Comment by SathyaJayabal** [comment]
Interview status is updated to completed. verified on prod
<img width="1096" alt="Screenshot 2021-05-18 at 9 23 48 AM" src="https://user-images.githubusercontent.com/58783823/118587822-da590800-b7ba-11eb-9307-5ec4db17633a.png">
