### ISSUE TITLE
Interview rescheduled date is not getting updated

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#183]
Description:

Interview rescheduled date is not getting updated in both api and UI side.

Date rescheduled from 30 April to 3rd May

![image](https://user-images.githubusercontent.com/55895538/116691035-3c60f180-a9f5-11eb-91de-d3b059cd0033.png)

![image](https://user-images.githubusercontent.com/55895538/116690956-20f5e680-a9f5-11eb-94a3-e1c5a366c725.png)

![image](https://user-images.githubusercontent.com/55895538/116691146-5e5a7400-a9f5-11eb-9ad0-66f3fda3b260.png)
![image](https://user-images.githubusercontent.com/55895538/116691191-6f0aea00-a9f5-11eb-9fed-0cf28fee0fe5.png)

**Comment by nikolay83** [comment]
And what's in Zapier history?

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1080" alt="Screenshot 2021-05-04 at 1 10 22 PM" src="https://user-images.githubusercontent.com/58783823/116973458-34959b80-acda-11eb-8543-8689aecb938a.png">
verified on dev
<img width="1094" alt="Screenshot 2021-05-04 at 1 13 41 PM" src="https://user-images.githubusercontent.com/58783823/116974063-2005d300-acdb-11eb-8bc0-cc2f5c8bed58.png">
<img width="1086" alt="Screenshot 2021-05-04 at 1 17 24 PM" src="https://user-images.githubusercontent.com/58783823/116974068-21cf9680-acdb-11eb-87c1-62c91c823d9b.png">

**Comment by SathyaJayabal** [comment]
@urwithat , we will also have to support displaying the status when the meeting is cancelled.

**Comment by SathyaJayabal** [comment]
cancellation is tracked  here #249
