### ISSUE TITLE
Rb gets duplicated when we all positions in the job are filled

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#189]
1. Create a project and job and  assign resources to the job.
example: 
https://platform.topcoder-dev.com/taas/myteams/17298
2. assign resources for all positions

actual: A duplicate Rb is created of the last resource assigned
expected: duplicate RB must not be created.

**Comment by maxceem** [comment]
@SathyaJayabal I suspect that this records was created as a copy of the second one, not the third one.

1. Did you create the job using UI or direct API calls?
2. I can see 4 RBs assigned to this job. How each of these resources was created? Did you use direct API calls, or did you created them in RCRM?

**Comment by SathyaJayabal** [comment]
Everything through UI @maxceem 

1. create project and job from connect
2. assign candidates from RCRM
3. edit RB from taas app UI

And I am sure the duplicate was created when the other user was edited, which s very weird, but i double checked.

**Comment by SathyaJayabal** [comment]
@maxceem , this can be reproduced please try with a fresh project

**Comment by maxceem** [comment]
Fixed by https://github.com/topcoder-platform/taas-apis/commit/6f139acc2dc5225596183901f50b1f577d9ebf3b

**Comment by SathyaJayabal** [comment]
verified on dev.

**Comment by SathyaJayabal** [comment]
verified on prod.
