### ISSUE TITLE
Report an Issue Interface

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#19]
Implement a modal (or equivalent) to appear when the user clicks on the "Report an Issue" button on the MyTeams page. Same Modal should be used when a user clicks the "Report an Issue" in the actions menu on a particular resource.

Model should include a Subject Line(non-editable) and Body labeled as "Describe your issue" (editable).

Subject Line (Team level): Issue Report - TEAM NAME
Subject Line (resourceBooking level): Issue Report - TEAM NAME - RESOURCE HANDLE

Body should be a text area.

On submission of the form, send an email to `customersuccess@topcoder.com` with the Subject Line defined above and the body as defined by the user. Append a link to the corresponding team detail page at the end of the email body.

**Comment by wdprice** [comment]
Our goal will be to integrate w/ SFDC to create an escalation record in place of sending an email to customer success. More details to come as we solution w/ the SFDC team.

**Comment by maxceem** [comment]
Sum up:
- User can send a report for the **whole team** by clicking "Report Issue" on the team list page ([screenshot](https://monosnap.com/file/SJquSbwiIWBTcz7iyNXntyfJK116lm)) or on the Team Detail page ([screenshot](https://monosnap.com/file/vhx178nQKZmy4ldH3O07E4tqey2K33))
- Or we can send a report for a particular resource ([screenshot](https://monosnap.com/file/elhQxZLGG5MDRrrPxAZ5vuZWpdJIBN))
- When we click the "Report Issue" button in any of these places, we have to show the popup https://marvelapp.com/prototype/921gg0f/screen/75360462/handoff
   - If we report team, then title should be: `Issue Report - <TEAM NAME>`. If we report resource, then the title should be `Issue Report - <TEAM NAME> - <RESOURCE HANDLE>`
- User should be able to enter any text inside the report and click "Submit" (disabled if no text).
- When the user clicks "Submit" we should disable buttons, show the loading indicator like during member deleting (see [video](https://monosnap.com/file/00zo4dLWlb8fmmBz3WNgQkFkXrUpRa)) and send a request to the API endpoint:
   - if the request was successful, then close popup and show green toastr with "Report submitted successfully"
   - if the request failed, then show red toast **with error from the server**, hide the loading indicator, enable buttons and show teaxtarea keeping all the text of the user, so user can try to submit report again.
- Use API endpoint `POST /taas-teams/email`:
    - body for team report:
       ```js
        {
          template: "team-issue-report"
          data: {
            projectName: <TEAM NAME>,
            projected: <TEAM ID>,
            reportText: <REPORT TEXT FROM THE TEXTARE>   
          }
       }
       ```
    - body for team report:
       ```js
        {
          template: "member-issue-report"
          data: {
            projectName: <TEAM NAME>,
            projected: <TEAM ID>,
            reportText: <REPORT TEXT FROM THE TEXTARE>,
            userHandle: <HANDLE OF THE REPORTED USER>,
          }
       }
       ```
-📍Note, that we would like to show this report popup on 2 pages: Team List and Team Details. We would like to be able to open this popup by a single method, like 
    ```js
     import { showReportPopup } from 'components/ReportPopup'

     // somewhere in the code
     onClick={() => showReportPopup(<TEAM NAME>, <TEAM ID>, <HANDLE>)}
    ```
    - this is so we don't have to repeat the whole code of the popup on each page again and again.

**Comment by sandhiyakavi** [comment]
@maxceem The email send to customersuccess@topcoder-dev.com doesn't have body section sent

![image (20)](https://user-images.githubusercontent.com/55895538/108811807-47606580-75f1-11eb-8ae1-28bcddd1e4cb.png)

Other than that ,everything is working fine

Getting success message for Report send from Team listings, Team details page and Report send for particular resource.


https://user-images.githubusercontent.com/55895538/108812205-0f0d5700-75f2-11eb-8042-e751145daba5.mp4

Getting error message in case of failure.

<img width="776" alt="report failed_taas app" src="https://user-images.githubusercontent.com/55895538/108812234-20eefa00-75f2-11eb-90c1-2ee945aa2191.png">

**Comment by maxceem** [comment]
@sandhiyakavi this is ready for QA now.

We've fixed the email body so now it's shown:

![image](https://user-images.githubusercontent.com/146016/108820977-a3ad9000-75c5-11eb-81a4-30f7429cee4a.png)

I’ve tried to improve formatting, but it appears hard to do without changing the email template. So I guess we have to release with such formatting for now and we would have to improve the email template after.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. It is working as expected.

![image](https://user-images.githubusercontent.com/55895538/108824266-e0e54280-7604-11eb-8604-950d35094d50.png)
<img width="776" alt="report failed_taas app" src="https://user-images.githubusercontent.com/55895538/108824330-ecd10480-7604-11eb-92bc-254eb783316a.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.


https://user-images.githubusercontent.com/55895538/109296482-b3520080-7873-11eb-9446-e469509cdead.mp4

Failure message.
![image](https://user-images.githubusercontent.com/55895538/109296567-dc729100-7873-11eb-884a-87e16cbbed82.png)

Separate issue logged for Email template https://github.com/topcoder-platform/taas-app/issues/121
