### ISSUE TITLE
[Content] "availability" is expected on the "Schedule an Interview" modal

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#192]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SCHEDULE ANOTHER INTERVIEW

4. observe

### Expected Result ###

"availability" is expected.

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###

![1](https://user-images.githubusercontent.com/4590317/116798890-a4fbbb80-ab26-11eb-8f78-5eb918e160b6.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by sandhiyakavi** [comment]
@nikolay83 @urwithat Still the spelling for 'availability' is displayed wrong.

![image](https://user-images.githubusercontent.com/55895538/118081745-f180aa00-b3f6-11eb-8bac-836bfffd0ea3.png)

**Comment by sandhiyakavi** [comment]
@nikolay83 @urwithat sorry tried while deploying.Displaying correctly.Closing the issue

![image](https://user-images.githubusercontent.com/55895538/118081914-3b699000-b3f7-11eb-8c16-097db40e4fc5.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/118444747-7ede3a00-b728-11eb-8b12-1638ee1b6803.png)
