### ISSUE TITLE
[Functional] email validation is incorrect on the "SCHEDULE AN INTERVIEW" modal

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#193]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SCHEDULE ANOTHER INTERVIEW

4. click "Add more" to add a row

5. input "test@test....." for the email address

6. observe

### Expected Result ###

The "BEGIN SCHEDULING" button should be disabled if the Email Address is invalid.

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###

![3](https://user-images.githubusercontent.com/4590317/116799113-b219aa00-ab28-11eb-89bb-2cdf7f5ad928.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
That's exactly the behavior, I can't reproduce your case neither in Firefox nor Chrome.

**Comment by winterflame** [comment]
Hi @nikolay83 ,

I can attach a video if you could provide some test data. Right now, there is no data for the "INTERVIEWS" tab.

When we input "test" in the textbox, the "BEGIN SCHEDULING" button is disabled, right? If this is the correct behavior, then when the email is a valid one (e.g. **test@test.....**), this button should be disabled.

Please recheck this, thanks!
