### ISSUE TITLE
[Content] "1 Attendees" should be "1 Attendee"

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#194]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SCHEDULE ANOTHER INTERVIEW

4. click "BEGIN SCHEDULING" button, confirm the action then close the modal

5. click ACTIONS > VIEW PREVIOUS INTERVIEWS

6. observe

### Expected Result ###
"1 Attendees" should be "1 Attendee"

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###
![4](https://user-images.githubusercontent.com/4590317/116799226-05d8c300-ab2a-11eb-8201-417dbc2b9099.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
I suggest "1 Attendee(s)" to keep it simple.

**Comment by nikolay83** [comment]
There is never less than 2 attendees at the interview :)
