### ISSUE TITLE
[Content] "Additionally" should be "additionally"

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#196]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SCHEDULE ANOTHER INTERVIEW

4. observe

### Expected Result ###
"Additionally" should be "additionally", as there is a comma to its left side.

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###
![6](https://user-images.githubusercontent.com/4590317/116799460-1f7b0a00-ab2c-11eb-9de1-e3902ab58d90.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/118082213-ba5ec880-b3f7-11eb-9cc3-21da7f6ffe52.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.

<img width="960" alt="additionally" src="https://user-images.githubusercontent.com/55895538/118448584-1fcef400-b72d-11eb-842c-958c5b25ff60.png">
