### ISSUE TITLE
[UI] dropdown width should be smaller

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#198]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. click to see options in the dropdown

4. observe

### Expected Result ###
The dropdown width should be smaller as the options are not that long, there is a lot of spaces in it.

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###

![7](https://user-images.githubusercontent.com/4590317/116799748-a381c180-ab2d-11eb-824a-ab8ca374a3f1.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by SathyaJayabal** [comment]
trivial
