### ISSUE TITLE
[Content] "No Selected" should be "No Candidates Selected" for consistency

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#199]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. click "SELECTED" tab (No data)

4. click "TO REVIEW" tab (No data) to compare with

5. observe

### Expected Result ###
"No Selected" should be "No Candidates Selected" for consistency.

### Actual Result ###
See the screenshots.

### Screenshot and/or screencast ###
![8](https://user-images.githubusercontent.com/4590317/116799858-94e7da00-ab2e-11eb-98b6-568e37b7e9e1.jpg)

![8 1](https://user-images.githubusercontent.com/4590317/116799865-a0d39c00-ab2e-11eb-8d37-4a1f21ffd0b0.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by SathyaJayabal** [comment]
@nikolay83  need to update text to "No Selected Candidates"

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Displaying correctly

![image](https://user-images.githubusercontent.com/55895538/118459627-e3a09100-b736-11eb-9dfd-0a5d64edbeb6.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1106" alt="Screenshot 2021-05-17 at 4 13 35 PM" src="https://user-images.githubusercontent.com/58783823/118476403-104eab80-b72b-11eb-86aa-ff88905d5803.png">
<img width="1134" alt="Screenshot 2021-05-17 at 4 13 49 PM" src="https://user-images.githubusercontent.com/58783823/118476407-12b10580-b72b-11eb-8cc7-ad442a8ae7b1.png">
<img width="1101" alt="Screenshot 2021-05-17 at 4 14 06 PM" src="https://user-images.githubusercontent.com/58783823/118476408-13499c00-b72b-11eb-8d41-4884a0ce4faf.png">
<img width="1116" alt="Screenshot 2021-05-17 at 4 14 12 PM" src="https://user-images.githubusercontent.com/58783823/118476410-147ac900-b72b-11eb-89fb-56f9d28f8eed.png">
