### ISSUE TITLE
Remove unused navigation options from Nav Sidebar

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#20]
Only navigation option in the v1.0 sidebar should be "My Teams"

Remove the options highlighted in the image
![image](https://user-images.githubusercontent.com/6014049/101504643-73007780-3941-11eb-95ff-5c8d8b5867fb.png)

**Comment by maxceem** [comment]
Also:

![image](https://user-images.githubusercontent.com/146016/101532099-b6d49a80-399c-11eb-9e01-c595394ccb33.png)

and:

![image](https://user-images.githubusercontent.com/146016/101532159-cce25b00-399c-11eb-9ac7-2e263776daac.png)

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/8

**Comment by sandhiyakavi** [comment]
Verified. Working as expected.


https://user-images.githubusercontent.com/55895538/102773875-4894cc80-43cd-11eb-8bbd-95bf1a0602e0.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 25 19 PM" src="https://user-images.githubusercontent.com/58783823/106148042-9657de00-619e-11eb-8245-3fe33a6f9e99.png">
