### ISSUE TITLE
[UI] "SHOW MORE" button should be hidden instead of disabled if no data is available

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#200]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 4" row

3. click to see each tab that has no data

4. observe

### Expected Result ###
The "SHOW MORE" button should be hidden instead of disabled if no data is available.

### Actual Result ###
See the screenshot, it is shown as disabled.

### Screenshot and/or screencast ###
![9](https://user-images.githubusercontent.com/4590317/116800016-d2009c00-ab2f-11eb-8991-153c3e3a6291.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by SathyaJayabal** [comment]
as per design
