### ISSUE TITLE
[UI] Placeholder text not aligned to middle in Firefox

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/taas-app#201]
## Steps
1. Go to https://platform.topcoder-dev.com/taas/myteams/17258  
2. Click Create Position  
3. Observe the placeholder text for Job Name, Start Date, and Duration  

## Expected Result
Placeholder text should be aligned to middle, just like in Chrome and Edge

## Actual Result
Placeholder text is aligned to top  

## Screenshot/Screencast
![not middle](https://user-images.githubusercontent.com/1199534/116800020-e47ad580-ab2f-11eb-8ffb-4eba1cde2512.png)

## Environment
Windows 10 Pro Version 1909 Build 18363.900, Firefox 88.0 (64-bit)

**Comment by SathyaJayabal** [comment]
trivial
