### ISSUE TITLE
[Functional] should not allow adding duplicate emails on the "Schedule an interview" modal

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#202]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SCHEDULE ANOTHER INTERVIEW

4. click "Add more" to add a row

5. enter "test@test.com" for the email address

6. repeat step 4 and 5 twice

7. observe

### Expected Result ###

Should not allow adding duplicate emails.

### Actual Result ###
See the screenshot, no any validation and the "BEGIN SCHEDULING" button is enabled.

### Screenshot and/or screencast ###

![10](https://user-images.githubusercontent.com/4590317/116800137-e1ccb000-ab30-11eb-9742-0db146a0d490.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
there is no such requirement
