### ISSUE TITLE
[UI] Up/down buttons too small in Firefox

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/taas-app#203]
## Steps
1. Go to https://platform.topcoder-dev.com/taas/myteams/17258  
2. Click Create Position  
3. Observe the up/down buttons for Number of Openings and Duration  

## Expected Result
The buttons should be big enough to click  

## Actual Result
The buttons are small and are hard to click  

## Screenshot/Screencast
https://user-images.githubusercontent.com/1199534/116800131-d5485780-ab30-11eb-9009-a307b75eb9b3.mp4

## Environment
Windows 10 Pro Version 1909 Build 18363.900, Firefox 88.0 (64-bit)

**Comment by SathyaJayabal** [comment]
trivial
