### ISSUE TITLE
[Content] Wording for candidate, applicant and member should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#204]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on any row, click ACTIONS > SELECT CANDIDATE

4. observe the content

### Expected Result ###

Wording for candidate, applicant and member should be consistent.

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###
![11](https://user-images.githubusercontent.com/4590317/116800213-9b2b8580-ab31-11eb-94f7-2571d7fd9161.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Wording is consistent

![image](https://user-images.githubusercontent.com/55895538/118460539-c3bd9d00-b737-11eb-8243-3b1422ef8802.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="645" alt="Screenshot 2021-05-17 at 4 16 19 PM" src="https://user-images.githubusercontent.com/58783823/118476577-4ee46600-b72b-11eb-9f5e-7ef83e10f24c.png">
