### ISSUE TITLE
[Common][UI] Confirm/Close/Cancel buttons on the modal should be aligned to center

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#205]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. play with the available feature and observe the modals

### Expected Result ###

Buttons should be aligned to center.

### Actual Result ###
See the screenshots.

### Screenshot and/or screencast ###
![12](https://user-images.githubusercontent.com/4590317/116800259-273dad00-ab32-11eb-9d61-99607dc40629.jpg)

![12 1](https://user-images.githubusercontent.com/4590317/116800264-2e64bb00-ab32-11eb-9b7d-4f2662339e5e.jpg)

![12 2](https://user-images.githubusercontent.com/4590317/116800273-3f153100-ab32-11eb-909d-38711ef432cb.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
Good suggestion, but not a bug
