### ISSUE TITLE
[UI] "CANCEL" button should be "CLOSE"

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#206]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. on the first row, click "ACTIONS" > "SCHEDULE ANOTHER INTERVIEW", confirm the action

4. repeat the step 3 for 3 times

5. observe the error modal

### Expected Result ###

"CANCEL" button should be "CLOSE".

### Actual Result ###
See the screenshot.

### Screenshot and/or screencast ###

![13](https://user-images.githubusercontent.com/4590317/116800367-0a55a980-ab33-11eb-9b2f-2a50069a202b.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. 

![image](https://user-images.githubusercontent.com/55895538/118461058-3a5a9a80-b738-11eb-812d-e5cb16e0d816.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="646" alt="Screenshot 2021-05-17 at 4 17 58 PM" src="https://user-images.githubusercontent.com/58783823/118476786-979c1f00-b72b-11eb-95df-008bf9da92cb.png">
