### ISSUE TITLE
[Common][Safari][UI] user handle has a default blue triangle around it on the modals

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#207]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. click ACTIONS > SELECT CANDIDATE or DECLINE CANDIDATE or VIEW PREVIOUS INTERVIEWS (if any)

4. observe the user handle

### Expected Result ###
Should have no UI issues.

### Actual Result ###
See the screenshots.

### Screenshot and/or screencast ###
![14](https://user-images.githubusercontent.com/4590317/116800492-20179e80-ab34-11eb-93b5-5f1bab1e0cde.jpg)

![14 1](https://user-images.githubusercontent.com/4590317/116800495-2efe5100-ab34-11eb-8211-36e726c46b57.jpg)

![14 2](https://user-images.githubusercontent.com/4590317/116800501-40dff400-ab34-11eb-84eb-4c0cde3dfccf.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Safari Version 14.1 (15611.1.21.161.5, 15611)*

**Comment by SathyaJayabal** [comment]
trivial
