### ISSUE TITLE
[functional] 'Resource Type' Input label not attached on page load to the input field.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#208]
### Description:
'Resource Type' Input label not attached on page load to the input field

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. click on the 'Create Position' button.
3. click on the input field **below** ' Start Date'
4. Observe for any label to the field( there is no label attached to it when initially page loads) , then select any one option from the drop-down list and then again observe for the label to appear above the field.
OR
3. Follow the steps as per the video attached

---

### Video / Snap:

https://user-images.githubusercontent.com/67191980/116800493-2f402180-ab1f-11eb-8f7c-d03259839111.mp4

---

### Actual result:

the label is missing on page load, and appears after the dropdown option is selected.

---

### Expected result:

As the user see the fields for filling up the form, the label to all field should be clearly displayed on loading the page

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by swap12875** [comment]
@nikolay83, if possible, can you please share its original Bug Id (if it is duplicate one), or The Input field label is not necessary for this input field?

**Comment by nikolay83** [comment]
it's not a duplicate but it's not Scheduler related
