### ISSUE TITLE
[UI] Job titles retain black color after clicking once and page refreshing

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#209]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on any of the projects visible
4. Click Back and Refresh page
5. Currently, the project title retains a black color as opposed to blue it had before clicking

## Screenshot
https://user-images.githubusercontent.com/51795389/116800774-b68e9480-ab21-11eb-813f-2d110de95a33.mp4

## Actual Result
Job titles retain black color after clicking once and page refreshing

## Expected Result
Job titles should not retain in black color state

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by SathyaJayabal** [comment]
trivial

**Comment by hyperblaster1** [comment]
@nikolay83 Similar UI issues have been accepted for others. Can you please reconsider this ? It is valid and it's not exactly a feature is it ?

**Comment by nikolay83** [comment]
It's not in scope of this Bug Hunt, first of all. Also it's not clear what do you mean by "Similar UI issues... for others".
