### ISSUE TITLE
Show user photo from TaaS API instead of using V3 API

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#21]
Because we use user ids from users V5 API, we cannot use V3 API for getting users photos, as ids are different.

- So we have to use `photo_url` returned by TaaS API
- Remove code to load Photo URL from V3 API

**Comment by maxceem** [comment]
Done via

Teams List

![image](https://user-images.githubusercontent.com/146016/101536449-afb08b00-39a2-11eb-996b-be522225b274.png)

Team Details

![image](https://user-images.githubusercontent.com/146016/101536572-dcfd3900-39a2-11eb-9a7c-7f98c8066c05.png)

Position

![image](https://user-images.githubusercontent.com/146016/101536838-37969500-39a3-11eb-94bf-df04325c2df8.png)

**Comment by SathyaJayabal** [comment]
verified on dev

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 36 07 PM" src="https://user-images.githubusercontent.com/58783823/106149307-1d598600-61a0-11eb-89f5-041713d28dd1.png">
