### ISSUE TITLE
Search My Teams is not working 

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#211]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. In Filter by team name, enter a part of any of the Team names - such as 'swap' or 'Intervie' 
4. Currently, the My Teams search does not work for partial words , if you search for full words such as 'Interview' , it works. If you search for 'Intervie' or any similar partial keyword it is not working

## Screenshot
https://user-images.githubusercontent.com/51795389/116801143-98766380-ab24-11eb-97d2-3332aa9d0fde.mp4

## Actual Result
Search My Teams is not working 

## Expected Result
Search in My Teams should work when searching for all keywords,partial or full

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by SathyaJayabal** [comment]
as per design
