### ISSUE TITLE
[Functional] Multiple client logins is not logging user out from other sessions

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#212]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Open a different browser of any choice
4. Login on second browser with credentials from Step 2 
5. Click Refresh in both browser
5. Currently, the application does not log user out on logging in on another client

## Screenshot
https://user-images.githubusercontent.com/51795389/116801290-07a08780-ab26-11eb-9931-2e3df57b73af.mp4

## Actual Result
Multiple client logins is not logging user out from other sessions

## Expected Result
Should log users out of other sessions on login

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit) | Firefox Build 88.0 (64-bit)

**Comment by nikolay83** [comment]
why should it? It's expected.
