### ISSUE TITLE
[IE11] Unable to login

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#214]
1. open https://platform.topcoder-dev.com/taas/myteams/17258, observe

2. open https://www.topcoder-dev.com, click Log In, wait and observe

### Expected Result ###
Should be able to open the application and enter credentials to login.

### Actual Result ###
See the screencast.

### Screenshots & screencast ###

https://user-images.githubusercontent.com/4590317/116801393-2ad63180-ab3c-11eb-9b59-88de19dbd9bf.mp4

Error after step 1:
![error](https://user-images.githubusercontent.com/4590317/116801387-1b56e880-ab3c-11eb-99fb-13d1c4a0dae7.jpg)

Endless waiting after step 2:

![endless](https://user-images.githubusercontent.com/4590317/116801411-58bb7600-ab3c-11eb-931a-addc6fe966bc.jpg)

### Device/OS/Browser Information ###

OS: *Windows 7*

Browser Version: *IE 11.0*
![ie11](https://user-images.githubusercontent.com/4590317/116801378-0a0ddc00-ab3c-11eb-9fb8-812d5b7827c0.jpg)

**Comment by SathyaJayabal** [comment]
We are not supporting IE11.
