### ISSUE TITLE
[Content/UI] Misplaced cross button in skill list

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#215]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on INTERVIEW SCHEDULER TEST PROJECT
4. Click on REVIEW CANDIDATES next to 'Interview Scheduler Test Job 1'
5. Switch to 'Selected' Tab
6. Hover on 'Apache Derby, Appium, Applet, BigQuery, Bootstrap, Chatter, Servlet' text next to tester1234
7. Currently, the required job skill list items have a misplaced cross button. This is not the edit view, cross button is unnecessary

## Screenshot
https://user-images.githubusercontent.com/51795389/116801442-af6a8500-ab27-11eb-9d41-d3608439bd6d.mp4

## Actual Result
Misplaced cross button in skill list

## Expected Result
Cross button should be removed

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
not a bug
