### ISSUE TITLE
[Functional] Cannot login on MS Edge

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#216]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams on MS Edge
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Shows Welcome to Topcoder Micro Frontends

## Screenshot
https://user-images.githubusercontent.com/51795389/116801509-518a6d00-ab28-11eb-8469-dd9ff0f471fb.mp4

## Actual Result
Cannot login on MS Edge

## Expected Result
Should be able to login

## Device|OS
Windows 10 Build 19042.928 | MS Edge Version 90.0.818.51 (Official build) (64-bit)

**Comment by nikolay83** [comment]
duplicates #214

**Comment by hyperblaster1** [comment]
@nikolay83  IE11 and MS Edge are different browsers,right ? Also the #214 has not documented any other browsers just IE11.

**Comment by hyperblaster1** [comment]
@nikolay83 IE11 and MS Edge are different browsers,right ? Also the #214 has not documented any other browsers just IE11. Can you please reconsider ?

**Comment by nikolay83** [comment]
True, so the 1 penalty point for duplication is removed.
MS Edge is not in the PLATFORM REQUIREMENTS however.
