### ISSUE TITLE
[Windows 7][Chrome] Unable to see "SHOW MORE" by default when it is in disabled state

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#217]
1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 2" row

3. click on a tab that has no data, observe

4. double click the "SHOW MORE" button area, observe

### Expected Result ###
By default, it should be visible.

### Actual Result ###
See the screencast and screenshot.

### Screenshot and/or screencast ###
![15](https://user-images.githubusercontent.com/4590317/116801580-e0ee4b00-ab3d-11eb-8db9-79f0999d24fe.jpg)

https://user-images.githubusercontent.com/4590317/116801576-da5fd380-ab3d-11eb-9e2b-374756f6addf.mp4

### Device/OS/Browser Information ###

Device & OS: *Laptop with Windows 7*

Browser Version: *Google Chrome 86.0.4240.75*

**Comment by nikolay83** [comment]
why would you need with the empty list?
