### ISSUE TITLE
[UI] close button has invalid tooltip

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#218]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 4" row

3. click ACTIONS > SCHEDULE ANOTHER INTERVIEW (make sure the user has been scheduled 3 times earlier)

4. hover on the "X" button, observe

### Expected Result ###
Should not have an invalid tooltip.

### Actual Result ###
See the screencast and screenshot.

### Screenshot and/or screencast ###

![close](https://user-images.githubusercontent.com/4590317/116802044-417f8700-ab42-11eb-9646-69e5fc6c9cfa.jpg)

https://user-images.githubusercontent.com/4590317/116802045-45130e00-ab42-11eb-9054-aa906d9a2cd0.mp4

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
@SathyaJayabal is it a bug?

**Comment by SathyaJayabal** [comment]
@nikolay83 , yes

**Comment by SathyaJayabal** [comment]
@nikolay83 ,  can we add this to the rest of the content issues?

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. No tooltip displayed

![image](https://user-images.githubusercontent.com/55895538/118464394-c3270580-b73b-11eb-8e6b-4a472b067a10.png)

**Comment by SathyaJayabal** [comment]
verified on prod. No tooltip displayed,
