### ISSUE TITLE
[UI/Content] Sort By label is not there in Position detail page

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#219]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on 'INTERVIEW SCHEDULER TEST PROJECT'
4. Click on Review Candidates next to 'Interview Scheduler Test Job 1'
5. Currently, the Sort By dropdown's label 'Sort By' is not there , while it is there in the design spec

## Screenshot
https://user-images.githubusercontent.com/51795389/116802340-a7164800-ab2f-11eb-926a-62aafb8e5ad4.mp4

## Actual Result
Sort By label is not there in Position detail page

## Expected Result
Sort By label should be there in Position detail page

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
there is no sorting requirement
