### ISSUE TITLE
ResourceBooking Customer rate not updating in UI

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#22]
The UI is displaying a $0 for customer rate
![image](https://user-images.githubusercontent.com/6014049/101539267-43b33000-396c-11eb-8d42-766bd5f05313.png)

When referenced in the taas-teams API, however, there is a value in customerRate:
![image](https://user-images.githubusercontent.com/6014049/101539336-604f6800-396c-11eb-8a12-48eac03826d7.png)

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/taas-app/commit/9c2d2b533dc2259bcbf8a19173e393f2408fb5fe

**Comment by sandhiyakavi** [comment]
Verified.

![image](https://user-images.githubusercontent.com/55895538/102774124-b5a86200-43cd-11eb-9c5d-f5774ac7b51a.png)

**Comment by SathyaJayabal** [comment]
Customer Rate Out of scope for initial release
