### ISSUE TITLE
[UI] Color of "CONFIRM" buttons are inconsistent

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#221]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click "REVIEW CANDIDATES" on the "Interview Scheduler Test Job 3" row

3. click ACTIONS > SELECT CANDIDATE, observe the "CONFIRM" button

4. click "CANCEL"

5. click ACTIONS > DECLINE CANDIDATE, observe the "CONFIRM" button

### Expected Result ###
Color should be consistent.

### Actual Result ###
See the screenshots.

### Screenshot and/or screencast ###
![16 1](https://user-images.githubusercontent.com/4590317/116802508-02533500-ab46-11eb-8ec9-3f09e92e0465.jpg)

![16 2](https://user-images.githubusercontent.com/4590317/116802513-05e6bc00-ab46-11eb-9380-a09610154e37.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by nikolay83** [comment]
this is intended
