### ISSUE TITLE
[Content/Layout] [UI/UX] 'Required job skill' modal appears on clicking the skill para, which should appear on clicking more button.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#222]
### Description:
'Required job skill' modal appears on clicking the skill para, which should appear on clicking more button.
---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. Go to any project and click,
3. locate 'All team member' section.
4. do a mouse hover/click on skills column.
5. Observe for the  'Required job skill' modal.

OR 
3. Follow the steps as per the video attached

---

### Video / Snap:

https://user-images.githubusercontent.com/67191980/116803160-fe1e1c00-ab33-11eb-8172-d9c6470e40c3.mp4

---

### Actual result:

The modal appears on the mouse hover/click action on the required skill [ara as well as `more` hyperlink in the required skill column 

---

### Expected result:

The modal should only appear on the clicking / hover action on the `more` button.

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
it is intended

**Comment by swap12875** [comment]
@nikolay83 , can you please share, the purpose of giving 'more' text as hyperlink here, if the required skill can be viewed only by hovering to the skill normal text? If hyperlink text 'more' serves no any special requirements, then still it is hyperlink, then this should be a valid issue/bug here, as > text hyperlinked without any specific purpose/requirements< isn't it?

**Comment by nikolay83** [comment]
The purpose is to show the full skill set. With the bigger tapping/clicking area the UX doesn't deteriorate.
