### ISSUE TITLE
[UI/UX] No mouse hover animation attached to buttons on the pages

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#223]
### Description:
No mouse hover animation attached to buttons on the pages

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. Do a mouse hover on the tabs/ buttons displayed on the pages

---

### Video / Snap:

---

### Actual result:

no mouse hover/click animation is attached to the tabs /buttons on the page.

---

### Expected result:

The tabs/ buttons/ close buttons should be provided with the hover animation

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
no such requirement

**Comment by swap12875** [comment]
@nikolay83 as the Submit button on some modal is provided with very less opacity, and not even recognisable by the user, so such buttons and also some other tabs on the page, if provided with hover animations may help to enhance UX/UI prospective. So I reported the issue.

**Comment by nikolay83** [comment]
@SathyaJayabal what do you think?

**Comment by SathyaJayabal** [comment]
No such req for now
