### ISSUE TITLE
[Functional] Sorting criteria implemented on one tab changes sorting criteria for other tabs

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#224]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on 'INTERVIEW SCHEDULER TEST PROJECT'
4. Click on REVIEW CANDIDATES next to 'Interview Scheduler Test Job 3'
5. Currently, the project title retains a black color as opposed to blue it had before clicking
6. Change Sort By Criteria from 'Skill Matched' to 'Handle'
7. Switch to 'SELECTED' tab
8. Currently, sorting criteria change implemented on one tab changes sorting criteria for other tabs

## Screenshot
https://user-images.githubusercontent.com/51795389/116803449-67eaf580-ab35-11eb-9f52-772f93e2b98d.mp4

## Actual Result
Sorting criteria implemented on one tab changes sorting criteria for other tabs

## Expected Result
Sorting criteria one page should not change other page's sorting criteria

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
not a bug
