### ISSUE TITLE
Edit Job Details button is not there

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#225]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on 'INTERVIEW SCHEDULER TEST PROJECT' project
4. Click on'123' position
5. Currently, the job details does not have the Edit Job Details button contrary to design spec

## Screenshot
https://user-images.githubusercontent.com/51795389/116803624-193e5b00-ab37-11eb-8636-c8681a552a47.mp4

## Actual Result
Edit Job Details button is not there

## Expected Result
Edit Job details button should be there

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by SathyaJayabal** [comment]
already tracked here
https://github.com/topcoder-platform/taas-app/issues/112
