### ISSUE TITLE
Report Issue > SUBMIT button text is not visible, also bgcolor inconsistent with design spec causing low contrast

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#226]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on INTERVIEW SCHEDULER TEST PROJECT
4. Click 'Report an issue'
5. Currently , the SUBMIT button text is not legible. The design spec background color is (#e9e9e9) . The deployed app's submit button background color is (#f8f8f8) . 

## Screenshot
https://user-images.githubusercontent.com/51795389/116803956-b352d300-ab38-11eb-8204-1e5e6670a549.mp4
Deployed app
![is_supplementary](https://user-images.githubusercontent.com/51795389/116803983-ea28e900-ab38-11eb-8cee-93ceb9e975de.png)
Design spec
![is_supplementary_](https://user-images.githubusercontent.com/51795389/116803994-fd3bb900-ab38-11eb-98b5-f5a9da8b0583.png)

## Actual Result
Report Issue > SUBMIT button text is not visible, also bgcolor inconsistent with design spec causing illegibility

## Expected Result
The design spec should be followed,it is legible .

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
because the report is empty
