### ISSUE TITLE
[Functional] Resource Rate Frequency has an empty value in dropdown

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#227]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on 'INTERVIEW SCHEDULER TEST PROJECT'
4. Click on 'CREATE POSITION'
5. Click on 'Resource Rate Frequency' 
6. Currently, this dropdown has an empty value option

## Screenshot
https://user-images.githubusercontent.com/51795389/116804117-e9448700-ab39-11eb-9935-2a230ae729a4.mp4

## Actual Result
Resource Rate Frequency has empty value option

## Expected Result
Resource Rate Frequency should not have empty values so as to not cause problems while submitting

## Device|OS
Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
not a bug
