### ISSUE TITLE
[Functional] Workload dropdown has an empty dropdown value

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/taas-app#228]
## Steps to Recreate

1. Open https://platform.topcoder-dev.com/taas/myteams
2. Login as TopAcc_three/ Appirio123 if not already logged in
3. Click on any of the projects visible
4. Click CREATE POSITION
5. Click on Workload in dropdown 
6. Currently there is an empty dropdown field in the options

## Screenshot
https://user-images.githubusercontent.com/51795389/116804160-3aed1180-ab3a-11eb-8e26-78bd36b1dbee.mp4

## Actual Result
Workload has an empty value in dropdown

## Expected Result
Workload should not have empty values so as to not cause problems while submitting

## Device | OS | Browser
Desktop | Windows 10 Build 19042.928 | Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by nikolay83** [comment]
not a bug
