### ISSUE TITLE
[Content] Update Candidate Selected Message

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#229]
Update Candidate Selected Message  from "Candidate is marked as Interested" to "Candidate is marked as Selected" when the candidate is selected.
<img width="1440" alt="Screenshot 2021-05-02 at 12 54 24 PM" src="https://user-images.githubusercontent.com/58783823/116805713-d932a480-ab45-11eb-87df-e9a5920674af.png">

**Comment by SathyaJayabal** [comment]
Could also update the "Candidate is marked as not Interested" message to "Candidate is marked as Declined"

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/118082646-80da8d00-b3f8-11eb-87b3-6791e9dc7503.png)
![image](https://user-images.githubusercontent.com/55895538/118082674-8e901280-b3f8-11eb-8e6e-a45938191793.png)
![image](https://user-images.githubusercontent.com/55895538/118082885-f181a980-b3f8-11eb-80a4-8bfbb4b826b5.png)
![image](https://user-images.githubusercontent.com/55895538/118082909-fcd4d500-b3f8-11eb-88c3-6d1831336632.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.

<img width="727" alt="selected" src="https://user-images.githubusercontent.com/55895538/118448902-8227f480-b72d-11eb-86d5-04fc12448654.png">
<img width="727" alt="declined" src="https://user-images.githubusercontent.com/55895538/118448913-8522e500-b72d-11eb-9478-51ba331d3fa6.png">
