### ISSUE TITLE
string "0" appended to skill strings

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#23]
Whenever a list of skills does NOT have enough skills to create the "and x more" link, there is a "0" appended to the end of the last skill:

![image](https://user-images.githubusercontent.com/6014049/101539925-43fffb00-396d-11eb-8968-0fcf33807ae2.png)

**Comment by maxceem** [comment]
Done by e2c5604cd8c6b2e9a50e1a0b417b0382c7c451bf

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-12-21 at 4 23 55 PM" src="https://user-images.githubusercontent.com/58783823/102769640-f477f100-43a8-11eb-972a-5ba55c459fa5.png">

**Comment by SathyaJayabal** [comment]
Verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 27 43 PM" src="https://user-images.githubusercontent.com/58783823/106148345-f3ec2a80-619e-11eb-8d98-c641f55dd25e.png">
