### ISSUE TITLE
[Content] "0% SKILL MATCHED" should be "0% SKILLS MATCHED"

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/taas-app#230]
### Steps to Reproduce ###

1. open https://platform.topcoder-dev.com/taas/myteams/17258 (login with TopAcc_three/ Appirio123 if not already logged in)

2. click on each tab to see the text "0% SKILL MATCHED"

3. hover on "Sketch, Graphic Design", observe that "Skills" is used

### Expected Result ###
"0% SKILL MATCHED" should be "0% SKILLS MATCHED".

### Actual Result ###
See the screenshots.

### Screenshot and/or screencast ###
![17](https://user-images.githubusercontent.com/4590317/116807524-2cb4ea80-ab66-11eb-8528-93624de308d1.jpg)

![17 1](https://user-images.githubusercontent.com/4590317/116807523-2a529080-ab66-11eb-8289-4aee636fbcc3.jpg)

### Device/OS/Browser Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.7*

Browser Version: *Firefox 88.0 (64-bit)*

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/118461469-ae953e00-b738-11eb-9bd2-7b97394ddb68.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1139" alt="Screenshot 2021-05-17 at 4 20 08 PM" src="https://user-images.githubusercontent.com/58783823/118476969-cb774480-b72b-11eb-91f0-bb129c235d16.png">
