### ISSUE TITLE
[UI/UX] Alignment issue with dropdown box

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#231]
### Description:
[Alignment issue with dropdown box](url)

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas` 
2. click on the any 'team'.
3. under Open position click on `Review Candidate`
4. under any of these tabs `TO REVIEW`, `INTERVIEWS`, `SELECTED`, `DECLINED` (select any of these), 
click on the dropdown as shown below, observe for the alignment of the dropdown with the parent input field.

---

### Video / Snap:

![image](https://user-images.githubusercontent.com/67191980/116808229-4b5eb580-ab55-11eb-8d5f-e830c952a7a0.png)

---

### Actual result:

The width of the dropdown box is shorter than the parent input field

---

### Expected result:

the dropdown should be matching with the parent dropdown box, 

![image](https://user-images.githubusercontent.com/67191980/116808384-08e9a880-ab56-11eb-8d16-3ec2b89c3dde.png)

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/118463804-26646800-b73b-11eb-808d-737e33d03e39.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/118478233-97f7e280-b74a-11eb-8b09-70d083811101.png)
