### ISSUE TITLE
[UI/UX] Missing blue highlight border for the description box when active.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#232]
### Description:
Missing blue highlight border for the description box when active.
---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas` 
2. click on any 'team'.
3. under Open position click on `create position`
4. observe for the create job page to be opened
4. try to input some values in the respective input fields, while entering the values to the fields, observe for the border which gets highlighted in blue colour when the user is entering some values/ input fields are selected and active.

---

### Video / Snap:

https://user-images.githubusercontent.com/67191980/116808639-8cf06000-ab57-11eb-81dc-cca78db6b8e8.mp4

---

### Actual result:

All the input fields are getting highlighted when they are active, except the Job description, text area

---

### Expected result:

the job description text area should also get highlighted in blue when active or the values are being entered to it

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/118463523-cc63a280-b73a-11eb-8efe-f9a27b12a9d8.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="708" alt="Screenshot 2021-05-17 at 4 26 48 PM" src="https://user-images.githubusercontent.com/58783823/118477813-bd75f380-b72c-11eb-99a3-e871dd65365f.png">
