### ISSUE TITLE
[functional] Pressing the Refresh button while the 'Schedule your availability.' modal, closes the modal after refreshing the page.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#233]
### Description:
Pressing the Refresh button while the 'Schedule your availability.' modal, closes the modal after refreshing the page.

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams` 
2. click on any team which has the candidate added for interview.
3. click on  **Review Candidate** 
4.  click on the **Action** button
5. click on `Schedule interview` Or `Schedule another.
6. click on the browser refresh button, and observe the modal disappear from the page

---

### Video / Snap:

https://user-images.githubusercontent.com/67191980/116817448-01d98f00-ab84-11eb-8b2c-d6876869088b.mp4

---

### Actual result:

after pressing the refresh button, the modal disappears from the page.

---

### Expected result:

the refreshing the page should not cause any modal to disappear from the page unless the user interacts with it

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
not sure what's wrong with it
