### ISSUE TITLE
[functional] Open position is not updated after the selection of a candidate for the job.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#234]
### Description:
Open position is not updated after the selection of a candidate for the job.

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams` 
2. click on any team which has the candidate added for interview.
3. click on  **Review Candidate** 
4. Select any of the available candidates, make sure the candidate is selected and the status is updated on SELECTED tab.
5. navigate back to the team page and observe the Number of Open position, to get updated 

---

### Video / Snap:

https://user-images.githubusercontent.com/67191980/116819358-6e0cc080-ab8d-11eb-8f04-6d33b80efa60.mp4

---

### Actual result:

When the Candidate got selected for the job the open position is not getting updated.

---

### Expected result:

The Open position under the job title should get updated after the candidate is selected with an interview.

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by SathyaJayabal** [comment]
as per design

**Comment by swap12875** [comment]
Hi @nikolay83,

> as per design

refer to https://github.com/topcoder-platform/taas-app/issues/242#issuecomment-831695365, If this is so

 then can you please clarify the above comment. 
If we apply the business logic here if any vacancy gets filled up then the position should not be displayed as `open`, because it will make confusion for whether the position is available for filling or not. 

As I  think this is a functional issue and should be addressed with the proper weightage.

**Comment by SathyaJayabal** [comment]
@swap12875 , positions will be filled only when candidates are placed and not selected. There is further business logic. The behaviour is as per the design.
