### ISSUE TITLE
Scedule an Interview modal gets bigger while selecting Email "Add More" link

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/taas-app#236]
Steps to reproduce:
1. Goto the https://platform.topcoder-dev.com/taas/myteams/17305/positions/d8d96781-a86f-4752-9b2c-8a21b4de1743/candidates
2. click on any team which has the candidate added for interview.
3. click on Review candidates
4. Click on Actions dropdown
5. Click on "Schedule Interview"
6. click on "Add More" link
7. Schedule Interview modal gets bigger upon selecting it
Video / Snap:

https://user-images.githubusercontent.com/13567734/116821760-c39a9a80-ab98-11eb-9ba7-358e20fa8e71.mp4

Actual result:
The popup is getting bigger upon selecting it

Expected result:
The Popup should not get bigger upon selecting more link

Device/Browser Info
Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)]
![os-browser](https://user-images.githubusercontent.com/13567734/116821805-f93f8380-ab98-11eb-898e-1e8ce948d290.jpg)

**Comment by nikolay83** [comment]
that's expected
