### ISSUE TITLE
[Content]Select Candidate contents were not ended with (.) mark

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/taas-app#237]
Steps to reproduce:

1. Goto the https://platform.topcoder-dev.com/taas/myteams/17305/positions/d8d96781-a86f-4752-9b2c-8a21b4de1743/candidates
2. click on any team which has the candidate added for interview.
3. click on Review candidates
4.Click on Actions dropdown
5. Click on "Select Candidate"
6. Observe the content were not ended with (.) mark

Video / Snap:

https://user-images.githubusercontent.com/13567734/116822080-820aef00-ab9a-11eb-99c4-976d31ef6f45.mp4

Actual result:
The select candidate contents were not ended with (.) mark.

Expected result:
The select candidate popup contents should ended with (.) mark.

Device/Browser Info
Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)]
![os-browser](https://user-images.githubusercontent.com/13567734/116822144-c0a0a980-ab9a-11eb-9348-80c36e06c184.jpg)

**Comment by nikolay83** [comment]
it looks ok without dots
