### ISSUE TITLE
[functional] After clicking `“Begin Scheduling"` from the 'Schedule an interview' modal doesn't initiate emails to all attendees.

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#238]
### Description:
After clicking `“Begin Scheduling"` from the 'Schedule an interview' modal doesn't initiate emails to all attendees.

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. click on the 'Review Candidate' button.
3. On the candidate review page, click on the input field **Action**  then on 'Schedule an interview' / 'Schedule another interview'.
4. In the `schedule an interview` modal/popup add some valid email Id's as attendees email id.
5. click on 'Begin Scheduling', and observe for the email to be get received on the respective email id's

---

### Actual result:
The email is not being received in the provided email Ids with the current app build

---

### Expected result:

The added email should be receiving the email notification to input thier availability.

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
can't reproduce it

**Comment by swap12875** [comment]
@nikolay83 , I tried to add the attendee's email, and checked the email ids after clicking on the 'Begin scheduling' but I haven't received the invitation mail for it.  As I thought you may have access to the email which appears by defaults in the add email field so not attached the video, 

If required I can attach the video here. 
Please confirm if you required the Repro video?

**Comment by nikolay83** [comment]
1. Have you checked the spam folders?
2. The video was strongly recommended initially in the spec, so I am not sure why are brining it up just now.
3. We've had the demo Monday and it worked successfully.
