### ISSUE TITLE
Show job title for resources

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#24]
![image](https://user-images.githubusercontent.com/146016/101540857-4a13cd00-39a9-11eb-92b3-f6b848f3fb03.png)

**Comment by maxceem** [comment]
Done via c8ce24b5a89901c54796747cd00e7077713640e7

**Comment by sandhiyakavi** [comment]
Verified.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102769739-6b6fb280-43c6-11eb-9b77-7d2348f0a009.png)

**Comment by SathyaJayabal** [comment]
Verified in Prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 28 50 PM" src="https://user-images.githubusercontent.com/58783823/106148491-1aaa6100-619f-11eb-9251-1a940e645e03.png">
