### ISSUE TITLE
[Content] "No Declined" should be "No declined candidates"

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/taas-app#240]
Steps to reproduce:

1. Goto the https://platform.topcoder-dev.com/taas/myteams/17305/positions/d8d96781-a86f-4752-9b2c-8a21b4de1743/candidates
2.click on any team which has the candidate added for interview.
3.click on Review candidates
4.Click on "Declined"
5. Observe the content "No Declined" should be "No candidates were declined"

Video / Snap:

https://user-images.githubusercontent.com/13567734/116823159-8f2adc80-aba0-11eb-8f26-46b6dc333ae3.mp4

Actual result:
The declined candidates is showing "No declined"

Expected result:
The declined candidates should show "No candidates were declined"

Device/Browser Info
Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)]
![os-browser](https://user-images.githubusercontent.com/13567734/116823217-e466ee00-aba0-11eb-928d-85034dcbb126.jpg)

**Comment by SathyaJayabal** [comment]
@nikolay83 , need to update text to "No Declined Candidates"

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/118461948-24010e80-b739-11eb-939c-858261dcc9c3.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1101" alt="Screenshot 2021-05-17 at 4 14 06 PM" src="https://user-images.githubusercontent.com/58783823/118477089-f06bb780-b72b-11eb-8694-ac4518ae8b7e.png">
