### ISSUE TITLE
[functional] 'Complete' status for an interview in ambiguity/ not displayed

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#241]
### Description:
'Complete' status for an interview in ambiguity/ not displayed

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. click on the 'Review candidate' button.
3. select any candidate for the job
4. **refer to** the marvel app link [here](https://marvelapp.com/prototype/921gg0f/screen/78382377)
5. Observe for the complete status of the selected candidate/interview in progress candidate/ declined candidate,

---

### Video / Snap:

![complete status](https://user-images.githubusercontent.com/67191980/116831493-5c4b0d80-abcd-11eb-8c2a-6b499d68ece2.jpg)

---

### Actual result:

the interview status is only displayed as `scheduling` but `complete` status is not getting updated anywhere on the page under any of the tabs like `selected candidate`/`interview` in progress candidate/ `declined ` candidate,

---

### Expected result:

there should be an updated status for the interview of the candidate if completed/ in relevant tabs. as shown in the marvel app reference. ELSE The `complete` status should be made clear for whom it would be displayed! (should remove the ambiguity)

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
with these steps to reproduce it won't be. Candidate and customer must agree on timing in x.ai, and then the time of this interview must have passed

**Comment by swap12875** [comment]
@nikolay83 agreed, but the **Note** regarding this 

_(candidate and customer interaction) is not in scope_ 

should have been provided in Challenge details. This would have been more helpful for testers.
