### ISSUE TITLE
[layout[ 'Schedule another interview' status for an interview   not displayed under inerview tab as per marvel app

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#242]
### Description:
'Schedule another interview' status for an interview   not displayed under inerview tab as per marvel app

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. click on the 'Review candidate' button.
3. select any candidate for the job
4. **refer to** the marvel app link [here](https://marvelapp.com/prototype/921gg0f/screen/78382379)
5. Observe for the tab marked in the above-mentioned

 marvel app design 
 

---

### Video / Snap:

![Schedule another interview](https://user-images.githubusercontent.com/67191980/116831901-c49aee80-abcf-11eb-9ec5-ac74f1d5af9f.jpg)

---

### Actual result:

The tab displayed in marvel app can't be made displayed by any operation with the candidate interview, either complete, scheduling.

---

### Expected result:

The tab may be made directly available under the `interview` tab as per the marvel app design

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
Not 100% sure what you mean, and also the object of this bug hunt is the app implementation not the marvel app design
