### ISSUE TITLE
`view the previous interview`  should displayed under `selected`/ `declined` candidates

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/taas-app#243]
### Description:
`view the previous interview`  should display under `selected`/ `declined` candidates.

---

### Steps to reproduce:

1. Goto the `https://platform.topcoder-dev.com/taas/myteams/17258` 
2. click on the 'Review candidate' button.
3. select any candidate for the job

 

---

### Actual result:

The 'view previous interview' tab is not displayed under the selected/declined candidates tab
---

### Expected result:

if the user wants to see the previous interview for the candidate he should see the one under the selected /declined tab

---

### Device/Browser Info

Device details: Laptop/Windows 10 pro

Browser : Chrome [Version 89.0.4389.90 (Official Build) (64-bit)] 

<img src="https://user-images.githubusercontent.com/67191980/116800539-ac6b9680-ab1f-11eb-9434-a6c6216b74b3.jpg"  width="120" height="120">

**Comment by nikolay83** [comment]
there is no such requirement. Once the decision is made, the interview history does not matter anymore
