### ISSUE TITLE
Report and Issue and Request Extension emails are sent with empty subject and body

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#246]
Report and Issue and Request Extension emails are sent with empty subject and body

**Comment by SathyaJayabal** [comment]
verified for 
1. Report Issue for Team form My teams page
<img width="942" alt="Screenshot 2021-05-03 at 1 50 46 PM" src="https://user-images.githubusercontent.com/58783823/116855808-a1942d00-ac17-11eb-8c91-d3b812440b1a.png">
2. Report Issue for Team form Team Details page
<img width="945" alt="Screenshot 2021-05-03 at 1 51 30 PM" src="https://user-images.githubusercontent.com/58783823/116855830-ace75880-ac17-11eb-9be9-3e875f1ef61d.png">
3. Report Issue for Team member
<img width="954" alt="Screenshot 2021-05-03 at 1 50 15 PM" src="https://user-images.githubusercontent.com/58783823/116855856-bb357480-ac17-11eb-8a91-bf55a0200744.png">
4. Request extension for Team member
<img width="911" alt="Screenshot 2021-05-03 at 1 56 11 PM" src="https://user-images.githubusercontent.com/58783823/116855882-ca1c2700-ac17-11eb-977f-ce133ee8a83e.png">

cc @nkumar-topcoder @urwithat

**Comment by cagdas001** [comment]
Don't you use a SendGrid template for these?

**Comment by SathyaJayabal** [comment]
@nkumar-topcoder verified on prod , on CW.

**Comment by nkumar-topcoder** [comment]
@SathyaJayabal This has been verified at Cloudwatch logs with no issues.
