### ISSUE TITLE
Interview scheduling process stopped if the attendees chose different time for the meeting.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#252]
Description:

Interview scheduling process stopped and not proceeding further if the attendees chose different time for the meeting.

Steps to Reproduce:

1. Schedule interview with Interviewee, interviewer and one additional attendee.
2. The Attendee made himself as optional.
3. Interviewee and Interviewer choose different times for the meeting.

Actual result:
The process gets hanged.

Jod id: e848da0c-a4e8-405c-b9d6-b06c5585cc4a
Interview id: bc9aea8c-b2da-4e0a-bdfc-6c6736976d9e

![image](https://user-images.githubusercontent.com/55895538/117962831-9dc08300-b35a-11eb-9445-f5f334391ac4.png)

**Comment by nikolay83** [comment]
@urwithat can it be a problem on Zapier side?

**Comment by urwithat** [comment]
@nikolay83 - not related to Zapier, it's mainly from `x.ai`. In my opinion, we can disregard this case.
We might have to discuss this one with x.ai and see what best we can do, or if there is a possibility of disabling the option of allowing any member to mark them self's as optional.

**Comment by sandhiyakavi** [comment]
@urwithat But the issue is not because of marking as 'optional' but since the interviewer and interviewee chose different time, the process got stopped (The interview can't be scheduled for a particular time). What would be the solution if one person wants different time and not the same one selected by another person incase of only 2 persons (interviewee and interviewer).

**Comment by sandhiyakavi** [comment]
This issue is no longer applicable as x.ai is replaced by Nylas now.
