### ISSUE TITLE
Job description is still readonly eventhough the Application form is disabled in recruitcrm

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#257]
Description:

Job description is still readonly eventhough the Application form is disabled in recruitcrm.

![image](https://user-images.githubusercontent.com/55895538/118112242-b5157400-b41f-11eb-95db-2e2e90e91632.png)
![image](https://user-images.githubusercontent.com/55895538/118112323-d4140600-b41f-11eb-985b-7622f5366965.png)
![image](https://user-images.githubusercontent.com/55895538/118112367-e0985e80-b41f-11eb-9025-45cc79855ed3.png)

Note: Enabling the application form from rcrm is working fine though.

cc: @nkumar-topcoder

**Comment by SathyaJayabal** [comment]
This is fixed and verified on dev, @sandhiyakavi 
closing this as it was only an issue on dev

cc @urwithat @nikolay83
