### ISSUE TITLE
[Bug] - Edit Job Security Permissions

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#258]
The user who created this job: https://platform.topcoder.com/taas/myteams/28071/positions/c1e106d2-a98f-4c59-a20e-aa1102e22d89

is unable to see the "Edit Job Details" button.

User handle: harishnachiraju

**Comment by wdprice** [comment]
@maxceem - not sure if you have permissions to troubleshoot this in prod, but figured I'd start with you while the rest of the team is out. If you lack permissions please re-assign to @nkumar-topcoder to review on his return.

**Comment by sandhiyakavi** [comment]
@wdprice It's an existing issue https://github.com/topcoder-platform/taas-app/issues/112. At present only Booking Manager/Admin will be able to view "Edit Job Details" button.
But the creator of the job can still edit the Job by accessing the edit job page directly.(through url).

**Comment by maxceem** [comment]
I'm closing this issue as a duplicate. The task is already in process.
