### ISSUE TITLE
Interview status not updating from x.ai

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#261]
Interview status not updating from x.ai.

**Comment by SathyaJayabal** [comment]
This is fixed now.

**Comment by SathyaJayabal** [comment]
verified all 4 zaps
<img width="1134" alt="Screenshot 2021-05-15 at 10 48 12 AM" src="https://user-images.githubusercontent.com/58783823/118349404-1a777b00-b56e-11eb-8e25-0eac5efc74a8.png">
<img width="1105" alt="Screenshot 2021-05-15 at 10 54 33 AM" src="https://user-images.githubusercontent.com/58783823/118349407-1d726b80-b56e-11eb-9c6b-26cae905507b.png">
<img width="1145" alt="Screenshot 2021-05-15 at 11 03 29 AM" src="https://user-images.githubusercontent.com/58783823/118349408-1ea39880-b56e-11eb-95fc-4599575f03f0.png">
<img width="1120" alt="Screenshot 2021-05-15 at 11 09 46 AM" src="https://user-images.githubusercontent.com/58783823/118349409-1f3c2f00-b56e-11eb-8453-02adafee7305.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.
