### ISSUE TITLE
UI issues in TAAs Intake app

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#276]
There are several minor UI issues observed in the app that do not match the marvel app, recording all of them here.

**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam

**Issue 1**
Page title needs to be bold to match the design(font weights don't match)

Design:
![image](https://user-images.githubusercontent.com/4592712/119763879-fe5ccd80-becd-11eb-8971-31e062d9314f.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119763914-146a8e00-bece-11eb-84a6-e2e0ace5a960.png)

**Issue 2**
The text under the page title doesn't exactly match the text in the marvel app

Design:
![image](https://user-images.githubusercontent.com/4592712/119764696-82fc1b80-becf-11eb-9c24-39c74510762b.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119764805-b76fd780-becf-11eb-8dee-6b7d553075e4.png)

**Issue 3**
Select button style/color/font on the landing page doesn't match the design

Design:
![image](https://user-images.githubusercontent.com/4592712/119764916-e423ef00-becf-11eb-8090-af0931cc5564.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119764963-f43bce80-becf-11eb-9d78-ebae0726be33.png)

**Issue 4**
On the landing page, the left navigation should expand to the bottom

![image](https://user-images.githubusercontent.com/4592712/119772315-9497f000-bedc-11eb-9f90-f212a0649bb6.png)

**Issue 5**
Input Skills Page title needs to be bold to match the design(font weights don't match)

Design:
![image](https://user-images.githubusercontent.com/4592712/119772556-007a5880-bedd-11eb-8268-ee65eff8a8a8.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119772592-0cfeb100-bedd-11eb-86cc-cc70023498b1.png)

**Issue 6**
The font sizes and the button size/style doesn't match in the completeness box

Design:
![image](https://user-images.githubusercontent.com/4592712/119773009-afb72f80-bedd-11eb-83c6-56a6e2a056c4.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119773067-bc3b8800-bedd-11eb-96a7-e48992933ac7.png)

**Issue 7**
The border around the selected skill boxes needs to be more bold to match the design

Design:
![image](https://user-images.githubusercontent.com/4592712/119773278-09b7f500-bede-11eb-8668-2835b72fe91e.png)

App:
![image](https://user-images.githubusercontent.com/4592712/119773308-13d9f380-bede-11eb-93d4-d099dc74f130.png)

**Issue 8**
The text at the bottom of 'WE HAVE MATCHING PROFILES' screen, goes beyond the area

App:
![image](https://user-images.githubusercontent.com/4592712/119773559-6e734f80-bede-11eb-9501-931b4f7433b3.png)

**Issue 9**
Color of the text "Hi <user>, we have special rates for you as a Xeno User!" in we have matching profiles user page should be #219174

Design:
![image](https://user-images.githubusercontent.com/4592712/122159930-b6a5e200-ce8c-11eb-907f-5493fdcb56be.png)

App:
![image](https://user-images.githubusercontent.com/4592712/122159962-c4f3fe00-ce8c-11eb-9a3a-b53e3ab0cedf.png)

**Comment by nikolay83** [comment]
Issue 2: the text in the implementation is grammatically correct, in design - not

**Comment by sdgun** [comment]
@nikolay83 Issue 5 is common to the Roles and Job Description pages too, please let me know if you want me to create a separate issue for that

**Comment by sdgun** [comment]
@nikolay83 Issue 3,4,6, and 9 in the description are not fixed, are we ok to keep them as they are?

**Comment by nikolay83** [comment]
@sdgun neither me not the developer working on it cannot reproduce those 3,4,6 and 9. Can it just cache in your browser.
Even if not, I think we are ok to keep it. E.g. I can't tell the color difference in issue 9 example :)

**Comment by sdgun** [comment]
Verified in production.
