### ISSUE TITLE
Browser back button is opening the landing page while on skills search results

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#277]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click Select on the skills box
Select some skills and click search on the completeness box
Then click browser back button

**Expected behavior**
Since there is no way for the user to go to skills page from the skill search results page(WE HAVE MATCHING PROFILES page), it is better to take the user back to the skills page with browser back button

**Current behavior**
Browser back button is opening the landing page while on skills search results

https://user-images.githubusercontent.com/4592712/119775688-9617e700-bee1-11eb-9fae-01e6c997acc1.mp4

**Comment by nikolay83** [comment]
Layout improvement could help here by putting some button to come back to search.
@wdprice wdyt?

**Comment by sdgun** [comment]
Verified in Dev, in all flows, back button is navigating to the previous page.

**Comment by sdgun** [comment]
Verified in production.
