### ISSUE TITLE
The page shrinks when entering a non existing skill

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#279]
Steps
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click Select on the skills box
Enter some text that doesn't match any existing skill

The skills area is shrinking

https://user-images.githubusercontent.com/4592712/119782962-66b9a800-beea-11eb-9eb3-8064d0d7c176.mp4

**Comment by sexta13** [comment]
I believe this bug no longer is reproducible

**Comment by sdgun** [comment]
Looks like this has been fixed by some other fix, closing as this cannot be reproduced now.
