### ISSUE TITLE
When click Submit Request multiple times, duplicate jobs are created

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#280]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click Select on the skills box
Select some skills and click search on the completeness box
Click Submit Request button
Close the ADD ANOTHER POSITION pop up either using the close(x) button OR by clicking outside of the pop up
Click Submit Request button again

**Current behavior**
This will create the same job multiple times in since we are calling the jobs API in each click with the same project Id

It will be better not to give a way to click Submit request button twice. We can remove the ability to close  ADD ANOTHER POSITION pop up

https://user-images.githubusercontent.com/4592712/119784987-65897a80-beec-11eb-9de2-335031023e5e.mp4

**Comment by sexta13** [comment]
this no longer is happening....

**Comment by sdgun** [comment]
With the latest changes we have done to the app, submit is not submitting the project. So this issue is not valid anymore.
