### ISSUE TITLE
Search button is enabled when pressing enter button

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#294]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'INPUT JOB DESCRIPTION' box
Press enter key ones

**Current behavior**
Search button on the completeness box is enabling 

**Expected behavior**
"Search" button should be active if at least if there at least 10 chars in the editor

https://user-images.githubusercontent.com/4592712/120599576-52832700-c465-11eb-9a0b-5692d4d77d6b.mp4

**Comment by nikolay83** [comment]
Looks like normal UX to me
