### ISSUE TITLE
The tab selection is not reset when opening different descriptions

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#298]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Click the Description link on the role tiles
Click Skills tab
Close the pop up
Now click the Description link of another role

**Current behavior**
It's opening the skills tab of that role 

**Expected behavior**
The pop up should be opened and show the Job Description by default

https://user-images.githubusercontent.com/4592712/120748132-e44f6a80-c51f-11eb-9e0a-36236a144c1e.mp4

**Comment by sexta13** [comment]
can't reproduce

**Comment by sdgun** [comment]
This issue cannot be reproduced now.
