### ISSUE TITLE
The '# of resources' and 'Duration (weeks)' should be 0 by default on the Team Details page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#310]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Click Submit
Click Continue
Check the values in '# of resources' and 'Duration (weeks)'

**Current behavior**
'# of resources' show 3 and 'Duration (weeks)' show 20

**Expected behavior**
'# of resources' and 'Duration (weeks)' should be 0 when opening this pop up

![image](https://user-images.githubusercontent.com/4592712/122000043-d6290600-cdcb-11eb-855f-16923bff90af.png)

**Comment by nikolay83** [comment]
The default values 3 and 20 were intended (by me) to somehow anchor the customer to these numbers. @wdprice wdyt?

**Comment by sexta13** [comment]
@nikolay83 should we consider this bug? or leave 3 and 20 ?
