### ISSUE TITLE
Created TAAS Teams are not displayed in My Teams

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#312]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Click Submit
Click Continue
Enter a team name and description and other data
Click submit
Check the I agree... option
Click Confirm

**Current behavior**
This will open the TAAS Team, but when go to My Teams, the newly created Teams are not displayed

**Expected behavior**
The newly created Teams should be available in My Teams

https://user-images.githubusercontent.com/4592712/122004074-8f3e0f00-cdd1-11eb-95fd-bf7987b60814.mp4

**Comment by nikolay83** [comment]
The reason might be https://github.com/topcoder-platform/taas-app/issues/315

**Comment by sdgun** [comment]
Verified in Dev, the created Teams are displayed in TAAS Teams.

**Comment by sdgun** [comment]
Verified in Prod
