### ISSUE TITLE
sendRoleSearchRequest API responds with length error when the Job description is long, but the UI allows entering long description

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#316]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'Input Job Description' box
Enter a description which is 256 characters long
Click search
Check the sendRoleSearchRequest  API response in the Dev tools

**Current behavior**
Job description greater than 255 chars can be entered from UI but the sendRoleSearchRequest API throws the below error and shows NO MATCHING PROFILES page

message: "\"data.jobDescription\" length must be less than or equal to 255 characters long"

**Expected behavior**
@nikolay83 Atm we don't have a limit to JD from UI. If we want to have a limit better to have the restriction from UI too.

![image](https://user-images.githubusercontent.com/4592712/122042743-28801c00-cdf8-11eb-9583-5e819e938c24.png)

![image](https://user-images.githubusercontent.com/4592712/122042786-359d0b00-cdf8-11eb-9a8e-7f830396da65.png)

**Comment by nikolay83** [comment]
@wdprice will 2000 chars be enough?

**Comment by sdgun** [comment]
@nikolay83 the UI only allows 255 chars now, is this the expectation?

**Comment by nikolay83** [comment]
@sdgun No, must be 2000.

**Comment by sdgun** [comment]
Issue is not fixed, JD should allow 2000 chars but it only accepts 255 chars now.

![image](https://user-images.githubusercontent.com/4592712/123008613-d1221300-d3d8-11eb-8ff8-811d6ad507d1.png)

**Comment by sdgun** [comment]
This issue is fixed in Dev.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/124719219-8c43c380-df24-11eb-82e6-0c74339b55d7.png)
