### ISSUE TITLE
All positions are not displayed in the Team until the page is refreshed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#318]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Click Submit
Click Add another role and add a different role >> Search >> submit
Click submit
Check the I agree... option
Click Confirm
Check the open positions

**Current behavior**
The submitTeamRequest request is sending all positions but the Team only shows one position, but they will be displayed after the page is refreshed

**Expected behavior**
All positions submitted by submitTeamRequest  API should be displayed in the team 

https://user-images.githubusercontent.com/4592712/122161411-4c427100-ce8f-11eb-90e3-28a4f51207c9.mp4

**Comment by urwithat** [comment]
@nikolay83 , @sdgun - Can we show the loading screen for 15 / 30 sec more before redirecting to TaaS -> My Team
<img width="757" alt="Screenshot 2021-06-28 at 9 38 44 AM" src="https://user-images.githubusercontent.com/29911110/123579220-1e491f00-d7f5-11eb-8de8-88552c0e164e.png">

**Comment by sdgun** [comment]
This issue is not replicated anymore since we are navigating to the Teams page after creating the team.

**Comment by sdgun** [comment]
Verified in production.
