### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#32]
- [x] hide job cost
- [x] hide team weekly cost if 0
- [x] hide cost for resources if 0
- [x] remove mock server

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/taas-app/commit/06df9d173288531b9081d434cb2bfd41e24f98b1, https://github.com/topcoder-platform/taas-app/commit/9681d6176c383f603f43de2a6da533f17e7952ef, https://github.com/topcoder-platform/taas-app/commit/c6029e3f81d9e0a94318e009e4083b6fd31487ba, https://github.com/topcoder-platform/taas-app/commit/7874305911c0f29bf243e11229d7b85e2fbd0c57

**Comment by SathyaJayabal** [comment]
@maxceem , what is the 4th point `remove mock server` ?

**Comment by maxceem** [comment]
Before using real API we have some demo data inside this repository, so I've removed it. This cannot be seen from the outside here I just remove the code https://github.com/topcoder-platform/taas-app/commit/06df9d173288531b9081d434cb2bfd41e24f98b1

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-12-23 at 10 34 06 AM" src="https://user-images.githubusercontent.com/58783823/102961557-982ce280-450a-11eb-8de0-dfcb796dec14.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 42 32 PM" src="https://user-images.githubusercontent.com/58783823/106150102-ffd8ec00-61a0-11eb-9010-9df4b62c2eae.png">
<img width="1440" alt="Screenshot 2021-01-28 at 7 42 35 PM" src="https://user-images.githubusercontent.com/58783823/106150123-05cecd00-61a1-11eb-948e-78b2b94d84f0.png">
