### ISSUE TITLE
UI components overlap in mobile 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#320]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam from a mobile phone(Android/IOS)

It is very difficult to use the application in mobile devices since most of the UI components overlap

Device: Pixel XL
OS: Android 10
Browser: Chrome

Device: iPhone 6S
OS: 13.7
Browser: Safari

![Screenshot_20210616-125205_Chrome](https://user-images.githubusercontent.com/4592712/122176352-1eb2f300-cea2-11eb-8c55-452ab12aac8b.jpg)
![Screenshot_20210616-125222_Chrome](https://user-images.githubusercontent.com/4592712/122176359-207cb680-cea2-11eb-9245-dbae85ef7e17.jpg)
de
![Screenshot_20210616-125243_Chrome](https://user-images.githubusercontent.com/4592712/122176362-21ade380-cea2-11eb-9327-c96c5c0bf964.jpg)v

**Comment by nikolay83** [comment]
@sdgun how does it look in landscape orientation?
@wdprice will we have UI design for mobile portrait orientation or leave it on developers' discretion?

**Comment by sdgun** [comment]
@nikolay83 Landscape view looks better

**Comment by nikolay83** [comment]
Confirmed by @wdprice that mobile is out of scope and there is no UI design for it.
