### ISSUE TITLE
No validation when deleting the values in resources and duration fields in Team Details page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#321]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box (or use any flow)
Select a role
Click Search
Click Submit
Click Continue
Enter a team name
Delete the values in resources and duration fields

**Current behavior**
No validation message, submit button is enabled. But the API throws an error and the project is not submitted

**Expected behavior**
Should show a validation message

![image](https://user-images.githubusercontent.com/4592712/122180042-b49c4d00-cea5-11eb-975a-758a7edf3599.png)

![image](https://user-images.githubusercontent.com/4592712/122179972-a2baaa00-cea5-11eb-8b8b-f80f48e2a93d.png)

**Comment by sdgun** [comment]
Verified in Dev, this issue is still not fixed. The validation message of the fields gets removed when removing data from another field

https://user-images.githubusercontent.com/4592712/122738900-0d058d00-d2a0-11eb-88b8-fbd83b780e49.mp4

**Comment by sexta13** [comment]
To fix this, can we disable the input of numbers with the keyboard? just increment and decrement in the buttons?

**Comment by nikolay83** [comment]
What is the effort of fixing it this way vs the effort of keeping the input of numbers with the keyboard?

**Comment by sexta13** [comment]
the first approach I already implemented, the one with the keyboard I would have to understand better the react-final-form...which is somehow hard to understand.

**Comment by sexta13** [comment]
https://monosnap.com/file/e0pFxGC2dStL8RnBHr0yEv8jsr94gA 

This is how it looks. This way the user is unable to put invalid values. If we have + an - buttons, why to enable the input directly?

**Comment by sdgun** [comment]
Verified in Dev, validation error msg is displayed when deleting the values.

![image](https://user-images.githubusercontent.com/4592712/123908318-e2e55680-d994-11eb-9637-60649531aa6b.png)

**Comment by sdgun** [comment]
@nikolay83 This issue can be seen again in Dev.

![image](https://user-images.githubusercontent.com/4592712/124420892-0259f600-dd7e-11eb-9f5a-6b1b6a4d8c8e.png)

**Comment by sdgun** [comment]
Verified in Dev, issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/124538504-61307580-de39-11eb-9cc1-34d5e0b737bb.png)

**Comment by sdgun** [comment]
Verified in production

![image](https://user-images.githubusercontent.com/4592712/124718521-cd87a380-df23-11eb-8f63-e5c97498d19c.png)
