### ISSUE TITLE
There is no way to remove previously added roles and they do not get removed even after a log out

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#325]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Now the role is shown in the top right hand corner drop down

If the user wants to remove the role, there is no way to do that. Even after logging out and log in back, the previously added roles are there. 

![image](https://user-images.githubusercontent.com/4592712/122332408-fedc0780-cf53-11eb-9367-499bdfaeab8d.png)

**Comment by nikolay83** [comment]
Looks like a feature we missed (or omitted on purpose) in design. @wdprice should we add it?

**Comment by sdgun** [comment]
@nikolay83 Also noticed the roles added by one user is shown when another user logs in too

**Comment by sdgun** [comment]
Verified, the roles can be removed. Also verified the removed roles are not submitted in the submit team request.

**Comment by sdgun** [comment]
Verified in production, positions can be removed now.


https://user-images.githubusercontent.com/4592712/123238783-6538cb00-d4fc-11eb-8f47-4fe1a11f370d.mp4
