### ISSUE TITLE
Resource Type shows 'Unsuppored value:' for the positions

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#328]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Click Submit
Click Continue
Enter a team name and description and other data
Click submit
Check the I agree... option
Click Confirm
Click on a open position and check the details

**Current behavior**
Resource Type shows 'Unsuppored value:' for the positions even if the role name equals available resource type in TAAS

![image](https://user-images.githubusercontent.com/4592712/122344216-2a66ee00-cf64-11eb-952b-424101095a65.png)

**Comment by nikolay83** [comment]
@wdprice @urwithat So I guess resourceType is not a role? How can we derive resource type from what we have in the Role object? Should we a role type (e.g. Develop, Designer, Data Scientist, QA etc.)?

**Comment by nikolay83** [comment]
Confirmed by @wdprice as low priority. We will replace resource types with roles soon.
