### ISSUE TITLE
[Production] Sporadic error when submitting team request

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#329]
**Steps**
Go to https://platform.topcoder.com/taas/myteams/createnewteam/
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Click submit 
Select Add another role and add another role
and submit the team request

Sporadically one time noticed the below error and couldn't submit the request

![image (1)](https://user-images.githubusercontent.com/4592712/122372956-bb4ac300-cf7e-11eb-9058-9a4ae934724a.png)

![image](https://user-images.githubusercontent.com/4592712/122372975-c00f7700-cf7e-11eb-902f-d21a379efb88.png)

**Comment by nikolay83** [comment]
@sdgun were you able to reproduce it since then?

**Comment by sdgun** [comment]
@nikolay83 I didn't try this in production after that, but in Dev this cannot be reproduced.

**Comment by sdgun** [comment]
Closing as this couldn't be reproduced in prod.
