### ISSUE TITLE
Skill Match % Calculation

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#33]
Skill Matched % should be percentage of a users skills that match the assigned jobs skills.

Example: 
Job id: `d226c1d1-b38f-4ed8-82e7-36f1140f8ffe`
Job skills is
`2D Computer Graphics, 3D Projection, Java`
User Skills is:
`Java`

Expected : Skill Match %  should be 33.3 % (1 out of 3 skills)
Actual : Skill Match % is 1%

<img width="1440" alt="Screenshot 2020-12-21 at 12 32 02 PM" src="https://user-images.githubusercontent.com/58783823/102748680-a3f09b80-4388-11eb-8683-c33ff52c7ad3.png">

<img width="1440" alt="Screenshot 2020-12-21 at 12 31 47 PM" src="https://user-images.githubusercontent.com/58783823/102748651-92a78f00-4388-11eb-8f3f-f56cc413c90f.png">

**Comment by maxceem** [comment]
Fixed via 3aa1bf4d565a16b5007125179743b49a326e226d

![image](https://user-images.githubusercontent.com/146016/103137853-759af500-46d5-11eb-8afa-fa73968c7eb3.png)

As part of this task, we don't use `skillMatched` which is generated by the server, and calculate client-side using the list of job and user skills. So now we can remove it from the server https://github.com/topcoder-platform/taas-apis/issues/82

**Comment by sandhiyakavi** [comment]
Verified. working as expected.

![image](https://user-images.githubusercontent.com/55895538/103188516-0f4be780-490c-11eb-8ce3-eda38795901a.png)

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 39 24 PM" src="https://user-images.githubusercontent.com/58783823/106149680-8e00a280-61a0-11eb-8048-bc294d0f014b.png">
