### ISSUE TITLE
 UI issues on Safari

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#334]
1. The enabled search button text  must be in green
<img width="1440" alt="Screenshot 2021-06-21 at 9 16 55 AM" src="https://user-images.githubusercontent.com/58783823/122704638-b7b28700-d271-11eb-84e0-ec2b9e750a46.png">
2. Start month input is missing month picker
<img width="1440" alt="Screenshot 2021-06-21 at 9 21 34 AM 1" src="https://user-images.githubusercontent.com/58783823/122704879-36a7bf80-d272-11eb-8195-c121fe2124a8.png">

**Comment by sexta13** [comment]
Can't replicate the 2. The first one I've changed for all buttons.

**Comment by SathyaJayabal** [comment]
I dont see the button style updated yet.
<img width="1440" alt="Screenshot 2021-06-30 at 12 39 23 PM" src="https://user-images.githubusercontent.com/58783823/123917546-8be57e80-d9a0-11eb-9726-2c01430b261d.png">

Issue 2 cant be replicated.

**Comment by nikolay83** [comment]
Can't replicate issue 1 either nor can yet another developer. Could it be browser cache? @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@nikolay83 , I cannot still see the change after clearing cache. 

@lakshmiathreya , can you please help verify this issue.
1. Login and go to
https://platform.topcoder-dev.com/taas/createnewteam
2. Select first option (Select a role)
3. Select a role form the given list of roles
4. Check the style of the "Search" button
<img width="1440" alt="Screenshot 2021-07-02 at 11 03 39 AM" src="https://user-images.githubusercontent.com/58783823/124225516-32f32300-db25-11eb-9cf1-b0af5a3f91ac.png">

**Comment by nikolay83** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/3432907/124240290-e3a7f500-db1a-11eb-939d-9988e8498e6c.png">

I see it all correct. Safari 14.0.3 at BigSur.

**Comment by SathyaJayabal** [comment]
@nikolay83 , lets mark it as pass as its working for you. It could be an issue with my browser.

**Comment by sdgun** [comment]
Verified in prod
