### ISSUE TITLE
When the niche  role is returned, the  submit request button must be  enabled

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#336]
When the niche  role is returned, the submit request button must be enabled so  that the user can submit their request for the niche role.

<img width="1434" alt="Screenshot 2021-06-21 at 9 05 00 AM" src="https://user-images.githubusercontent.com/58783823/122705681-dca7f980-d273-11eb-9e53-94776dce66c5.png">

@nikolay83 is my understanding correct or we donot allow requests for the niche role?

**Comment by nikolay83** [comment]
Valid point, IMO, however as per the mockup it's disabled. @wdprice @urwithat wdyt?

**Comment by nikolay83** [comment]
Confirmed by @wdprice the bug is valid.

**Comment by sdgun** [comment]
@nikolay83 The submit button is still disabled.

![image](https://user-images.githubusercontent.com/4592712/123190555-626ab580-d4bd-11eb-9839-eeff3d4215cd.png)

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/124417458-d5561500-dd76-11eb-8338-a5a78f46865a.png)

**Comment by sdgun** [comment]
Verified in production.


![image](https://user-images.githubusercontent.com/4592712/124718337-a16c2280-df23-11eb-8468-f61c3c75bb9a.png)
