### ISSUE TITLE
Resource Type: unsupported value seen in job details and edit screens

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#338]
There are 4 options for resource type at present in the taas app. But when we create jobs from the Create team flow, a few other resource type values are added. 

<img width="1440" alt="Screenshot 2021-06-21 at 1 18 16 PM" src="https://user-images.githubusercontent.com/58783823/122726097-513e6080-d293-11eb-9669-3ae09b772adf.png">
<img width="1440" alt="Screenshot 2021-06-21 at 1 17 04 PM" src="https://user-images.githubusercontent.com/58783823/122726156-5dc2b900-d293-11eb-8b2c-72282b259985.png">

cc @urwithat @nkumar-topcoder

**Comment by sdgun** [comment]
Duplicate issue : https://github.com/topcoder-platform/taas-app/issues/328
