### ISSUE TITLE
After signing up, the user is not directed to the submission process

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#339]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam/ without logging in
Click select button in Select a role box
Select a role >> click search
Sign up and click activate account button in the email and log in

**Expected behavior**
Once a user signs up/in for TopCoder Directory she must return to the submission process and land at the next step after Submit request click as if the flow was not interrupted by authentication.

**Current behavior**
Shows a page with message "externalId: 88774932 "user" not found"

https://user-images.githubusercontent.com/4592712/122732787-3e7b5a00-d29a-11eb-8b7c-14299b47e190.mp4

**Comment by nikolay83** [comment]
Hmm.. just worked for with "topacc_three" account at Safari/Macos.
What account did you use?

**Comment by sdgun** [comment]
@nikolay83 Since we need a new user for signing up, I tested this by creating a new gmail account.

**Comment by SathyaJayabal** [comment]
@nikolay83 , I am alos not able to use my newly registered users on the taas app. I too get the external id user not found error. Is it because the corresponding user is not present in v5 ?

To replicate, please register a new account and try accessing the taas app.

**Comment by nikolay83** [comment]
a comment from @Eisbilir:
"it seems that newly created members are not getting created at v5 automatically.When frontend calls taas-teams/me, the endpoint searches for the user by externalId in v5 ecosystem and can't find it.We can find another way to get member's data without searching it in v5 ecosystem, Or we can focus on creating users in v5. I think it depends on what member data we need for that page".

@sdgun @SathyaJayabal have you tried to sign up and then sign in immediately outside of Roles Intake app?
@urwithat can it be yet another sync problem, like those many that we have when e.g. updating smith in the Working Manager and still seeing old data in OR.

**Comment by sdgun** [comment]
@nikolay83 I know the QA team is doing some testing around sign up and immediate log in after sign up is working in other apps.

**Comment by sdgun** [comment]
@nikolay83 Verified it with another new user, still we receive the same error


https://user-images.githubusercontent.com/4592712/123206539-80461380-d4d9-11eb-92c3-f0eff50f5266.mp4

**Comment by sdgun** [comment]
@nikolay83 When checking last time it worked after 2.5 mins, are we are ok with this time?

**Comment by nikolay83** [comment]
At least we need to communicate it properly to the customer (quick fix).
Proper fix would be to push the update the users data source or ES, before it's pulled via Kafka in ~2.5 min.
I deem it business critical as a new customer may churn from TC, if she has to wait for a few minutes.
@urwithat @wdprice  wdyt?

**Comment by urwithat** [comment]
This is related to member registration delay while the member is synched across all systems, especially TaaS! just a thought: can we have a loading icon till the member is available in the systems?
@sachin, @nkumar - any idea on where is the delay is happening!

**Comment by sdgun** [comment]
@urwithat @nikolay83 I checked this in production today and observed the submit page being displayed without any issue when I  signed up without any delays(sign up happened within 15 seconds after receiving activation email). In above comments I did the testing in Dev.

**Comment by SathyaJayabal** [comment]
@urwithat @nikolay83 @sdgun , I had created few test users last week for the registration testing on both dev and prod. I still face the issue in dev, while accessing taas app with the new users. Looks like these users did not get created on v5. 

But the prod users created during the same time, work fine.

**Comment by sdgun** [comment]
Verified in Dev, the userid issue is not thrown anymore.

**Comment by sdgun** [comment]
Verified in production
