### ISSUE TITLE
Fix filtering by "role" and full name

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#34]
![image](https://user-images.githubusercontent.com/146016/102765876-ebc1f380-4385-11eb-9165-4b610515b113.png)

**Comment by sandhiyakavi** [comment]
@maxceem Also filtering by name is not working if there is firstname and lastname for the candidate (there is space in between).
Works only for firstname.

https://user-images.githubusercontent.com/55895538/102773282-5433c380-43cc-11eb-8e63-2cc263b6ddc6.mp4

**Comment by maxceem** [comment]
Fixed by 2f87b4182fddacd5748e77da1281bf7d41de55a9

![image](https://user-images.githubusercontent.com/146016/103137999-ab8ca900-46d6-11eb-8068-dc1edff20fcb.png)

![image](https://user-images.githubusercontent.com/146016/103138003-b6473e00-46d6-11eb-8fd9-d12aec7e3e0f.png)

**Comment by sandhiyakavi** [comment]
Verified.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/103188746-07407780-490d-11eb-9ebb-035d759d45a5.png)
![image](https://user-images.githubusercontent.com/55895538/103189168-bd589100-490e-11eb-8f57-9cfc06fec68f.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 38 13 PM" src="https://user-images.githubusercontent.com/58783823/106149562-6c072000-61a0-11eb-8e90-44d35343cbf8.png">
