### ISSUE TITLE
Empty page with console errors when searching for skills or search from JD 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#340]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam/ 
Click select button in INPUT SKILLS box OR INPUT JOB DESCRIPTION
Select a skill (or enter JD) >> click search

**Current behavior**
Shows an empty page with below console error

![image](https://user-images.githubusercontent.com/4592712/122737016-3fae8600-d29e-11eb-813c-467405fc5026.png)

**Comment by nikolay83** [comment]
I guess the problem is it is getting a member by externalID. That's wrong, even for external members. It should get it by memberId or userId.

**Comment by sdgun** [comment]
Verified in Dev, this error is not displayed anymore.

**Comment by sdgun** [comment]
@nikolay83 I can see this error again with the role "Support Engineer"

![image](https://user-images.githubusercontent.com/4592712/123064122-9dbca400-d42b-11eb-92c1-c75dc1811d59.png)



https://user-images.githubusercontent.com/4592712/123063998-854c8980-d42b-11eb-8da0-3a980ecc7e8f.mp4

**Comment by sdgun** [comment]
Verified in production, this issue is fixed.


https://user-images.githubusercontent.com/4592712/123239264-d1b3ca00-d4fc-11eb-80c5-a5a8ac76ae39.mp4
