### ISSUE TITLE
The UI elements alignment issue when showing validation messages

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#343]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'Select a role' box
Select a role
Click search
Click submit >> continue
Enter 0 in resource and duration fields

**Current behavior**
![1](https://user-images.githubusercontent.com/4592712/122855415-dc226800-d332-11eb-9c0a-b01b8f05c176.png)
![2](https://user-images.githubusercontent.com/4592712/122855418-dd539500-d332-11eb-900a-c27c789a08d9.png)

**Comment by sexta13** [comment]
it depends on this https://github.com/topcoder-platform/taas-app/issues/321

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/123913850-5343a600-d99c-11eb-8bb0-b20007d4c1ed.png)

**Comment by sdgun** [comment]
Verified in production

![image](https://user-images.githubusercontent.com/4592712/124717734-0a06cf80-df23-11eb-92e2-43a0a135ad58.png)
