### ISSUE TITLE
After submitting the request, taas teams page is opening, a refresh is needed to show the created team

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#348]
**Steps**
https://platform.topcoder-dev.com/taas/createnewteam
Click select button in the 'SELECT A ROLE' box
Select a role
Click Search
Submit >> fill the data >> submit

After submitting, user is redirected to the Taas teams page, (before yesterday's changes we used to open the particular team just created)

The just created team is not on the page, a refresh is needed to see it

https://user-images.githubusercontent.com/4592712/123192014-b9718a00-d4bf-11eb-9ac8-905b3525e5be.mp4

**Comment by nikolay83** [comment]
@urwithat 
The request from the FrontEnd is being done. The server doesn't respond with the updated information, probably it's not synced immediately. I believe the solution can be to delay the request for a few second with some notification. Does it work?

**Comment by sdgun** [comment]
Verified with multiple teams/users, latest Team was displayed in Teams page.

**Comment by sdgun** [comment]
Verified in production.
