### ISSUE TITLE
Integrate Customer Scroll

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#355]
Integrate the scrolling customer feed from Topcoder.com into the app and keep it displayed at all phases. Doesn't need the same layout at Topcoder.com, but should show the same logos and instill confidence in the user.

![image](https://user-images.githubusercontent.com/6014049/123960970-e15c6400-d97d-11eb-978c-4bb0cab526ac.png)

**Comment by nikolay83** [comment]
@urwithat @wdprice 
any source code to reuse?
What will be the source of the images?

**Comment by wdprice** [comment]
I can check w/ marketing.

**Comment by wdprice** [comment]
@nikolay83 - this is a CSS keyframe animation

`  #box {
    background-image: url('https://www.topcoder.com/wp-content/uploads/2020/12/Homepage-Logos.svg');
    animation: backgroundScroll 300s linear infinite;
  }
  @keyframes backgroundScroll {
    from {background-position: 0 0;}
    to {background-position: -7701px 0;}
  }`

Adjust the keyframe “to” values depending on the size of the image that you are going to use.

May need some tinkering, but hopefully this gets us going in the right direction.

**Comment by sdgun** [comment]
@nikolay83 I do not see the customer scroll, checked in incognito too.

**Comment by nikolay83** [comment]
It used to work for me, but it's gone.

**Comment by sdgun** [comment]
@yoution I tried clearing cache and in multiple browsers but no luck

**Comment by yoution** [comment]
@sdgun @nikolay83 because the screen height is less than 859px, how to fix it?

![image](https://user-images.githubusercontent.com/3863914/126269735-909f3c3f-c1a9-4823-baff-0cd881150350.png)

**Comment by nikolay83** [comment]
@sdgun @urwithat 
something happened to the screen height. I have to zoom out to 67% to view it normally including the ribbon with logos.

**Comment by nikolay83** [comment]
@yoution 
It still requires zooming out down to 75% in Safari and Chrome.

**Comment by yoution** [comment]
@nikolay83 because Baghel add a minHeight restriction， if screen  height is smaller than the value, it will hide the scroll.
I don't know which screen height the scroll should support

**Comment by sdgun** [comment]
Verified in Dev in windows - Chrome/Firefox browsers. Noted the customer scroll shown on top of the page when the content is still being loaded. Not reporting new issues since this feature is to be changed as per https://github.com/topcoder-platform/taas-app/issues/402

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126950773-9240088b-1abb-4ecd-9113-9c9a85b1d071.png)
