### ISSUE TITLE
Move # of Resources per Role earlier in the flow

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#356]
Rather than having the customer confirm the # of resources for a role only in the last step, prompt them after they continue from the match screen to enter how many resources they need.

Keep the final screen as confirmation.

**Comment by nikolay83** [comment]
@wdprice 
>>Keep the final screen as confirmation
But still editable, right?

**Comment by wdprice** [comment]
Correct

**Comment by yoution** [comment]
@nikolay83 
add three input fields here?
and we can only edit the current search position?
![image](https://user-images.githubusercontent.com/3863914/125554587-c40c5e4e-d31d-41fa-ad25-a86833180d10.png)

**Comment by nikolay83** [comment]
1. Yes, here please.
2. Yes, only the current ones. The default values must be configured, and they will be 1 resource and 4 weeks. Also these are the minimum values.

**Comment by yoution** [comment]
@nikolay83 
when does the modal show?after searching the role or click the `submit Request`button?

**Comment by nikolay83** [comment]
@yoution 
please show the interface after the search is done. Currently this modal makes the search animation even shorter which is not desired.
Instead of the modal just add it to the march screen https://monosnap.com/file/07czrvUNuQ4jPm3q1omiI0kBqODhI0, the location is up to, e.g. beneath the match rate green circle will be fine, and "60% of members are available 20 hours / week (part time)" text will be removed anyway.

**Comment by nikolay83** [comment]
@yoution 
there are unnecessary scroll bars now
![image](https://user-images.githubusercontent.com/3432907/125909160-3b84cff0-4d51-43d9-841c-d9cdd2093bb8.png)

**Comment by yoution** [comment]
@nikolay83  
for first one, why not  update the data in the detail screen?

**Comment by nikolay83** [comment]
1. Do you mean Team Details? The idea is to let the user to update the value both in the Matching screen and the Team details screen. The values set in the Matching screen must be propagated to the Team details screen.

3. Also the "Save" button is redundant here and not clickable anyway. Please remove.

**Comment by yoution** [comment]
@nikolay83 
1. currently, if you set the value in Matching screen, it will pass to Team details screen,  this logic is wrong?
2. I can not reproduce the scrollbar issue
![image](https://user-images.githubusercontent.com/3863914/125912691-472fe46d-af2f-481c-9aec-4d67f7a7bd50.png)

**Comment by nikolay83** [comment]
1-2. I got it: user should have saved the input before she continues. That was not intuitive.
Please remove the Save button and do save the # weeks and # resources on Continue button click.
3. Please reuse validation from here https://github.com/topcoder-platform/taas-app/issues/362

**Comment by yoution** [comment]
@nikolay83 
how about this error reading?
![image](https://user-images.githubusercontent.com/3863914/125968811-60965e4c-9d8c-4246-b82a-2df0d16be2c7.png)

**Comment by nikolay83** [comment]
Actually, for # resources any message doesn't make sense, it's clear why it's not zero or -1 :) So just don't keep the existing way of validation response.
For # weeks - yes, looks good.

**Comment by sdgun** [comment]
Verified in Dev, there is a validation message for resource and it has a typo.

![image](https://user-images.githubusercontent.com/4592712/126106835-038dd192-8a4a-4b08-a2ec-3288efe0cece.png)

**Comment by sdgun** [comment]
Created issue https://github.com/topcoder-platform/taas-app/issues/390 for the above issue

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126951966-60c10a28-e45c-4d28-b712-f68e2deeb55a.png)
