### ISSUE TITLE
Update Default Values for Resource Count & Duration

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#362]
Update the default values for # of resources and duration for a given role:
![image](https://user-images.githubusercontent.com/6014049/125095642-65ab9700-e0a2-11eb-9532-9913a73ebbe0.png)

New Defaults:
#of resources: 1
Duration (weeks): 4

Do not accept input of a duration less than 4 weeks. Display an error reading: "Talent as a Service engagements have a 4 week minimum commitment."

**Comment by nikolay83** [comment]
@mbaghel 
this requirement is not implemented
Display an error reading: "Talent as a Service engagements have a 4 week minimum commitment."
Please note that #356 is also now implemented the # resources and # weeks set there must not be overridden by these defaults.

**Comment by mbaghel** [comment]
@nikolay83 
Right now the old error message is displayed if you enter a 0, a negative number or a float. The new error message is only displayed if you enter a number between 1-3. Do you want to display the new error message in all cases?

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126107489-c709c035-e9b9-49a2-8b8b-aa822e029dcb.png)


![image](https://user-images.githubusercontent.com/4592712/126107550-5ed13c23-3e0a-4a5f-acfc-ba910864e09b.png)

**Comment by sdgun** [comment]
Verified in production.


https://user-images.githubusercontent.com/4592712/126951698-63456f39-c4fa-4398-b390-3f09b0318b9c.mp4

![image](https://user-images.githubusercontent.com/4592712/126951734-1b702bdc-87fc-4a80-b826-3a21fe97b41f.png)

![image](https://user-images.githubusercontent.com/4592712/126951756-956a73f2-6623-4cbb-9caa-6a3b19e15157.png)
