### ISSUE TITLE
Hide the Full/Part Time % displays

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#363]
Hide this UI element:
![image](https://user-images.githubusercontent.com/6014049/125096030-c0dd8980-e0a2-11eb-8a6e-7baca8cfec76.png)

Until we have actual values, it is better to not display it.

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126109927-881f87e3-1447-4509-b89e-1b80e0ab4466.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126950982-83e0c432-7358-4fb4-ae34-0b54654e0688.png)
