### ISSUE TITLE
Update Labels on Rate Screen for Xeno. Add additional rate.

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#364]
Update some labels and add a new row of values:
![image](https://user-images.githubusercontent.com/6014049/125096613-50833800-e0a3-11eb-8734-1f118bdf28b0.png)

New value will require addition of that field to database/API.

**Comment by nikolay83** [comment]
@wdprice 
Does this Niche rate have smth do with the Custom role? Or is it a different concept and there will be Niche rate for regular roles?

**Comment by yoution** [comment]
@nikolay83 
which filed to show `global niche rate`? and please provide the column color?
![image](https://user-images.githubusercontent.com/3863914/125553149-097d5ee8-9f5f-4982-9d6c-46a1d5e18360.png)

**Comment by nikolay83** [comment]
1. Global Niche rate will be a new row of 3 fields (niche, rate30Niche, rate20Niche in the DB and data model). You have to add them along with 9 existing ones.
2. Please use the green like the one in the header background.

**Comment by yoution** [comment]
@nikolay83  
1. currently, the filed doesnot exist,  do I need to add them in BE, if not, just to show 0 in FE

**Comment by nikolay83** [comment]
@yoution 
yes, you need to add these 3 new fields wherever needed (API, service, data model, DB schema, ES). If they are empty, show "n/a".

**Comment by yoution** [comment]
@nikolay83 
how about `niche` filed? do it need to be the required filed when create role?
![image](https://user-images.githubusercontent.com/3863914/125609672-d1d2f584-b485-4229-a31e-f32f5ea2b07a.png)

**Comment by nikolay83** [comment]
Just all the other 9 rates, IIRC they are not required.

**Comment by wdprice** [comment]
@nikolay83 - this has nothing to do with custom role. We actually changed the term `niche` to `custom` to eliminate confusion since the term is a category of rates for harder to find skills.

The term Niche is just the name of the new row, with it's own values.

**Comment by sdgun** [comment]
@yoution can you please provide me the create role API request for the changes done in this ticket?  

![image](https://user-images.githubusercontent.com/4592712/126112823-962c7732-1c48-4582-aa42-7aef574a2410.png)

**Comment by yoution** [comment]
@sdgun   https://github.com/topcoder-platform/taas-apis/blob/dev/docs/swagger.yaml#L3344

**Comment by sdgun** [comment]
Thanks @yoution The roles created with newly added parameters are not returned in the getRole response, so not displayed in the app


https://user-images.githubusercontent.com/4592712/126116631-e905f5a7-45ea-4501-9134-1b182e377f34.mp4

**Comment by yoution** [comment]
@sdgun I will check, give me 10 minutes

**Comment by yoution** [comment]
@nikolay83 it can work locally, did you deploy it successfully?

![image](https://user-images.githubusercontent.com/3863914/126120897-680d5aa7-412b-4f2a-b35f-18439fa136cd.png)

![image](https://user-images.githubusercontent.com/3863914/126120497-864803b4-f86a-49f7-aa9d-c0d91ee6dc77.png)

**Comment by sdgun** [comment]
Created new issue https://github.com/topcoder-platform/taas-apis/issues/415, will verify the mapping of the niche rates once #415 is fixed.

**Comment by sdgun** [comment]
Verified the nice rate mapping in Dev

![image](https://user-images.githubusercontent.com/4592712/126441643-b9a9f62e-1fef-4084-a6d4-91ea335b2ab8.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126955504-07ff6d9c-c6ed-4822-9af1-b19d421de293.png)
