### ISSUE TITLE
Update Team Details Labels & add additional options under "Advanced"

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#365]
![image](https://user-images.githubusercontent.com/6014049/125097139-cc7d8000-e0a3-11eb-9708-8bf80b387a50.png)

New text to go underneath Team Details:
`Please provide a name for your Team. This could be the name of the project they will work on, the name of the team they are joining, or whatever else will make this talent request meaningful for you.`

New Advanced Options:

- Description - keep as-is
- Ref Code - simple text field, goes to ref code field on the POST to v5/projects

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126108023-6c650aa8-6ea1-4abb-b914-acdc9cbefe1e.png)

![image](https://user-images.githubusercontent.com/4592712/126108185-2efb41d5-4df9-4de8-8aa2-2a00d6829664.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126955644-65adc681-b94a-4546-9706-8485129e3b16.png)
