### ISSUE TITLE
Update Button Label

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#366]
Update the text on label from "Submit Request" to "Continue"
![image](https://user-images.githubusercontent.com/6014049/125098495-10bd5000-e0a5-11eb-9724-fdfc9d77ecc9.png)

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126103031-76514c6a-e43b-4f20-9e1f-26a3e1f442ec.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126952214-9adda80f-57ef-4724-822a-7bb35fc9179c.png)
