### ISSUE TITLE
Input Job Description Instructions

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#367]
![image](https://user-images.githubusercontent.com/6014049/125098653-364a5980-e0a5-11eb-9666-2bf0dfd4a42d.png)

Add the following block of text to the Input Job Description screen to guide the user in how to use this.

`Input a Job Description for your opening and the Topcoder Platform will identify the skills required to perform the job duties and find the best matching freelancers for your job opening. After inputting the Job Description click on the "Search" button to see the skills identified.`

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126102319-16b3ef6a-cb68-4974-99f9-e6fc69bb31e9.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126952365-5d105ce5-ea06-422f-9336-3be562d12cab.png)
