### ISSUE TITLE
Start screen label updates

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#368]
Update text in labels as follows:
![image](https://user-images.githubusercontent.com/6014049/125099249-d1433380-e0a5-11eb-96a2-5cc962bf7a1a.png)

1. `Choose a Role`
2. `Select from a list of pre-defined roles which Topcoder develops talent for. Standardized Job Descriptions and baseline skills are available for review.`
3. `Select one or more technical skills you need. Topcoder will match your requirements to our talent.`
4. `Input a Job Description and Topcoder will extract the required skills from it, then find the best matching talent for the job duties.`

**Comment by sdgun** [comment]
Verified in Dev.

@nikolay83 
The app has an additional 'which' in the point 3 text(Input skills description)

![image](https://user-images.githubusercontent.com/4592712/125921301-c2868c97-b4e9-488b-b3ef-f9d8539140c7.png)

**Comment by nikolay83** [comment]
@sdgun "which" word is removed now

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126432361-d5075cdf-1029-4379-9c53-78b42d24d531.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126953596-c120f8a6-31b5-4ee2-a15e-ae1a77485ba3.png)
