### ISSUE TITLE
Role Selection Screen Label Updates

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#369]
![image](https://user-images.githubusercontent.com/6014049/125100633-53802780-e0a7-11eb-9dff-d8fa2051beba.png)

Update "Description" to `View Description & Skills`

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126101875-26b3dda3-84d2-45fb-8cb2-a752fecdb77a.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126954965-35a91199-bb8d-4908-b1ad-43f2bd1e4d04.png)
