### ISSUE TITLE
Found Skills Modal Updates

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#371]
![image](https://user-images.githubusercontent.com/6014049/125101387-297b3500-e0a8-11eb-8d76-cfe88ae18877.png)

1. Updates "Skills" to "Identified Skills"
2. Subtitle Text update to: "Topcoder has identified the following skills referenced in your Job Description."

Update the font, sizing, and placement of the skill list.

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126101798-0f3f3177-037b-4e68-aaec-711691bce85d.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126954653-7c626647-6bc3-4404-b136-1c1ab9f06a5f.png)
