### ISSUE TITLE
Searching Screen Not Showing Full Animation

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#373]
When the "Search" screen appears, it is only showing a single frame of animation. It appears and disappears too quickly. 

The designs had 3 frames, and each should be present for ~500ms (We may need to tinker with the timing)

![image](https://user-images.githubusercontent.com/6014049/125115134-ec6b6e80-e0b8-11eb-96ea-27bdb25f30f6.png)

**Comment by sdgun** [comment]
Verified in Dev, all 3 frames are played.


https://user-images.githubusercontent.com/4592712/126101363-9f982ae7-443e-4095-9aa4-d9f276ac7f37.mp4

**Comment by wdprice** [comment]
@nikolay83 - Let's update the timing to 1500ms per frame.

FYI @sdgun

**Comment by sdgun** [comment]
Verified in production, we show each frame for around 500ms. @nikolay83 should we create a new ticket to track the above change requested by Will?

**Comment by SathyaJayabal** [comment]
@sdgun , I am closing this issue, Please track in new issue if required.
