### ISSUE TITLE
Remove Job Description Maximum

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#374]
Currently there is a 2000 character limit on job descriptions, this is too restrictive. Please remove this restriction.

**Comment by nikolay83** [comment]
Will 100K chars suffice?

**Comment by wdprice** [comment]
Yes

**Comment by sdgun** [comment]
Verified in Dev.The JD allows 100k chars.

![image](https://user-images.githubusercontent.com/4592712/125914491-b3d14629-7ac0-449b-ac6e-b061f32bbfd8.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126955917-ff01b65e-1690-488e-8797-dd76b4901930.png)
