### ISSUE TITLE
Label Update - Completeness

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#375]
Update the label from `Completeness` to `Progress`.

![image](https://user-images.githubusercontent.com/6014049/125703152-3630f378-bfa4-410b-a781-706d65e3f05f.png)

**Comment by nikolay83** [comment]
**Tech note:**
besides the label, the name of styles and functions should be update accordingly.
see https://github.com/topcoder-platform/taas-app/search?q=Completeness

**Comment by sdgun** [comment]
Verified in dev

![image](https://user-images.githubusercontent.com/4592712/126268187-07c2c7cb-a7be-4cdc-a610-668fe3db65e9.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126954456-a59f4351-f945-421f-8a77-a7262560afe8.png)
