### ISSUE TITLE
Input Skills Instructions

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#376]
Insert some text with instructions under "Input Skills"
![image](https://user-images.githubusercontent.com/6014049/125703467-676592c8-420e-4a44-a2df-4042f027e876.png)

Instructions content:
`Please select one or more essential skills you require your talent to have. Topcoder will match to profiles which contain most or all of these skills. `

**Comment by yoution** [comment]
@nikolay83 
how about this text?hide it when we have selected the skills?
![image](https://user-images.githubusercontent.com/3863914/126065585-83ea2b48-4697-413a-bd5b-793c394b7d83.png)

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/126268497-f91e56d4-8fda-4edf-b568-5efcf98b2c18.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/126954829-ad63b80d-08b1-47cc-b1f5-877be7a2ca85.png)
