### ISSUE TITLE
Restrict the duration field on Jobs to a 4 week minimum

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#383]
Task from Will:

> I know we have a new intake tool, and once it's ready for primetime I want to retire the Connect form, but in the meantime we need to do a quick update to the Connect intake form.
> We need to restrict the duration field on Jobs to a 4 week minimum.

This is similar like we did in Connect App https://github.com/appirio-tech/connect-app/issues/4417

**Comment by maxceem** [comment]
Sum up:
- If the user try to enter Duration less than 4 during [creating](https://platform.topcoder-dev.com/taas/myteams/18020/positions/new) or [editing](https://platform.topcoder-dev.com/taas/myteams/18020/positions/ff35ace5-2a29-46e6-a654-4691a729282d) Job, show an error message like in Connect App: "Please, choose at least 4 weeks"
- the same time "Create"/"Save" button should be disabled
- NOTE: don't block a user from entering Duration less than 4, the user should be able to input value and see the error. If we just block a user from entering a small value user might think these is a bug.

![image](https://user-images.githubusercontent.com/146016/125925757-a613c2ed-5957-42ba-8890-bf723414d07f.png)

**Comment by nikolay83** [comment]
@maxceem 
should we align it with https://github.com/topcoder-platform/taas-app/issues/362 ?
Must be the same ENV_VAR is a source of truth.

**Comment by maxceem** [comment]
thanks for pointing it out @nikolay83, yes, makes sense

We would create a constant and reuse it in both places.

**Comment by maxceem** [comment]
paid via https://www.topcoder.com/challenges/ae745672-4446-4f7f-ab04-2dd3e6bed69a

**Comment by sandhiyakavi** [comment]
@maxceem Currently we are able to enter floating point values to the duration field, though tooltip is displayed and Create button is hidden, the "Talent as a Service engagements have a 4 week minimum commitment." error message is also shown even if the value is already greater than 4.
![image](https://user-images.githubusercontent.com/55895538/126288492-20467ec9-4392-473e-8fe0-6ca26ddd81b0.png)
 
Other than that it is working as expected.
![image](https://user-images.githubusercontent.com/55895538/126287310-7c887cfa-f0f7-45b8-bdfa-66b027335b83.png)
![image](https://user-images.githubusercontent.com/55895538/126288232-9e9363c9-f599-4508-a79e-1668c24c22be.png)

**Comment by maxceem** [comment]
@mbaghel there appears to be one edge case, could please have a look at this. Validation should work well even if enter float number.

**Comment by mbaghel** [comment]
Added a fix #392

**Comment by maxceem** [comment]
Thanks, @mbaghel.

@sandhiyakavi the issue with decimal numbers is fixed and ready for testing on DEV.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. 

![image](https://user-images.githubusercontent.com/55895538/126314452-7f07520e-cc62-4c0d-9421-fb545ecb2c50.png)

**Comment by sandhiyakavi** [comment]
@maxceem There is an issue while editing the Job, Save button is not getting enabled in Editing Job screen if the duration field is null. Save button is getting enabled only if we edit the duration field.

Steps to Reproduce:
1. Edit the existing duration field to null.
2. click save button.
3. Again try to edit fields other than the duration field.
4. Observe the Save button is not getting enabled.
5. It gets enabled only if we enter the duration field again.

**Comment by maxceem** [comment]
Ah, nice catch @sandhiyakavi.

@mbaghel this field is optional. So we may leave it empty and should only check for minimal value if some value is entered into the field. Could you please have a look at this?

**Comment by mbaghel** [comment]
Fixed in #409. I misunderstood how this field should work.

**Comment by maxceem** [comment]
Thanks @mbaghel it works well for me now.

@sandhiyakavi this was fixed and ready for QA.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. working as expected

**Comment by sandhiyakavi** [comment]
Verified on Prod

![image](https://user-images.githubusercontent.com/55895538/126951981-704cafff-db9a-4eac-9f9c-8393a5cfb5af.png)

**Comment by maxceem** [comment]
The previous payment was incorrect and was canceled by Topcoder Support. Here is a correct payment https://www.topcoder.com/challenges/ab3b12b0-e89e-40d5-9fa5-92dde9cbb248
