### ISSUE TITLE
The role page and skills page UI doesn't utilize the whole space 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#396]
**Steps**
go to https://platform.topcoder-dev.com/taas/createnewteam
Click on select role or select skills
Check the UI

The role page and skills page UI doesn't utilize the whole space

![image](https://user-images.githubusercontent.com/4592712/126430807-80e007f9-ce8c-42c7-8f50-821d2dc505d2.png)

![image](https://user-images.githubusercontent.com/4592712/126430862-f1c956c6-b700-4e80-9901-bcfb2338a700.png)

**Comment by sdgun** [comment]
Pls note the space as been reduced tan in the previously, ex below is the current production UI

![image](https://user-images.githubusercontent.com/4592712/126431329-20641c63-6491-4a48-816c-da53862b6b03.png)

**Comment by nikolay83** [comment]
Must be connected with the logo ribbon.

**Comment by sdgun** [comment]
Verified in Dev.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129537211-1fda8249-1144-4450-b0cc-b851c1c50658.png)
