### ISSUE TITLE
Top Skill Selection & Matching

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#400]
In order to increase chances of getting viable matches, we need to make some changes on the "Skills Identified" screen that appears on the "Input Job Description" workflow.

This will also need to happen with minor label changes when the user clicks "Continue" on the "Input Skills" workflow.

This feature will require the user to select up to n skills as the most important skills:
![image](https://user-images.githubusercontent.com/6014049/126706857-f93c65ac-e2b4-452d-970d-994badaa6253.png)

n should be able to be defined at the app level. Start with n=3.

**"Input Job Description" flow labels:**
Title: "Identified Skills"
Subtitle: "Topcoder has identified the following skills referenced in your job description. Select your the n skills most important to be successful in the job. These skills will be weighted more heavily in matching."

**"Input Skills" flow labels:**
Title: "Identified Skills"
Subtitle: "You have chosen the following skills in your request. Please select your the n skills most important to be successful in the job. These skills will be weighted more heavily in matching."

On each request be sure to save which skills the user has marked as most important for future reporting and analysis.

When performing the role match, only match the marked skills against the role, skills not marked by the user should not be evaluated in the match.

**Comment by sdgun** [comment]
Verified in Dev. 
When the user selects 3 skills, the rest  of the options are disabled and display the message 'You can select up to 3 skills.'
The search is done only based on the selected skills as expected.

![image](https://user-images.githubusercontent.com/4592712/127316125-02caea79-6c73-4268-93f4-962688b73ee7.png)

**Comment by wdprice** [comment]
Sorry I made a couple typos in the copy on the page. Need to update a title and remove the word "the" from both modals. Correct copy below

"Input Job Description" flow labels:
Title: "Identified Skills"
Subtitle: "Topcoder has identified the following skills referenced in your job description. Select the n skills most important to be successful in the job. These skills will be weighted more heavily in matching."

"Input Skills" flow labels:
Title: "Selected Skills"
Subtitle: "You have chosen the following skills in your request. Please select the n skills most important to be successful in the job. These skills will be weighted more heavily in matching."

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129529800-2be74e72-d9ad-49b8-90b1-5b93c1838454.png)

![image](https://user-images.githubusercontent.com/4592712/129529816-9170c130-29a9-4c49-92f9-ff78bfcb871b.png)
