### ISSUE TITLE
Update Customer Scroll to be static

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#402]
Initial review found the customer scroll to be distracting due to the animation. 

Update this to remove the scroll, keep the "Trusted By" text, and replace with a static set of logos. 

See this page for an example of the static logos. You can use the exact same logos as shown: https://go.topcoder.com/projects/

![image](https://user-images.githubusercontent.com/6014049/126708649-f92732d5-f70a-4ae5-b516-54bf3d4e1e92.png)

**Comment by sdgun** [comment]
Verified in Dev in Windows chrome/FF & Edge.

![image](https://user-images.githubusercontent.com/4592712/127286136-73272de5-5504-488c-ba38-f9d7c7c8dc3b.png)

**Comment by SathyaJayabal** [comment]
verified on dev (safari)
<img width="1440" alt="Screenshot 2021-07-30 at 9 27 15 AM" src="https://user-images.githubusercontent.com/58783823/127598014-fbfda8ba-c9e0-4394-b6eb-c2d50c6e78fc.png">

**Comment by wdprice** [comment]
The logos seem non-responsive, while the Trusted By is. It is not centered on larger screens. Can we center the entire element and keep the positioning of "Trusted By" centered above the logos?

See below for an example of w wide view:

![image](https://user-images.githubusercontent.com/6014049/127862922-0dc4a52e-0a24-447b-bbaa-5fd9415646ff.png)

CC: @nikolay83 @sdgun

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129530941-9874948d-4ec3-4712-a6f9-b548c8b919f7.png)
