### ISSUE TITLE
Title Update on Base Page

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#404]
Update the following labels:

![image](https://user-images.githubusercontent.com/6014049/126710387-fc5b3c73-7af7-4b85-a9c8-077a737a8eb4.png)

1. "Find your Talent"
2. "Please select how you'd like to search the Topcoder community for a perfect match."

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/127285579-87d1aadd-4983-4db6-a3ab-1e5f5117fdfc.png)

**Comment by sdgun** [comment]
Overridden by changes in https://github.com/topcoder-platform/taas-app/issues/411
