### ISSUE TITLE
Email not sent for Report an issue and Request Extension for the resource booked.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#405]
Description:

Email is not getting sent for Issue Report and Request Extension for the resource booked eventhough success message is received for both.

Note: Issue report for project level is working fine and Email is getting received.

![image](https://user-images.githubusercontent.com/55895538/126776314-9541957b-a151-41a0-ab3c-13e24fa59eaf.png)

**Comment by maxceem** [comment]
@sandhiyakavi I've received emails for the user report:

![image](https://user-images.githubusercontent.com/146016/126777592-e811218d-18ca-4006-a0cb-7358c848d988.png)

and extension request 43 minutes ago:

![image](https://user-images.githubusercontent.com/146016/126777629-9375ce28-3f93-40ea-85c5-02fcfb9b862a.png)

Do you think these might be the emails you triggered?

**Comment by maxceem** [comment]
I've just got these 2 now:

![image](https://user-images.githubusercontent.com/146016/126777821-e78bae50-6d52-43bf-a915-cf9233613622.png)

**Comment by sandhiyakavi** [comment]
@maxceem yes , these were the mails sent. It's getting received. I will close this issue
