### ISSUE TITLE
Update Progress Tracker

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#406]
New updates to the Progress Tracker element: https://marvelapp.com/prototype/89c7i66/screen/81081387

**Comment by sdgun** [comment]
@nikolay83 I don't see this in Dev, please check if this is deployed. Thanks

**Comment by sdgun** [comment]
@nikolay83 According to the design 53% of completion is displayed while searching and at that time the button is shown as 'Searching'. At the 3rd step(overview of the results), the percentage should be 84%). But the app is missing this 'searching' button change and at 3rd step the progress percentage is 53%

Design:
![image](https://user-images.githubusercontent.com/4592712/128838383-adb16783-88da-4d7b-a749-ab86883dfb56.png)

App:
![image](https://user-images.githubusercontent.com/4592712/128838942-76a0d75c-6dc6-4b79-9cbf-76425b0c1d2a.png)

**Comment by sdgun** [comment]
Verified in Dev.


https://user-images.githubusercontent.com/4592712/129011226-b46a99cb-a8a7-4f55-9107-206af98e337c.mp4

**Comment by sdgun** [comment]
Verified in production.
