### ISSUE TITLE
Add All Full or Part Time selector

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#407]
Add a new column on the match made screen and the review screen before submission.

Title: Full or Part Time
Type: Picklist
Values: "Full Time - 40hr/wk", "Part Time - 30hr/wk", "Part Time - 20hr/wk"
Default Value: "Full Time - 40hr/wk"

![image](https://user-images.githubusercontent.com/6014049/126838319-295936d5-e3ed-4fa8-b433-05f668f15c04.png)

**Comment by sdgun** [comment]
@nikolay83 When a part time option is selected from 'Full or Part Time' drop down, TAAS Team still shows the workload as Full-time. Just checking if this value has anything to with the value displayed in the job details of the selected position in the Team.

![image](https://user-images.githubusercontent.com/4592712/127297140-998846bb-d01a-4ef7-a119-1456781cae81.png)

**Comment by cagdas001** [comment]
The workload is another field:
![chrome_2021-07-28_12-19-09](https://user-images.githubusercontent.com/28513447/127310957-419fc658-2a28-4c91-ad1f-b721f3ec75ad.png)

The new field gets reflected in the `hoursPerWeek` of jobs.
![chrome_2021-07-28_13-53-02](https://user-images.githubusercontent.com/28513447/127310974-808295b6-40d0-4ebf-b12e-bb2f94d41d6e.png)

**Comment by sdgun** [comment]
Thanks @cagdas001 I guess there is no direct mapping here with any visible field in the Taas app.

Verified in Dev in Windows chrome/FF & Edge.

![image](https://user-images.githubusercontent.com/4592712/127283713-3d7b8feb-1668-4090-8be7-1b26da899c7c.png)

**Comment by cagdas001** [comment]
> I guess there is no direct mapping here with any visible field in the Taas app.

Yeah, I think so. Maybe we should also reflect `hoursPerWeek` (i.e. the full or part-time selection) somewhere in the UI. And we can automatically set the `workload` based on this selection as well. It's clear a `full-time` workload is against the `Part Time - 20hr/wk` selection

If the team comes up with a decision on this, I'll follow up on this issue

**Comment by wdprice** [comment]
I support the addition of the field to the TaaS App UI, but don't view it as a blocker for this release.

Please post the details of the database field and proposed logic and we'll add something to the backlog.

**Comment by cagdas001** [comment]
> Please post the details of the database field and proposed logic and we'll add something to the backlog.


**DB**

`hours_per_week` column of the `jobs` table

**Backend**

`hoursPerWeek` property of jobs

**Frontend**

As above: `hoursPerWeek` property of jobs. You should be able to simply access with `job.hoursPerWeek`.

You'll get an integer value from the backend, denoting the hours per week. So, the value mapping should/will be

| Selection | Value |
| ---- | ---- |
| Full Time - 40hr/wk | 40 |
| Part Time - 30hr/wk | 30 |
| Part Time - 20hr/wk | 20 |

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129535870-7e844fa8-6611-4c54-b07a-c3f71adba70b.png)

![image](https://user-images.githubusercontent.com/4592712/129535920-a869b989-84d7-424d-95c8-7df7ec5eb71f.png)
