### ISSUE TITLE
Horizontal scroll bar is enabled

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#410]
Horizontal scroll bar is enabled on all pages

![image](https://user-images.githubusercontent.com/4592712/126953040-e9c989d9-3a0d-4f42-972e-2561426cb5d5.png)

**Comment by nikolay83** [comment]
@sdgun 
I can't reproduce it even if I zoom in/out (Safari, Chrome)

**Comment by sdgun** [comment]
@nikolay83 Yes, after the latest deployment done today it is fixed in Dev.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129531702-4ee77949-b30d-4edb-8200-5e3409f728e5.png)
