### ISSUE TITLE
Update Design on Start Screen

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#411]
New start screen design: https://marvelapp.com/prototype/89c7i66/screen/81081397

Use the text and labels inside this document. Buttons still take you to the path as they did in the previous version.

**Comment by wdprice** [comment]
@nikolay83 - Do we have an estimate on this one?

**Comment by sdgun** [comment]
Verified in Dev

![image](https://user-images.githubusercontent.com/4592712/127962026-0d7ebed8-0399-4ee3-835c-2dbe3bc52ea2.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129531485-70428215-0b11-4941-a08a-74a08e2726b5.png)
