### ISSUE TITLE
Update Match Found Screen

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#412]
Update to the Successful match screen: https://marvelapp.com/prototype/89c7i66/screen/81081386

Note: while the updated design does not contain this element, please keep it at the bottom of the element, along witht he full time / part time feature:
![image](https://user-images.githubusercontent.com/6014049/127060188-2ed7d4d3-30e0-4241-a388-330ce7ab3a66.png)

**Comment by cagdas001** [comment]
@nikolay83 Does this apply only to the Skills and Job Description results? The Role page doesn't involve a skill search & matching process.

**Comment by nikolay83** [comment]
@cagdas001 
yes, correct.

**Comment by yoution** [comment]
@nikolay83 can you give me some test data?
I can not understand the requirement very clear
if I input `nginx` and `.net` it return 
![image](https://user-images.githubusercontent.com/3863914/127844371-8034b2e1-dc55-4662-8c40-5e74846fc4c1.png)

but the BE not return which skill is matched? so I need to change the BE?

if I input `nginx` and `javascript` it return no matched, why?

**Comment by yoution** [comment]
I know, we do not to modify the BE api

**Comment by yoution** [comment]
@nikolay83  how about these ones?
the role has these skills, but not search by the request?
![image](https://user-images.githubusercontent.com/3863914/127851017-de951fe8-46ad-4cd8-a038-221a9f732e4e.png)

**Comment by yoution** [comment]
@nikolay83  is there any skill api, I can use to get skill id by skillname, in order to show to skill image , we use get the skill id

**Comment by nikolay83** [comment]
1. Yes, it returns the number of skills matched in the role found.
2. Yes, you have to adjust the back-end to return the skills matched (and requested but unmatched if technically necessary, up to you). Let me know it makes the dev more expensive.
3. For  nginx and javascript probably there is no role matching both skills at prod (or whatever environment you have). Or is there?

**Comment by sdgun** [comment]
@nikolay83 
1. The members matched section is auto adjusted when there are more than 4-5 skills. 
2. The description doesn't match with the design

App:
![image](https://user-images.githubusercontent.com/4592712/127966459-7ee51f3b-bd20-4723-8063-4725f6d7aacf.png)

Design:
![image](https://user-images.githubusercontent.com/4592712/127966816-f3e4104a-7771-4f6a-808a-ff2e5e3dd646.png)

**Comment by wdprice** [comment]
The skills matched should show the skills the customer identified, not the skills on the role. So if a Customer inputs: "React.js, Node.js, .NET, SCSS" , then those 4 should be shown, with React, Node and SCSS highlighted.

Always put the customers top N skills on the top of the list.

**Comment by yoution** [comment]
@wdprice @nikolay83  Could you please explain elaborately，
if we input `skillA, skilB, skillC, skillD`, then BE get a Role, which has `skill A SkillB, skillE`, so we should show `SKillA, SkillB` highlight, 
and disable `SkillC, SkillD`

**Comment by wdprice** [comment]
You are correct @yoution. By disable, I assume you are saying it will be displayed, but "grayed out"

**Comment by sdgun** [comment]
@yoution @wdprice This scenario is something that doesn't happen according to the current implementation, because when a search is made for `skillA, skilB, skillC, skillD` we never return a role which doesn't have all those skills. In such scenarios we return custom role.


> @wdprice @nikolay83 Could you please explain elaborately，
> if we input `skillA, skilB, skillC, skillD`, then BE get a Role, which has `skill A SkillB, skillE`, so we should show `SKillA, SkillB` highlight,
> and disable `SkillC, SkillD`

**Comment by yoution** [comment]
@sdgun there is a `rate`, if matched rate below that value, will return custom role, current rate maybe `0.7`

**Comment by sdgun** [comment]
@yoution So we only allow user to select up to 3 skills max, with that this scenario cannot happen right?

**Comment by yoution** [comment]
@sdgun no, if BE config the `match-rate` is 0.7, if you input `skillA`,`skillB`,`skillC`,`skillD`, but the role has `skillA`, `skillB`, `skillC`, so current the matching-rate is 3/4 = 0.75, so the vaule is more than 0.7, will return role, if the role only has `skillA`, `skillB`,
the matching-rate is 2/4 = 0.5, so current value is less than 0.7, so will return custom role

**Comment by sdgun** [comment]
@yoution since we only allow max 3 skills from UI, the max value rate can go is 0.66(ex- looking for skilla, skillb, skillc and role has only 2 of them, so 2/3) which is less than 0.7 and returns custom role. So this grayed out skills we cannot match with current UI restriction?

**Comment by wdprice** [comment]
@sdgun - we can update the match threshold pretty easily - I am OK with updating to .66 so we can get matches on 2 out of 3.

**Comment by wdprice** [comment]
@nikolay83 @yoution - one thing I noticed in my recent tests - we are still showing the old match screen when the user taks the "Select a Role" path.

For that path only can we use the new screen and show all the skills related to the Role? Current functionality for job description and input skills is great, just the role path would be affected by this request.

**Comment by wdprice** [comment]
@nikolay83 - did you see the above comment? Want to get this update in before we launch.

**Comment by sdgun** [comment]
Verified the UI issue of members matched section shrinking. but didn't verify the skills disabling since match rate is 7. Not closing the issue since the above issue reported by Will

**Comment by sdgun** [comment]
Removing Ready for Dev QA label since https://github.com/topcoder-platform/taas-app/issues/412#issuecomment-894264477 is pending

**Comment by nikolay83** [comment]
@yoution 
Will's request was : for "Select Roles" path only can we use the new screen and show all the skills related to the Role.

**Comment by yoution** [comment]
ok, I will add it

**Comment by sdgun** [comment]
Verified both disable skills with match rate .66 and the role flow showing all skills highlighted.

![image](https://user-images.githubusercontent.com/4592712/129009575-23da425f-9509-4f1d-a99a-2ded91e0fa71.png)

![image](https://user-images.githubusercontent.com/4592712/129009698-10d27a95-c634-4bb1-b312-b2835b41d060.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129542947-24df4ba9-028b-47ab-8af7-19d6efb211ba.png)
