### ISSUE TITLE
Add a static card at the end of the role list.

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#416]
![image](https://user-images.githubusercontent.com/6014049/127668228-b000fa2e-28a2-4f9d-9394-b0cdcfabd3b6.png)

Add a static card which will always appear at the end of the list.

Card Title: "Don't see what you're looking for?"
Button: "Describe your needs"

**Comment by nikolay83** [comment]
@wdprice 
does it lead to the JD flow when clicked?

**Comment by wdprice** [comment]
Yes sir!

**Comment by nikolay83** [comment]
@wdprice 
Any icon for this card?

**Comment by wdprice** [comment]
Just the text would be fine, as long as fonts match the rest of the app. I
think a slightly different look would be good. Can you share a screengrab
of how it's coming together?

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/127961483-fcdbb54c-22ca-4b55-a04a-d5142ef4c63e.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129531586-0541178a-2db2-4454-ad4f-bda901956fba.png)
