### ISSUE TITLE
UI issue in the successfully deleted message when deleting a role from Taas admin

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#420]
**Steps**
- Go to TAAS Admin >> Roles
- Delete/add/update a role
- Check the message

![image](https://user-images.githubusercontent.com/4592712/127975496-2890c529-6216-4697-921a-4960b0a7ea12.png)

![image](https://user-images.githubusercontent.com/4592712/127975909-63a69518-fa3c-4fa3-81da-ee847648d201.png)

**Comment by cagdas001** [comment]
@sdgun I cannot reproduce this

![2021-08-03_22-27-15](https://user-images.githubusercontent.com/28513447/128074492-d2ca4fa0-4989-408c-ae3f-ed3835fe8e15.png)

Tried to play with screen size as well, but it still works on my side

**Comment by sdgun** [comment]
@cagdas001 It worked for me too after clearing cache. So closing the issue.
