### ISSUE TITLE
When entering symbols/non-existent skills on the skills field, the symbol/value is added to the skill list

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#426]
**Steps**

Go to TAAS Admin >> Roles
Click create new role button
Click on skills field and enter 'C#' or a non-existent skill (ex- 'abc')

You will not see C# in the skill suggestions drop down, but it is being added to the skill list. And No suggestions will be displayed until you click on some fields a few times

Note: Skills like C#, F# should be displayed in the suggestions in this case. But the suggestions start showing only after at least 3 letters are entered in the skills field

https://user-images.githubusercontent.com/4592712/128125651-cd8237ce-0020-416c-88e4-1b4f3f353c77.mp4

**Comment by sdgun** [comment]
verified in Dev, this issue is fixed.

**Comment by lakshmiathreya** [comment]
Verified in Prod. However, the error message needs to be improved. @sdgun pls link the Issue for that here.

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-08-16 at 4 04 45 PM" src="https://user-images.githubusercontent.com/51733042/129551345-f01cd1f0-02a2-43a1-9727-5cf4641a2c8a.png">

**Comment by sdgun** [comment]
> Verified in Prod. However, the error message needs to be improved. @sdgun pls link the Issue for that here.

Created issue https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/102
