### ISSUE TITLE
Deposit Confirmation Screen Display Issues

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#434]
![image](https://user-images.githubusercontent.com/6014049/128772951-dfb4fab5-f9f9-432b-951a-8f7855803f86.png)

Custom role is not bringing a number to this screen - nothing is included in the total deposit for that role.

If no role image is related to the role, we need it to display the default role image.

**Comment by arpitchaudhari** [comment]
What are the steps to recreate this issue?

**Comment by nikolay83** [comment]
@arpitchaudhari 
may be the below will give you more context:
https://github.com/topcoder-platform/taas-apis/blob/cdfd20c84900437e2f54499213a69c2b54cea892/src/services/TeamService.js#L812

https://github.com/topcoder-platform/taas-apis/blob/fbacd801f67d523b3bb13c467ce42a6fa46a71af/migrations/2021-07-01-role-insert-custom-role.js

**Comment by wdprice** [comment]
Honestly, easiest way to get a custom role is to choose a single skill in the "Input Skills" flow. Choose something that isn't a part of any role and search on it. For example, I added only a single skill: `Amazon Alexa` and searched.

This got me to the custom role screen. Then click on "Continue this Search" to add the custom role to your cart and proceed to the deposit.

**Comment by arpitchaudhari** [comment]
Fixed #441

**Comment by sdgun** [comment]
Not sure if there will be roles without rate values, but if there is no rate set, NaN is still displayed on the checkout page

![image](https://user-images.githubusercontent.com/4592712/128988988-431ab4e7-d559-47ca-9f7b-7fba63155f95.png)

**Comment by wdprice** [comment]
We shouldn't display a role without a global rate ever.

**Comment by nikolay83** [comment]
@wdprice @sdgun 
sounds like a new requirement, so I've created a separate issue: https://github.com/topcoder-platform/taas-app/issues/462 and changed the status to Ready for QA here.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129536877-3f78c09b-4c06-4457-b23f-6f287d826fde.png)
