### ISSUE TITLE
UI Issues in checkout page on windows 10

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#440]
**Steps**
Go to checkout page

Observe the below UI issues:
the data on the right side & left side are too close to the edge

Design:
![image](https://user-images.githubusercontent.com/4592712/128844108-6f92d7c3-fac1-4ab1-954c-4f69057936ee.png)

Implementation:
![image](https://user-images.githubusercontent.com/4592712/128995345-58b97170-8495-46b3-89df-33b460383231.png)

Windows 10
Chrome 92.0.4515.131
Firefox 90.0.2
Edge

**Comment by arpitchaudhari** [comment]
Is this happening in all three browsers in windows 10?

**Comment by sdgun** [comment]
@arpitchaudhari Yes

**Comment by sdgun** [comment]
@arpitchaudhari I found in the latest design requirements, the page title is 'Confirm your request', so please do not change it. I am modifying the description now.

**Comment by sdgun** [comment]
Verified in Dev(all mentioned browsers), fixed.

![image](https://user-images.githubusercontent.com/4592712/129197665-96f6e5ed-4f89-488f-8955-b418defca20c.png)

**Comment by sdgun** [comment]
Verified in prod
