### ISSUE TITLE
Empty page when opening the checkout page with a custom role in the role list

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#441]
**Steps**
Continue to checkout page with a custom role

opens up a white page and there is a console error

![bandicam 2021-08-10 15-13-00-453](https://user-images.githubusercontent.com/4592712/128845951-76963015-3af1-4e6e-9cef-68325f9e6406.jpg)

![image](https://user-images.githubusercontent.com/4592712/128955319-9f18510c-c1ce-4cfd-aa36-d45add74e5af.png)

**Comment by nikolay83** [comment]
@sdgun 
might be a cache issue. I used to have, but in Incognito mode it works fine.

**Comment by nikolay83** [comment]
This is what I see in the console when there is a custom role.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/3432907/128913117-10c69bf3-5088-4a2c-9d9a-e19f2278e549.png">

**Comment by arpitchaudhari** [comment]
Issue Fixed

<img width="1899" alt="Screenshot 2021-08-11 at 11 02 09 AM" src="https://user-images.githubusercontent.com/29978858/128975723-e1326155-4886-4476-9430-828c3873d854.png">

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/129008967-fe83deca-f4b4-435c-8cf6-9b6cf76e1fa3.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129537865-c1c42919-949a-4dae-a4b7-f01603c0f656.png)
