### ISSUE TITLE
Resource count and weeks are always 1 & 4 on the checkout page when those values are set from the Customize your team page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#442]
**Steps**
Go to checkout page by selecting a role and by increasing the number of resources and duration

Resource count and weeks are always 1 & 4 on the checkout page irrespective of what user selected

![image](https://user-images.githubusercontent.com/4592712/128849662-93e28cda-02dd-4a55-aec2-1a6988188e5d.png)

**Comment by sdgun** [comment]
Noticed the correct week number and resource count being displayed once the user signs in at the continue, but not when the user already signs in is proceeding to the checkout page

**Comment by nikolay83** [comment]
@sdgun 
but the user is mandated to sign in at the continue. She can't proceed anonymous.

**Comment by sdgun** [comment]
@nikolay83 yes, after the anonymous user logs in the data is correct. But when already logged in user continues to checkout page the data is incorrect

**Comment by sdgun** [comment]
@nikolay83 I tested this with TCConnCopilot

**Comment by sdgun** [comment]
@nikolay83 The counts are not getting updated when modifying them from the Team details page


https://user-images.githubusercontent.com/4592712/128973918-733ec4a2-4ec3-4761-b3d4-7f720061211b.mp4

**Comment by arpitchaudhari** [comment]
Issue Resolved

Uploading Screen Recording 2021-08-12 at 11.52.21 AM.mov…

**Comment by arpitchaudhari** [comment]
Issue Resolved

https://user-images.githubusercontent.com/29978858/129148771-9691933b-cbe7-41cd-925d-9105fea65b37.mov

**Comment by sdgun** [comment]
Verified in Dev, fixed.


https://user-images.githubusercontent.com/4592712/129197317-2e6fbd99-574c-49e2-a258-7416b15a85af.mp4

**Comment by sdgun** [comment]
Verified in prod
