### ISSUE TITLE
The amount calculation is incorrect 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#443]
**Steps**
Log in from an external user 
select a role/skill and continue 
On the Team details page, increase the number of resources to more than 1
go to checkout page and see the amounts

The Charge should be for the first week for the request using the global rate, and this should be multiplied based on the number of resources. The total deposit should be the total charges for the roles in the left side

But the implementation only shows the global rate irrespective of the number of resources(resource count is always 1 issue https://github.com/topcoder-platform/taas-app/issues/442)  and the total deposit is calculated by multiplying the global rate of each role by 4(weeks)

Also when the user selects 30 hr/week or 20 hr/week, it still takes the 40 hr/week rate in the calculation

https://user-images.githubusercontent.com/4592712/128850138-f639fd23-c0ff-4162-b236-0c52db2ce2b2.mp4

@wdprice pls correct me if I am wrong

**Comment by nikolay83** [comment]
@sdgun works fine for me. Can you recheck please?

**Comment by sdgun** [comment]
@nikolay83 Are we on the same page here? I rechecked it and I can still see the same issues. For ex I select .net engineer and I see role rate 50 and total deposit 200, which should be 50 since 1 role X 1 week. 

![image](https://user-images.githubusercontent.com/4592712/128855957-00e64bff-6ddd-4a62-ba90-a9351923cf2b.png)

**Comment by nikolay83** [comment]
@arpitchaudhari
The amount in the summary is calculated correctly.
However the total deposit is wrong: 
AS IS - the amounts from summary multipied by number of weeks
TO BE: just the total of amounts from summary. I.e. we charge only 1 week worth deposit.

**Comment by arpitchaudhari** [comment]
Issue Resolved.

![Image 11-08-21 at 9 04 AM](https://user-images.githubusercontent.com/29978858/128966294-6658cf9b-2046-4b50-9400-fa58ff1fbf9f.jpg)

**Comment by sdgun** [comment]
Verified in Dev, the amounts are correctly calculated.

![image](https://user-images.githubusercontent.com/4592712/128997818-100c12da-f020-409f-ad79-d4d6d6c6ddd9.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129537744-5f2656c2-434b-46be-8ee5-23d374311473.png)
