### ISSUE TITLE
Typo in the 'Name of the card' and 'country or region' validation

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#444]
**Steps**
Proceed to checkout page 
Click on Name of the card field and click outside
Check the validation

Validation shown 'This field is require.' needs to be corrected

The same with the country or region

![image](https://user-images.githubusercontent.com/4592712/128862168-9f04636a-d160-4ad8-85ee-e16d5663125c.png)

**Comment by arpitchaudhari** [comment]
Issue Resolved.

<img width="955" alt="Screenshot 2021-08-11 at 12 15 54 PM" src="https://user-images.githubusercontent.com/29978858/128982303-36b1cc1b-9259-4eeb-ada6-e956a08605f1.png">

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129537564-16d07c92-8d5d-4da3-8efa-dda522cc4871.png)
