### ISSUE TITLE
For internal users who signs in at the submission, the checkout page is displayed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#445]
**Steps**
Go to intake app (not logged in)
Select a role and proceed(you will be prompted to sign in)
Sign in and continue(sign in as Tcconncopilot user)
Continue submitting the request

You will be redirected to checkout payment, but this user is a internal user

https://user-images.githubusercontent.com/4592712/128865197-88213f82-0b91-4d51-85ab-7cc13e3162d7.mp4

**Comment by nikolay83** [comment]
@arpitchaudhari
After we've deployed the Auth valuation I see the blank page after I submit a team.
To Be: I must see Teams page with a newly added team.

**Comment by arpitchaudhari** [comment]
TCConnCopilot is defined as external user. 

Can you verify whether this user is external or internal in Auth0?

<img width="1900" alt="Screenshot 2021-08-11 at 8 41 51 AM" src="https://user-images.githubusercontent.com/29978858/128964149-484d063f-616c-41a6-8255-17a449c2bf0d.png">

**Comment by sdgun** [comment]
@arpitchaudhari 

![image](https://user-images.githubusercontent.com/4592712/128966890-3b2c729e-0961-47fa-a19f-4bc5c4783361.png)

**Comment by arpitchaudhari** [comment]
Don't goto checkout page. The data is deleted. Check before checkout page.

**Comment by sdgun** [comment]
@arpitchaudhari 

![image](https://user-images.githubusercontent.com/4592712/128969241-9c099ff1-1ae4-418b-9356-4aa147d5b623.png)

**Comment by arpitchaudhari** [comment]
@nikolay83 

I have found out that by default, app is considering member is external. When the internal member login in between the flow, the auth logic is not updating the `isExternalMember`. Due to this, checkout page is shown.

**Comment by nikolay83** [comment]
@arpitchaudhari 
Yes, that's correct logic.
Before displaying the Checkout page, you must check (by member ID) if the user is external or not. Use the same service that the Auth logic does.

**Comment by sdgun** [comment]
Verified in Dev, fixed.

**Comment by sdgun** [comment]
Verified in prod
