### ISSUE TITLE
CreatePayment API is called multiple times if the Pay button is clicked multiple times

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#446]
**Steps**
Proceed to checkout page
Fill in the correct card infor
Click Pay multiple times

CreatePayment API is called for each click, better to disable the button after one click

![image](https://user-images.githubusercontent.com/4592712/128891145-424d365a-4e5b-4f19-837c-bdb96ceb9db7.png)

**Comment by nikolay83** [comment]
@sdgun 
And does it lead to multiple payment transactions?

**Comment by arpitchaudhari** [comment]
Issue Resolved.

https://user-images.githubusercontent.com/29978858/128964858-64bc1073-a523-4ce9-92c1-1f934f1d16fa.mov

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

https://user-images.githubusercontent.com/4592712/128977764-8bd4f4f8-5873-4d46-880e-91ffe4fa64cd.mp4

**Comment by sdgun** [comment]
Verified in production.


https://user-images.githubusercontent.com/4592712/129546482-f8be4d13-314e-4eb0-ae61-5eac33c919b5.mp4
