### ISSUE TITLE
Empty page when proceeding from JD page and from Skills page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#449]
**Steps**
**Scenario 1**
Enter below description in JD page and continue by selecting all the skills or one skill on the pop up
'database java'

Shows an empty page

https://user-images.githubusercontent.com/4592712/128974580-02ab16bf-cc92-4098-be29-46c9ee00f8a4.mp4

**Scenario 2**
Select some skills which are existing in a selected roles and select 3 of them
continue

https://user-images.githubusercontent.com/4592712/128976505-608dbdbc-319d-4503-809a-20d3ed1a2f37.mp4

**Comment by nikolay83** [comment]
@sdgun any chance you tested it during deployment?
Both JD and Skills flow work fine for me, leading to either normal or custom role found page.

**Comment by sdgun** [comment]
@nikolay83 I checked these again and seeing the issue still. It happens in the mentioned scenarios and also when skills searched (skills page or JD):
docker aws database
NGINX Photoshop Docker database

Mostly when database skill is there. Please check with the exact inputs given in this issue. 

I also double checked this in prod and this issue is not there.

**Comment by arpitchaudhari** [comment]
Try with filling job title. 

![Screenshot 2021-08-11 at 5 43 38 PM](https://user-images.githubusercontent.com/29978858/129026716-dba85134-f772-4375-a452-aed323fdcebf.png)

**Comment by nikolay83** [comment]
@arpitchaudhari 
1. The job title is not mandatory, so the flow must go on even if it's empty
2. I tried with the job title, it's still an empty page.

**Comment by cagdas001** [comment]
@sdgun could you please re-check if it's still an issue? It's working on my side (with the database skill added)

**Comment by sdgun** [comment]
@cagdas001 This is not reproducible to me too now. I will close it after some more testing if it works.

**Comment by sdgun** [comment]
Verified in prod
