### ISSUE TITLE
Full time/part time availability is incorrectly shown on the checkout page if the user select a part time option and then change it to full time on the profile matching page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#455]
**Steps**
Proceed to matching profile found page in any flow
Select a part time option and then select full time option again
continue 
on the team details page enter team name and continue

Shows Part-Time availability under the position

https://user-images.githubusercontent.com/4592712/128993521-6276a341-3157-4768-b891-feb5475137f1.mp4

**Comment by sdgun** [comment]
@yoution This issue is not fixed, now it always show part time on the checkout page.

https://user-images.githubusercontent.com/4592712/129142700-ff3725df-5e72-48c1-99c1-b3d35dfb66f3.mp4

**Comment by yoution** [comment]
I will check

**Comment by sdgun** [comment]
Verified in Dev, fixed.

**Comment by sdgun** [comment]
Verified in prod
