### ISSUE TITLE
Confirmation Popup after Payment

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#459]

**Comment by nikolay83** [comment]
Do you mean payment confirmation, not the Commitment popup? Because if the latter, it'll be a bit impertinent to ask for commitment after the client has paid the deposit :)

**Comment by yoution** [comment]
@wdprice please confirm, and what will be showed in the popup?

**Comment by nikolay83** [comment]
@yoution 
For now just uncomment the existing popup. Will may be offline for the next 3-4 hours.

**Comment by sdgun** [comment]
@nikolay83 Is this issue a duplicate of https://github.com/topcoder-platform/taas-app/issues/461?

**Comment by wdprice** [comment]
Dupe ticket. Closing.
