### ISSUE TITLE
Filter by Team, not taking space into consideration

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#46]
Refer https://github.com/topcoder-platform/taas-app/issues/37#issuecomment-755873866

**Comment by maxceem** [comment]
hi @sandhiyakavi

we've fixed this issue as per discussion on https://github.com/topcoder-platform/tc-project-service/issues/645

Could you please test filtering by the team again, and tell if you get the expected results now.

The downside of the current fix, that we cannot find projects by partial words for example searching by `mark` would not return teams with `markdown` anymore, we would have to enter the word fully `markdown`.

How do you think is this new approach better than what we had before? Do you see any issues with the new approach?

**Comment by sandhiyakavi** [comment]
@maxceem Yes, This approach is better. I am able to search Taas team based on their full name as well as using keyword.

![image](https://user-images.githubusercontent.com/55895538/111733727-e65c4280-88bb-11eb-8f66-e451c87085e2.png)
![image](https://user-images.githubusercontent.com/55895538/111733752-f542f500-88bb-11eb-936b-07a8f8dea513.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/112827459-55f6dc80-90c9-11eb-963a-a5f56eae5aa1.png)
![image](https://user-images.githubusercontent.com/55895538/112827500-63ac6200-90c9-11eb-8c02-8167a1363012.png)
