### ISSUE TITLE
Insert Chatbot Code Snippet

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#460]
The following code needs to be added for a chatbot to appear on the page:

`<script type="text/javascript">
    window._chatlio = window._chatlio||[];
    !function(){ var t=document.getElementById("chatlio-widget-embed");if(t&&window.ChatlioReact&&_chatlio.init)return void _chatlio.init(t,ChatlioReact);for(var e=function(t){return function(){_chatlio.push([t].concat(arguments)) }},i=["configure","identify","track","show","hide","isShown","isOnline", "page", "open", "showOrHide"],a=0;a<i.length;a++)_chatlio[i[a]]||(_chatlio[i[a]]=e(i[a]));var n=document.createElement("script"),c=document.getElementsByTagName("script")[0];n.id="chatlio-widget-embed",n.src="https://w.chatlio.com/w.chatlio-widget.js",n.async=!0,n.setAttribute("data-embed-version","2.3");
       n.setAttribute('data-widget-id','df6d6a4d-7193-4eaf-648b-4569f0e6b262');
       c.parentNode.insertBefore(n,c);
    }();
</script>`

**Comment by wdprice** [comment]
All pages @nikolay83

**Comment by sdgun** [comment]
Verified in Dev, Chatbot is there on all pages for logged in or anonymous users except on checkout page. Observed the below:

1. On the Chatbot UI, the fields are not clearly visible
2. After sending some feedback/query, it doesn't show the form again when click on chatbot(shows the message 'Thanks for your...', until the page is refreshed

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129528756-f07df5cc-337e-416b-913b-014a2d7c930a.png)
