### ISSUE TITLE
Redirect & Popup Edit after successful credit card transaction

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#461]
Upon completion successful of a payment, the user currently gets a popup modal say "Creating Team" and then is directed to "My Teams".

Replace the Popup Modal with the design linked here:
https://marvelapp.com/prototype/89c7i66/screen/81180793

Use the following text:
Title: WE'VE RECEIVED YOUR DEPOSIT
Subtitle:  Thanks for trusting us with your talent needs! You will be redirected to your Team page where you can review candidates, schedule interviews, and lock in your selections.
Button Label: TAKE ME TO MY TEAM

Redirect after 10 seconds to the Team page: platform.topcoder.com/taas/myteams/:projectid

**Comment by wdprice** [comment]
@nikolay83 - this is a late breaking bit of feedback. Let me know if this will take more than one day to deliver and we may need to push it back to a later release.

**Comment by sdgun** [comment]
Verification is blocked due to https://github.com/topcoder-platform/taas-app/issues/475

**Comment by sdgun** [comment]
Adding Blocked label since https://github.com/topcoder-platform/taas-app/issues/475 is still failing

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/129233002-9482c803-2690-4ac2-b334-f7c11304bb17.png)

**Comment by sdgun** [comment]
Verified in production.


https://user-images.githubusercontent.com/4592712/129546248-4654ef38-4af0-480b-9191-697c2973cd79.mp4
