### ISSUE TITLE
Don't display a role without a global rate

### ISSUE THREAD

**Issue by nikolay83** [topcoder-platform/taas-app#462]
Is there is a role in the database that has a global rate (the full-time one) empty or null, then this role shouldn't 
- be displayed in the Roles list
- be found when searching via Skills or Job Description flow

**Comment by yoution** [comment]
@nikolay83 please review
https://github.com/topcoder-platform/taas-apis/pull/479
https://github.com/topcoder-platform/taas-app/issues/462

**Comment by sdgun** [comment]
@nikolay83 @wdprice Should this only be applied to Global rate (full time)? In my comment on issue [434](https://github.com/topcoder-platform/taas-app/issues/434#issuecomment-896575895), it's missing part time global rate which cause the amount to be displayed as 'NaN'

**Comment by wdprice** [comment]
Ah OK, so we need Global Part time rates added? That is easy enough to fix - it is a data issue.

**Comment by nikolay83** [comment]
@yoution 
2 extra requirements:
1) global20 and global30 rates also shouldn't be empty or null. So display only the roles that have all 3 global rates not empty.
2) display the part-time rate for the custom role (the full-time rate is in config) as
30 hour rate = Global Rate * .75
20 hour rate = Global Rate * .5

**Comment by yoution** [comment]
@nikolay83 `the full-time rate is in config`, does it already exist?I can not found the config value

**Comment by sdgun** [comment]
@yoution The rate is set incorrectly. For 30 hrs it should be Global Rate * .75 and for 20hrs Global Rate * .5, but it is vice versa now.


https://user-images.githubusercontent.com/4592712/129312002-b73fcc32-0c35-44e0-bf3d-1735dcb0fb7d.mp4

**Comment by yoution** [comment]
@sdgun I will check

**Comment by nikolay83** [comment]
@yoution 
customRole.rates[0].rate20Global = customRole.rates[0].global * 0.75
  customRole.rates[0].rate30Global = customRole.rates[0].global * 0.5

Should be vice versa, 0.75 for 30 hours

**Comment by yoution** [comment]
@nikolay83 please review

**Comment by sdgun** [comment]
Verified in Dev, fixed.

**Comment by sdgun** [comment]
Verified in production.
