### ISSUE TITLE
The pay amounts are all shown as 'NaN' on checkout page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#466]
**Steps**
Go to checkout page by selecting a few roles which have global rates

The pay amounts are not NaN

![image](https://user-images.githubusercontent.com/4592712/129142163-c5303e59-0c55-4810-9306-226cee09365a.png)

**Comment by yoution** [comment]
@sdgun  maybe can not reproduce
on the other hand, can you tell me how can I go to the payment page? when I click `submit` button, it will go to `taas app` list

**Comment by sdgun** [comment]
@yoution You have to log in from an external user to see payment page. I also do not see this issue now.

**Comment by yoution** [comment]
fixed with https://github.com/topcoder-platform/taas-app/issues/455

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/129186804-161944e9-2110-4c45-8b6c-8517caab379e.png)
