### ISSUE TITLE
Payment page gets stuck, 'null' is appended to the url instead of create-taas-payment

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#475]
**Steps**
Select a role/skill or enter JD and proceed to checkout page from an external user
Stay for a few seconds on the page

The Url shows null and page is stuck. Unable to proceed with the payment

https://user-images.githubusercontent.com/4592712/129190700-1de476ef-5c89-4588-a4d8-39189ababa7b.mp4

**Comment by sdgun** [comment]
Sometimes the payment page goes blank and shows the below:

![image](https://user-images.githubusercontent.com/4592712/129195134-dbb78ba5-8580-4636-b792-d0b14e98bed9.png)

**Comment by arpitchaudhari** [comment]
Fixed

**Comment by wdprice** [comment]
![image](https://user-images.githubusercontent.com/6014049/129212766-b635a49c-1d22-4be7-abab-b80a2b8e12a5.png)

This is happening after a few seconds on the checkout page with no interaction from the user.

**Comment by arpitchaudhari** [comment]
Its working.

https://user-images.githubusercontent.com/29978858/129225187-7f370bf3-1881-4074-983d-3faa4b7a1ac7.mov

**Comment by nikolay83** [comment]
@wdprice @sdgun 
I can't reproduce it either, works fine for me on dev, both with the custom and/or normal roles, both skills and roles flow.

**Comment by arpitchaudhari** [comment]
Same here. I am also not able to reproduce it.

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.


https://user-images.githubusercontent.com/4592712/129232507-b1bc89b7-9cc0-4736-9ab7-083d6d6aa153.mp4

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129545450-e797b03b-650d-4b1a-bb41-0612501fc902.png)
