### ISSUE TITLE
The title entered by the user in JD page is not displayed in the next page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#481]
Steps
Go to JD page
Enter a job description
Enter a job title
Click search and continue to the next page

Expected: If the user has entered a title, it should be displayed on the next page instead of the text "WHAT HAPPENS NEXT"

Actual: "WHAT HAPPENS NEXT" is always displayed irrespective of the title entered by the user

![image](https://user-images.githubusercontent.com/4592712/129310537-baa00d29-e5be-4923-bcd2-f1339be78132.png)

**Comment by nikolay83** [comment]
@sdgun
I think it's intentionally overridden by the static title when updating labels.

**Comment by sdgun** [comment]
@nikolay83 I thought the requirement was to show the title when coming from JD page by entering a title. 

![image](https://user-images.githubusercontent.com/4592712/129320263-e0cc7968-93b8-47fd-aa0a-d8a550a1e7a2.png)

**Comment by nikolay83** [comment]
@sdgun 
right you are!  

@mbaghel is on it.

**Comment by sdgun** [comment]
@nikolay83 I took the description of No matching profile as an example, this behavior(replacing role name with user entered title) should be there even if a matching role is found in JD flow(I didn't find any requirement change to this behavior). This fix is only adding the title when there is no matching profile.

**Comment by mbaghel** [comment]
@nikolay83 @sdgun  I made a PR to add the job title to matching role card as well. Please see #485

**Comment by sdgun** [comment]
@mbaghel @nikolay83 When a title is entered while there is a matching role to the entered skills, the position added does not show the title in the position list.


https://user-images.githubusercontent.com/4592712/129434733-b372465c-6bf6-455d-9e3f-10ae1173794c.mp4

**Comment by mbaghel** [comment]
I found the original specification from when I added the ability to insert a custom job title. At the time it was only intended to replace the job title for "custom roles". Did this requirement change? I think it makes sense to keep the title of the found role rather than to replace it with the user's arbitrary job title.

Relevant part of challenge overview from challenge [Taas Platform - Roles Intake - Post-release functional tweaks in UI](https://www.topcoder.com/challenges/90a05023-9d08-4644-8eb2-c8f6c9f93fd8):
> ...
>**Job title**
> If no roles are found, the position name that a customer will see in her list will be: a) Job title value - if it is provided, b) “Custom role” if Job title is not provided. This position must be reflected in the drop down list in the top right corner.
> 
> **No matching profiles” page**
> Add the Caption like in the "WE HAVE MATCHING PROFILES" page. The value of this caption will be the position name (see p. "Job title")
>...

**Comment by nikolay83** [comment]
@sdgun I think there is no best solution for it, and I doubt it'd prevent us from going live. So I suggest we accept it as it is.
@wdprice WDYT?

**Comment by sdgun** [comment]
@nikolay83 I don't think this issue should prevent the go live, it's a P3. But the behavior in current production is this.
