### ISSUE TITLE
Rate details doesn't show all the rates to the internal user, when user signs in after proceeding from an anonymous user

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#482]
**Steps**
Go to https://platform.topcoder-dev.com/taas/createnewteam without logging in
Proceed from any flow until sign in is prompted
Sign in as an internal user
Close the pop up and check the Rate details tab

Actual Behavior
All rates are not displayed 

Expected behavior
Internal user should see all rates

https://user-images.githubusercontent.com/4592712/129317823-52bd2c9e-d1ed-41c2-99ff-e1f54fa50e0e.mp4

**Comment by arpitchaudhari** [comment]
`niche` is not present in data.

UI Code:
```
<div styleName="cost">
  <h4>{formatRate(rates.niche)}</h4>
  <p>/Week</p>
</div>
```

JSON Data:
```
"rates": [
        {
          "global": 2500,
          "offShore": 10,
          "inCountry": 20,
          "rate20Global": 20,
          "rate30Global": 20,
          "rate20OffShore": 35,
          "rate30OffShore": 35,
          "rate20InCountry": 15,
          "rate30InCountry": 15
        },
        {
          "global": 25,
          "offShore": 5,
          "inCountry": 15,
          "rate20Global": 20,
          "rate30Global": 20,
          "rate20OffShore": 35,
          "rate30OffShore": 35,
          "rate20InCountry": 15,
          "rate30InCountry": 15
        }
      ],
```

**Comment by sdgun** [comment]
@arpitchaudhari Nothing to do with missing niche value here, you can see in the video the view of rate details is totally different when the user first sees the rate details after sign in and when the user checks it by selecting a role the second time. The first view is the view of the external user(less details) second view is the view we have to show to the internal user(show all rates)

**Comment by arpitchaudhari** [comment]
I was just informing it. I know the issue. I am working on it.

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed. Also tested the [impacted area](https://github.com/topcoder-platform/taas-app/issues/483#issuecomment-899053022)
