### ISSUE TITLE
Internal members should not see the last step(Refundable deposit payment) on the completeness box

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#483]
Steps
Go to intake app sign in as Tcconncopilot user
Search for a role
Check the step 4 on the completeness box

Internal members should not see this step

![image](https://user-images.githubusercontent.com/4592712/129329262-618ac9c5-9f7c-4be0-b915-f665c3738483.png)

**Comment by nikolay83** [comment]
@sdgun @lakshmiathreya 
The impact analysis for this and #482 may be 
- external users/anonymous viewing something they are not authorized to see, e.g. internal rates
- external users not viewing what they should, e.g. payment page
- internal viewing what they should not see, e.g. payment page

**Comment by sdgun** [comment]
@nikolay83 It shows 'Overview of the Results' step as the 3rd and 4th step now for both internal/external users. At the checkout page 4th step changes to 'Refundable Deposit Payment'

![image](https://user-images.githubusercontent.com/4592712/129485309-c34bc273-2215-4b8e-a18c-1033be5a2b75.png)

**Comment by nikolay83** [comment]
@yoution @sdgun 
I suggest an internal user doesn't see any 4th step in this list.

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/129512536-79c78c10-75c2-4e89-99a0-3815351abb86.png)

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/129528526-e408c9db-f828-4f1e-bb38-31e2ad079a11.png)
