### ISSUE TITLE
Team Creation & Connect Integration - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#5]
Teams will be created in v1.0 through Topcoder Connect.

Workflow as follows:

1. Click New Project
2. Choose Talent as a Service
3. Complete the forms

3a. Forms to be updated to utilize skill list from v5/skills w/ skillProvider = Topcoder. This list should reflect the available skills list on member profiles.
3b. Essential fields documented in v5/job API.

4. Upon completion of intake form, button appears that says "Take me to my project" (or similar language)
5. Project is created in v5/projects, jobs are added via v5/jobs & added as a job in RecruitCRM associated to "TaaS Intake Holding Company"
6. When clicked, button navigates the user to the corresponding project in TaaS App.

**Comment by maxceem** [comment]
> When clicked, button navigates the user to the corresponding project in TaaS App.

I would like to confirm this. In general, after project creation, we let users open the Project in **Connect App**. Should we make an exception here and open the project in **TaaS App**? (Now **Go to Project Dashboard** button opens the project in **Connect**)

![image](https://user-images.githubusercontent.com/146016/100899087-2264c680-34ca-11eb-84bf-b34440fe09c1.png)

**Comment by wdprice** [comment]
That is correct. There is currently a ticket being worked on to update this link in the Connect repo.

Additionally there is a ticket to put a button on the Connect page if a project type = talent-as-a-service which will direct the user to taas-app.

**Comment by maxceem** [comment]
Thanks, I missed this requirement in Connect task.

Just would refer to the corresponding issue in Connect here:
- Redirect to TaaS from the Project List https://github.com/appirio-tech/connect-app/issues/4195
- Create Jobs during when New Project is created https://github.com/appirio-tech/connect-app/issues/4130 (includes updating the link to the TaaS project)

**Comment by maxceem** [comment]
This can be tested on DEV using TEST01 environment of Connect App https://connect-test01.topcoder-dev.com/new-project/talent-as-a-service

**Comment by SathyaJayabal** [comment]
@maxceem , there are no skills listed in the TEST01 connect environment, while creating a taas project and defining talent requirements
<img width="1440" alt="Screenshot 2020-12-22 at 10 25 21 AM" src="https://user-images.githubusercontent.com/58783823/102850737-1d979080-4440-11eb-8f98-3acf17990830.png">

**Comment by SathyaJayabal** [comment]
@maxceem , the following functionality verified and works fine
Teams will be created in v1.0 through Topcoder Connect. After Taas project creation. link is displayed to Taas team 
Jobs created (job description, job duration and status) are carried over
On accessing the Taas Project from connect, button with link to Taas team is displayed




Project is created in v5/projects, jobs are added via v5/jobs & added as a job in RecruitCRM associated to "TaaS Intake Holding Company"
When clicked, button navigates the user to the corresponding project in TaaS App.

**Comment by maxceem** [comment]
> 1. V5/skills not listed in the Taas intake form in connect #5 (comment)

At the moment only `ubahn` / `bookingmanager` users can retrieve skills form v5. We have a ticket to create a new endpoint to return skills for any user https://github.com/topcoder-platform/taas-apis/issues/64.
So you may test it now with some `bookingmanager` for now.

> 2. Not able to verify if jobs created in RecruitCRM associated to "TaaS Intake Holding Company" - @wdprice , can you give details on how to verify this?

I guess it's not ready yet. We have a separate issue to track it https://github.com/topcoder-platform/taas-app/issues/11

**Comment by SathyaJayabal** [comment]
@maxceem @wdprice , the job start date and end date is calculated from the job creation date (taas project creation date) and duration of the job. reference point 2 below
https://github.com/appirio-tech/connect-app/issues/4130#issuecomment-736336081

**Comment by SathyaJayabal** [comment]
Verified skills selection for jobs/talent req using ubahn user
<img width="1440" alt="Screenshot 2020-12-23 at 12 55 24 PM" src="https://user-images.githubusercontent.com/58783823/102970823-3b3b2780-451e-11eb-99b5-479378aa4c5a.png">

**Comment by SathyaJayabal** [comment]
requires re testing  after https://github.com/appirio-tech/connect-app/issues/4206 updates

**Comment by sandhiyakavi** [comment]
Verified. Working as expected

<img width="957" alt="job_description" src="https://user-images.githubusercontent.com/55895538/105037252-0e3c4f00-5aa1-11eb-988e-7337a4487d86.png">
<img width="960" alt="project_created" src="https://user-images.githubusercontent.com/55895538/105037334-2ca24a80-5aa1-11eb-9636-34054639a0c8.png">
 
Button redirects correctly.
![image](https://user-images.githubusercontent.com/55895538/105037437-4f346380-5aa1-11eb-9539-b4c6c09413a5.png)

**Comment by SathyaJayabal** [comment]
verified in prod

Upon completion of intake form, button appears that says "Take me to my project" (or similar language)
Project is created in v5/projects, jobs are added via v5/jobs & added as a job in RecruitCRM associated to "TaaS Intake Holding Company"
When clicked, button navigates the user to the corresponding project in TaaS App.

<img width="1440" alt="Screenshot 2021-01-28 at 6 59 31 PM" src="https://user-images.githubusercontent.com/58783823/106150311-37e02f00-61a1-11eb-9d29-c4e87bf880bb.png">

<img width="1440" alt="Screenshot 2021-01-28 at 6 59 23 PM" src="https://user-images.githubusercontent.com/58783823/106150289-31ea4e00-61a1-11eb-9e73-6c80f3b9d26b.png">
