### ISSUE TITLE
Add link to the Connect Project

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#51]
On the request of Will on the Slack:

On each Team Details page, add a link "Open in Connect" which would open the same project in Connect App. At any of two places where arrows are pointing.

![image](https://user-images.githubusercontent.com/146016/104381903-e34c7b00-5535-11eb-9720-de5d43211c3d.png)

Add the same link to the project card menu on the My Teams page:

![image](https://user-images.githubusercontent.com/146016/104381850-cca62400-5535-11eb-8d6f-975ee8adb1d7.png)

**Comment by maxceem** [comment]
Done via 5d8fa560c174351556bad13280edef0bcb4e9634

![image](https://user-images.githubusercontent.com/146016/104382521-e8f69080-5536-11eb-8405-f4605842e683.png)

![image](https://user-images.githubusercontent.com/146016/104382541-f01d9e80-5536-11eb-9491-ce9c4a59c6ee.png)

**Comment by sandhiyakavi** [comment]
Verified. Working as expected

![image](https://user-images.githubusercontent.com/55895538/104408391-432f3a00-55a7-11eb-937c-73c5e0acf144.png)
![image](https://user-images.githubusercontent.com/55895538/104408420-580bcd80-55a7-11eb-89bf-82e015ec5d16.png)

https://user-images.githubusercontent.com/55895538/104408540-8ee1e380-55a7-11eb-9b76-36dd18ffe31b.mp4

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 40 32 PM" src="https://user-images.githubusercontent.com/58783823/106149883-c2745e80-61a0-11eb-93ef-3a91e2458578.png">
<img width="1440" alt="Screenshot 2021-01-28 at 7 40 51 PM" src="https://user-images.githubusercontent.com/58783823/106149900-c7391280-61a0-11eb-8992-fd5a4e24d480.png">
