### ISSUE TITLE
Scheduling 2nd meeting fails

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#518]
Steps to repdocue:
- Setup TaaS APP and TaaS Api locally as per [this guide](https://github.com/topcoder-platform/taas-app/wiki/Run-TaaS-App-with-TaaS-API-locally-to-test-Interview-Scheduling-using-Nylas).
- Run `npm run local:init` in taas api and create Job and Job Candidate
- Schedule 1st meeting with this job candidate, it would work good (internally it would create UserMeetingSettings for this user)
- Reload the page and schedule the second meeting, the server would return Internal Server Error

As pe debugging this happens because during sending request `POST https://api.schedule.nylas.com/manage/pages` we send `undefined` instead of calendar id:
```js
{
    "access_tokens": [
        "XXX"
    ],
    "slug": "tc-taas-interview-ee6193bd-6d6a-4cde-a7b5-629699bc38d5",
    "config": {
        "appearance": {
            "show_autoschedule": false
        },
        "booking": {
            "additional_guests_hidden": true,
            "opening_hours": [
                {
                    "end": "17:00",
                    "days": [
                        "M",
                        "T",
                        "W",
                        "R",
                        "F"
                    ],
                    "start": "06:00"
                },
                {
                    "start": "05:00",
                    "end": "16:00",
                    "days": [
                        "M",
                        "T",
                        "W",
                        "R",
                        "F"
                    ]
                }
            ],
            "name_field_hidden": true
        },
        "calendar_ids": {
            "undefined": {
                "availability": [
                    "17ths3j6058ol48kky74l48jz"
                ],
                "booking": "17ths3j6058ol48kky74l48jz"
            }
        },
        "event": {
            "duration": 30,
            "location": "Zoom link: https://us05web.zoom.us/j/89663700340?pwd=WkJmQWdLVnBWcVh2cS9XcG1Kd1pSdz09",
            "title": "Interview for job: Dummy title - at most 64 characters"
        },
        "expire_after": {
            "date": 1635242390,
            "uses": 1
        },
        "timezone": "Europe/Kiev"
    },
    "disableViewingPages": true
}
```

Expected behaviour:
- during the 1st meeting scheduling when UserMeetingSettings record is created `accountId` has be added during the `nylasCaldendar` record, but it's missing https://monosnap.com/file/kVfW0pyd8e5vHfiMViNIxjvKhN2mLG. (See this challenge for initial requirements https://www.topcoder.com/challenges/d4c83668-988f-4492-a1f5-66b119782406?tab=details)
- the second and future meeting creations should use calendar already added to UserMeetingSettings without error (maybe it's because of `accountId` maybe there is some other issue which has to be fixed in UI or API)

## Note

To work on this issue you would have to run TaaS App with TaaS API locally using

**Comment by sdgun** [comment]
Verifdied in production.
