### ISSUE TITLE
Hypen is displayed if date not added

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#53]
Description:

Hypen symbol is displayed if date not added
<img width="776" alt="hypen displayed" src="https://user-images.githubusercontent.com/55895538/104413224-4f1ff980-55b1-11eb-92d4-dcd880a4b274.png">

**Comment by maxceem** [comment]
I've replaces to `TBD`, is it what expected when there is no time information?

![image](https://user-images.githubusercontent.com/146016/104435278-de6ae400-5594-11eb-8af6-a58a6c068237.png)

**Comment by sandhiyakavi** [comment]
@maxceem Yes it's fine

**Comment by maxceem** [comment]
@sandhiyakavi I've marked it as `QA Pass on Dev` feel free to remove it if there is anything else.

**Comment by codejamtc** [comment]
**Fixed**: 🆗 in **Production** via [milestone v1.5](https://github.com/topcoder-platform/taas-app/milestone/3)
- Hypen symbol is displayed if date not added  🆗 

![bandicam 2021-02-26 09-37-40-332](https://user-images.githubusercontent.com/42398485/109253749-74da2880-7816-11eb-9773-442edd696477.jpg)
![bandicam 2021-02-26 09-37-51-103](https://user-images.githubusercontent.com/42398485/109253753-760b5580-7816-11eb-9669-f547238edcfe.jpg)
![bandicam 2021-02-26 09-37-56-435](https://user-images.githubusercontent.com/42398485/109253754-76a3ec00-7816-11eb-94e8-22c8918147ce.jpg)
