### ISSUE TITLE
The availability time is not getting saved once changed.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#549]
Description:

The availability time chosen in the Manage availability modal is not getting saved (updated) once changed. The first chosen availability time is shown each time.

![image](https://user-images.githubusercontent.com/55895538/139424899-a6fa058a-d7da-4cef-a194-24d29f9e6b89.png)

**Comment by maxceem** [comment]
Sum up:
- This issue is at backend TaaS API https://github.com/topcoder-platform/taas-apis
- Branch to work `dev`❗️
- Expected behaviour: when create new interview meeting, we have to update `defaultTimezone` and `defaultAvailableTime` inside UserMeetingSettings for the current user.

**Comment by maxceem** [comment]
Fixed by https://github.com/topcoder-platform/taas-apis/commit/70db75ff6eaaeb77d2ab77a638d12c55334bb9f5

**Comment by sdgun** [comment]
Verified, this issue is fixed. The changed time is saved and loaded the next time.

**Comment by sdgun** [comment]
Verified in production.
