### ISSUE TITLE
The start time/end time is not restricted based on the connected calender

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#558]
**Steps**
User connect a google calender
Try to schedule an interview for a time which is already booked in the calender  

Expected behavior
Should not allow to select a busy time

Actual behavior
Allows selecting any time

https://user-images.githubusercontent.com/4592712/139634406-ff0d2ef7-85f0-484b-8231-b0f38008f8ac.mp4

**Comment by maxceem** [comment]
@sdgun it doesn't take into account connected calendar here. Calendar time it taken into account when JC choose time:

![image](https://user-images.githubusercontent.com/146016/139836896-6b106ce4-65eb-4995-a828-18e8354bb634.png)

On this screen JC can only choose time which is:
- not occupied in the Customer's calendar
- selected as available during interview scheduling

**Comment by maxceem** [comment]
@sdgun I'm closing it as it looks like not an issue. But feel free to reopen it if needed.
