### ISSUE TITLE
After rescheduling an intrerview, the zoom link of the previous interview still works

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-app#592]
Steps
Schedule an interview
Reschedule it
Click the zoom link in the previous interview email

This link still works, do we want to keep it active?

**Comment by maxceem** [comment]
This is fine. Actually for the same interview zoom link is always the same even after we reschedule as this link it attached to the interview, not to a certain time. We just update it internally.

For now, I don't see any issue with this. As soon as we cancel the interview, such a link would get disabled.
