### ISSUE TITLE
My Teams Page - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#6]
My Teams page is the default landing page when selecting the TaaS Experience from the App Selector in the MFE framework.

My Teams page will:
- List all Projects the user has access to see via v5/projects WHERE type = 'talent-as-a-service'
- Display summary information of the project (Detailed below)
- Display team profile pictures (if available)

Team Summary info:
1.  Start-End date - Displayed values are determined by the resourceBookings associated to the project. Start date will be the earliest start date assigned any resourceBooking. EndDate will be the latest end date across all associated resourceBookings.
2. Time remaining - amount of time until the latest EndDate on any resourceBooking
3. Number of team members: X of Y. X=number of resourceBookings assigned to project; Y=SUM of numOpenings across all jobs (v5/jobs) associated with the project

**Comment by maxceem** [comment]
@wdprice at the moment this page doesn't have a pagination

1. As admin users would have access to all the TaaS projects (teams), there could be quite a long list of Teams. Should we implement pagination for the first release? Also, Project API at the moment has the limitation and returns maximum 20 projects per request, though we can relax this limitation if needed, but I guess we don't wanna list too many teams at once.

    ![image](https://user-images.githubusercontent.com/146016/101139798-b9409880-361a-11eb-8d9f-2ef7757981a7.png)

2.  Another thing to decide is the sorting order. At the moment Teams from API comes in the order of project creation (old first). We can sort Teams by last activity. So projects with the last activity would be shown first. For the first release we can just choose one filter order. And we can consider adding sorting options for the next releases. Something like this:

     ![image](https://user-images.githubusercontent.com/146016/101140024-0d4b7d00-361b-11eb-84e3-d56c14d0e5f0.png)

**Comment by maxceem** [comment]
@wdprice so far BookingManagers can see maximum 20 teams, should we implement agitation as per described in the previous comment? https://github.com/topcoder-platform/taas-app/issues/6#issuecomment-738642639

**Comment by wdprice** [comment]
I think pagination would be great if it can be done quickly.

In a future release we'll need a better way to handle larger lists, but for now pagination will do.

**Comment by maxceem** [comment]
@SathyaJayabal This is ready for QA.
Pagination is handled via separate issue https://github.com/topcoder-platform/taas-app/issues/37.

**Comment by SathyaJayabal** [comment]
My Teams page works as expected.

**Comment by SathyaJayabal** [comment]
Verified on Prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 04 15 PM" src="https://user-images.githubusercontent.com/58783823/106145517-a7532000-619b-11eb-989d-d686c69aa653.png">
