### ISSUE TITLE
Team Details Page (Top Bar) - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#7]
![image](https://user-images.githubusercontent.com/6014049/100247044-e77df400-2f07-11eb-96b2-b60a84cd6810.png)

Summary information similar to the summary info from My Teams.

Weekly cost is the SUM of customerRate for all currently active resourceBookings associated to the project.

Overall Rating should be hidden in the v1.0 release.

Report an issue will open a mailto: with a Subject Line of: "Issue reported on Project PROJECT_NAME"
Email to be sent to escalation email address defined in environmental variables. Initil value to be customersuccess@topcoder.com

**Comment by SathyaJayabal** [comment]
@wdprice , the subject line for Report an issue at present is
TaaS Issue: PROJECT NAME

Is this ok?

**Comment by wdprice** [comment]
This is acceptable @SathyaJayabal

**Comment by sandhiyakavi** [comment]
Verified.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102862478-81d44780-4474-11eb-9abc-c2dc61126a50.png)

**Comment by SathyaJayabal** [comment]
Verified on Prod
<img width="1129" alt="Screenshot 2021-01-28 at 7 06 05 PM" src="https://user-images.githubusercontent.com/58783823/106145756-ed0fe880-619b-11eb-8d3b-a4bb9ef677b2.png">
