### ISSUE TITLE
Job status updated to "Assigned" even though all positions are not filled

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-app#71]
Job status updated to "Assigned" even though all positions are not filled
Example:
Only 2 out of 3 positions were filled for this job, But the job status was updated to assigned.

Expected: Job status must be updated to "Assigned" only after all positions are filled.

cc @nkumar-topcoder 

<img width="1115" alt="Screenshot 2021-01-28 at 6 37 29 PM" src="https://user-images.githubusercontent.com/58783823/106142884-0c0c7b80-6198-11eb-8b86-d91587dad41d.png">

<img width="1389" alt="Screenshot 2021-01-28 at 6 37 11 PM" src="https://user-images.githubusercontent.com/58783823/106142865-0878f480-6198-11eb-9d7b-3d1ae560a542.png">

**Comment by maxceem** [comment]
It works as expected, let me provide you details @SathyaJayabal:
- Job 2 has 2 positions
- Job 1 has 1 position
- So in total there are 3 positions.
- As Job 2 has 2 resources assigned it's marked as assigned.

**Comment by SathyaJayabal** [comment]
@maxceem , thanks for the details. @nkumar-topcoder , this is not a bug as suspected and works as expected. I am closing this.
