### ISSUE TITLE
Change Job Candidate Creation Criteria

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#73]
Update the criteria to create a Job Candidate.

Current State - JobCandidate record created based on "Candidate Assigned" action from RCRM.

Future State - JobCandidate record should be created when the RCRM hiring status = `Ops Check Pass`

This request comes from the TaaS Ops team, who wants to ensure unapproved candidates are not presented to the customer.

**Comment by wdprice** [comment]
@nkumar-topcoder - can you check this out for feasibility?

**Comment by lakshmiathreya** [comment]
@nkumar-topcoder - need your help to test this on Prod. cc @sandhiyakavi

**Comment by nkumar-topcoder** [comment]
@lakshmiathreya  this was verified with @sandhiyakavi  during verification of new status `interview`
