### ISSUE TITLE
Enable Segment Analytics

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#78]
On the request of Will and accommodated by Tony we've enabled Segment Analytics.

- Each page would be tracked by analytics (I guess this would work only on PROD, because we have only one analytics key for PROD, so we wouldn't enable it on DEV)
- Each page has its own title in the browser (DEV + PROD):

    ![image](https://user-images.githubusercontent.com/146016/106947209-c53bfa00-6732-11eb-81e9-839951827726.png)
    
   ![image](https://user-images.githubusercontent.com/146016/106947242-ccfb9e80-6732-11eb-8725-ce4eac8d6b22.png)
   
   ![image](https://user-images.githubusercontent.com/146016/106947290-d84eca00-6732-11eb-8bd3-8fb63b928d5e.png)

**Comment by maxceem** [comment]
This issue has been done in 2 repositories:
- TaaS APP: https://github.com/topcoder-platform/taas-app/pull/50
- Frame https://github.com/topcoder-platform/micro-frontends-frame/pull/10

Note, analytics would be only enabled on PROD if we set `SEGMENT_ANALYTICS_KEY` environment variable, rebuild and redeploy https://github.com/topcoder-platform/micro-frontends-frame

**Comment by SathyaJayabal** [comment]
@maxceem , verified page titles on dev
<img width="247" alt="Screenshot 2021-02-05 at 11 06 49 AM" src="https://user-images.githubusercontent.com/58783823/106994238-69a95500-67a2-11eb-8991-4f36054bf7c8.png">
<img width="257" alt="Screenshot 2021-02-05 at 11 07 00 AM" src="https://user-images.githubusercontent.com/58783823/106994246-6b731880-67a2-11eb-8b19-3d7b21cd7462.png">
<img width="255" alt="Screenshot 2021-02-05 at 11 07 11 AM" src="https://user-images.githubusercontent.com/58783823/106994248-6ca44580-67a2-11eb-93cc-a5627cb140ec.png">

**Comment by sandhiyakavi** [comment]
Verified Page titles. Displaying as expected.

@maxceem Please let me know what else needs to be verified from QA side.

My Teams page.

![image](https://user-images.githubusercontent.com/55895538/109290957-aa5d3100-786b-11eb-94fc-d7d33a9a7a91.png)

Team Details page.
![image](https://user-images.githubusercontent.com/55895538/109291252-19d32080-786c-11eb-8eff-24b889c9440f.png)

Manage Access
![image](https://user-images.githubusercontent.com/55895538/109291296-26577900-786c-11eb-826d-009304e85ac3.png)

Resource Booking
![image](https://user-images.githubusercontent.com/55895538/109291359-3a9b7600-786c-11eb-8576-e0e2748b70ca.png)

Edit Resource Booking page
![image](https://user-images.githubusercontent.com/55895538/109291409-4be48280-786c-11eb-856b-e44f7156631e.png)

Create Job page
![image](https://user-images.githubusercontent.com/55895538/109291557-76364000-786c-11eb-9336-9934e4167965.png)

Job Details page
![image](https://user-images.githubusercontent.com/55895538/109291611-86e6b600-786c-11eb-96ad-c1d1c8d4b30f.png)

![image](https://user-images.githubusercontent.com/55895538/109291690-9960ef80-786c-11eb-9c06-964784b2ae83.png)

**Comment by maxceem** [comment]
@sandhiyakavi I think that's all that can be verified by QA. I've also asked Will and Tony to check if there is good data is coming to the analytics. I guess only a limited number of people have access there.
