### ISSUE TITLE
Team Details (Resource Bookings) - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#8]
![image](https://user-images.githubusercontent.com/6014049/100248059-06c95100-2f09-11eb-852e-6d78235fd215.png)

Displays a list of all resourceBookings associated with the project.

Filter bar is out of scope in v1.0 and should not be displayed.

Handle & Name information come from v5/users via v5/resourceBooking

Job Title (Developer in screenshot) is the name of the job from v5/users, via v5/resourceBooking

Start/End Dates, and customerRate come from v5/resourceBooking

Skill list % matched - the percentage of a users skills (from v5/users via resourceBookings) that match the assigned jobs skills (v5/jobs via resourceBookings)

The skill list contains the full list of user skills

Star Rating is out of scope at this time and should not be displayed.

Actions dropdown should contain the following actions:
1. Report an Issue
2. Request Extension

Both will initiate an email to the escalation environmental variable using mailto:. The subject lines will be prepopulated with "Issue Reported for Team Member MEMBERHANDLE on project PROJECTNAME" or "Extension requested for Team Member MEMBERHANDLE on project PROJECTNAME" respectively.

**Comment by SathyaJayabal** [comment]
> 
> Filter bar is out of scope in v1.0 and should not be displayed.
> 

@wdprice , filter bar is not removed yet. Do we need to remove it? It works partially now (does not work for filter by roles etc)

cc @maxceem

**Comment by maxceem** [comment]
@SathyaJayabal I believe we can keep it, and just fix filtering by "role".

I would track filtering by "role" with a separate issue https://github.com/topcoder-platform/taas-app/issues/34

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal I believe we can keep it, and just fix filtering by "role".
> 
> I would track filtering by "role" with a separate issue #34

Sure @maxceem , there were few more issues on the filter, we will update #34

**Comment by wdprice** [comment]
Confirmed - originally was listed out of scope but the team went above and beyond and get more done than expected.

**Comment by wdprice** [comment]
Just update the help text to reflect the capabilities.

**Comment by sandhiyakavi** [comment]
Verified. Working as expected.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 08 33 PM" src="https://user-images.githubusercontent.com/58783823/106146074-41b36380-619c-11eb-8631-a443243cc12c.png">
