### ISSUE TITLE
Team Details (Open Positions) - v1.0

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#9]
![image](https://user-images.githubusercontent.com/6014049/100249683-d682b200-2f0a-11eb-8110-1f5dd0d1221e.png)

List contains the jobs from v5/jobs that are associated to the project. Date / Rate are sourced from the job itself.

The status field will reflect the current state of jobCandidates:
- Sourcing: No jobCandidates currently assigned to job
- Candidates Available for Review: jobCandidates assigned to the job, and numOpenings > COUNT resourceBookings associated to Job
- Filled: numOpenings <= COUNT resourceBookings associated to Job
- Cancelled: Job has been cancelled by a TC admin

Select Candidates Button will direct to the jobCandidates view

**Comment by maxceem** [comment]
@wdprice at the moment we don't have a place in API to keep the open position rate. Should we add a new field to the API?

![image](https://user-images.githubusercontent.com/146016/100908502-3ca3a200-34d4-11eb-99d7-aa7436c389cc.png)

**Comment by maxceem** [comment]
@wdprice another thought on this. Who would be setting the rate for the jobs? customers or Topcoder managers?

If it would be the customers, we might also need to add a field for the rate in the TaaS intake form in Connect:

![image](https://user-images.githubusercontent.com/146016/101146100-4982db80-3623-11eb-9ebb-4abf55e2a96d.png)

**Comment by SathyaJayabal** [comment]
@wdprice, any updates on the rate associated with the job ? 

How does the logic work here? A job has a rate for  example $500, does that mean that the weekly pay for one position is $500? 

Each resource booking has a member rate and customer rate. Is the above rate that is considered as customer rate in the resource booking and what will be paid to the member?

**Comment by maxceem** [comment]
For the first release, we hide the job position rate as per https://github.com/topcoder-platform/taas-app/issues/32. It was discussed during the call.

**Comment by wdprice** [comment]
Confirming what Max noted above. This is something we'll solve for in a future release.

**Comment by SathyaJayabal** [comment]
@maxceem , for jobs which have candidates ready for review, the `Select Candidates` button is not available unless the job status is updated to `in-review`. When does the job status get updated to in-review during the actual flow? When a candidate applies to the job from RCRM, a jobCandidate record will be created on the platform for that job. Will the job status be updated then?

**Comment by SathyaJayabal** [comment]
@maxceem , also the automatic updation of the job status when the job positions are filled is not happening. When the resource bookings are created for a job and NUB of resource bookings >- number of open positions for the job the job status must be updated to "filled".

**Comment by SathyaJayabal** [comment]
@wdprice, just a suggestion, it will be good to display the number of open positions available for the job. This will help the user to decide how many candidates to mark as interested.
<img width="1440" alt="Screenshot 2020-12-22 at 12 50 23 PM" src="https://user-images.githubusercontent.com/58783823/102860777-7c670500-4454-11eb-937d-80a4863f8e16.png">

<img width="1087" alt="Screenshot 2020-12-22 at 12 48 00 PM" src="https://user-images.githubusercontent.com/58783823/102860765-783ae780-4454-11eb-898c-ff40db9b7982.png">

**Comment by wdprice** [comment]
Good suggestion, we can move that to a future release.

**Comment by SathyaJayabal** [comment]
@maxceem , this is ready for qa?

**Comment by maxceem** [comment]
Not yet, there are some API pending tasks not yet done.

**Comment by SathyaJayabal** [comment]
@maxceem , verified, works as expected. But we need to test automatic updates to the job status as and when candidates are assigned and selected etc. We can do this after RCRM integration.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-28 at 7 10 18 PM" src="https://user-images.githubusercontent.com/58783823/106146280-7f17f100-619c-11eb-8a8d-bb2d8073e05c.png">
